//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8xianliao20SGMomentNotification.h"

@class NSString;

@interface _TtC8xianliao22SGNewsSendNotification : _TtC8xianliao20SGMomentNotification
{
    // Error parsing type: , name: postId
    // Error parsing type: , name: seqno
    // Error parsing type: , name: sendUserId
}

+ (int)getConstructor;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic) long long sendUserId; // @synthesize sendUserId;
@property(nonatomic) long long seqno; // @synthesize seqno;
@property(nonatomic, copy) NSString *postId; // @synthesize postId;
- (unsigned char)getNotificationType;

@end

