//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

@interface _TtC8xianliao38SGMyCouponsHistoryRecordViewController : SGGoodsBaseViewController
{
    // Error parsing type: , name: userListView.storage
    // Error parsing type: , name: overdueListView.storage
    // Error parsing type: , name: scrollerView.storage
    // Error parsing type: , name: slideView.storage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)tapHaveOverdueCoupons;
- (void)tapHaveUseCoupons;
- (void)viewDidLoad;

@end

