//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface _TtC8xianliao29SGValidateBankCardByModuleReq : SGHTTPSReqModel
{
    // Error parsing type: , name: reservedMobile
    // Error parsing type: , name: cardNo
    // Error parsing type: , name: preToken
    // Error parsing type: , name: extInfo
    // Error parsing type: , name: moduleType
}

- (void).cxx_destruct;
- (id)init;
- (int)constructor;
@property(nonatomic) int moduleType; // @synthesize moduleType;
@property(nonatomic, copy) NSString *extInfo; // @synthesize extInfo;
@property(nonatomic, copy) NSString *preToken; // @synthesize preToken;
@property(nonatomic, copy) NSString *cardNo; // @synthesize cardNo;
@property(nonatomic, copy) NSString *reservedMobile; // @synthesize reservedMobile;

@end

