//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface _TtC8xianliao25SGBuildScanQRCodeOrderReq : SGHTTPSReqModel
{
    // Error parsing type: , name: receiveUserId
    // Error parsing type: , name: amount
    // Error parsing type: , name: remark
    // Error parsing type: , name: extraInfo
}

- (void).cxx_destruct;
- (id)init;
- (int)constructor;
@property(nonatomic, copy) NSString *extraInfo; // @synthesize extraInfo;
@property(nonatomic, copy) NSString *remark; // @synthesize remark;
@property(nonatomic) long long amount; // @synthesize amount;
@property(nonatomic) long long receiveUserId; // @synthesize receiveUserId;

@end

