//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSString;

@interface _TtC8xianliao34SGGetReceivablesInfoByAuthCodeResp : SGHTTPSResponseModel
{
    // Error parsing type: , name: receiveUserId
    // Error parsing type: , name: amount
    // Error parsing type: , name: revDesc
    // Error parsing type: , name: receiverNickName
    // Error parsing type: , name: receiverRealName
    // Error parsing type: , name: receiverSmallAvatarUrl
}

+ (int)constructor;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSString *receiverSmallAvatarUrl; // @synthesize receiverSmallAvatarUrl;
@property(nonatomic, copy) NSString *receiverRealName; // @synthesize receiverRealName;
@property(nonatomic, copy) NSString *receiverNickName; // @synthesize receiverNickName;
@property(nonatomic, copy) NSString *revDesc; // @synthesize revDesc;
@property(nonatomic) long long amount; // @synthesize amount;
@property(nonatomic) long long receiveUserId; // @synthesize receiveUserId;

@end

