//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC8xianliao22SGOrderCouponsListView : UIView
{
    // Error parsing type: , name: tableView.storage
    // Error parsing type: , name: noCouponsLab
    // Error parsing type: , name: noCouponsView.storage
    // Error parsing type: , name: couponsRequestMoreBlock
    // Error parsing type: , name: couponsSelectBlock
    // Error parsing type: , name: couponsType
    // Error parsing type: , name: dataSource
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)requestDataNet;
- (id)initWithFrame:(struct CGRect)arg1;

@end

