//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8xianliao23SGInterestPostGoodModel : NSObject
{
    // Error parsing type: , name: orderId
    // Error parsing type: , name: goodsId
    // Error parsing type: , name: goodsName
    // Error parsing type: , name: minSalePrice
    // Error parsing type: , name: totalSoldNumber
    // Error parsing type: , name: goodsPhotoUrlList
    // Error parsing type: , name: goodsDescription
    // Error parsing type: , name: shareCount
    // Error parsing type: , name: groupId
    // Error parsing type: , name: highestCommissionRateGroupTitle
    // Error parsing type: , name: tagPrice
    // Error parsing type: , name: activityPriceName
}

- (void).cxx_destruct;
- (id)init;

@end

