//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8xianliao19SGInterestHttpModel.h"

@class NSString;

@interface _TtC8xianliao15SGEditMomentReq : _TtC8xianliao19SGInterestHttpModel
{
    // Error parsing type: , name: localId
    // Error parsing type: , name: postId
    // Error parsing type: , name: textContent
    // Error parsing type: , name: posstateInfotId
    // Error parsing type: , name: mediaFlag
    // Error parsing type: , name: mediaConstructor
    // Error parsing type: , name: mediaAttribute
}

- (void).cxx_destruct;
- (id)init;
- (int)constructor;
@property(nonatomic, copy) NSString *mediaAttribute; // @synthesize mediaAttribute;
@property(nonatomic) int mediaConstructor; // @synthesize mediaConstructor;
@property(nonatomic) _Bool mediaFlag; // @synthesize mediaFlag;
@property(nonatomic, copy) NSString *posstateInfotId; // @synthesize posstateInfotId;
@property(nonatomic, copy) NSString *textContent; // @synthesize textContent;
@property(nonatomic, copy) NSString *postId; // @synthesize postId;
@property(nonatomic) long long localId; // @synthesize localId;

@end

