//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC8xianliao15SGInterestImage : NSObject
{
    // Error parsing type: , name: url
    // Error parsing type: , name: width
    // Error parsing type: , name: height
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) int height; // @synthesize height;
@property(nonatomic) int width; // @synthesize width;
@property(nonatomic, copy) NSString *url; // @synthesize url;

@end

