//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8xianliao20SGMomentNotification.h"

@class NSString;

@interface _TtC8xianliao27SGMomentForwardNotification : _TtC8xianliao20SGMomentNotification
{
    // Error parsing type: , name: postId
    // Error parsing type: , name: sendUserId
    // Error parsing type: , name: postType
    // Error parsing type: , name: pageId
    // Error parsing type: , name: momentTextContent
    // Error parsing type: , name: mediaFlag
    // Error parsing type: , name: mediaConstructor
    // Error parsing type: , name: mediaAttribute
    // Error parsing type: , name: forwardUserId
    // Error parsing type: , name: sendUserNickName
    // Error parsing type: , name: sendUserSmallAvatarUrl
    // Error parsing type: , name: referenceUserNickName
    // Error parsing type: , name: referenceSmallAvatarUrl
    // Error parsing type: , name: forwardPostId
    // Error parsing type: , name: notificationTime
}

+ (int)getConstructor;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic) long long notificationTime; // @synthesize notificationTime;
@property(nonatomic, copy) NSString *forwardPostId; // @synthesize forwardPostId;
@property(nonatomic, copy) NSString *referenceSmallAvatarUrl; // @synthesize referenceSmallAvatarUrl;
@property(nonatomic, copy) NSString *referenceUserNickName; // @synthesize referenceUserNickName;
@property(nonatomic, copy) NSString *sendUserSmallAvatarUrl; // @synthesize sendUserSmallAvatarUrl;
@property(nonatomic, copy) NSString *sendUserNickName; // @synthesize sendUserNickName;
@property(nonatomic) long long forwardUserId; // @synthesize forwardUserId;
@property(nonatomic, copy) NSString *mediaAttribute; // @synthesize mediaAttribute;
@property(nonatomic) int mediaConstructor; // @synthesize mediaConstructor;
@property(nonatomic) _Bool mediaFlag; // @synthesize mediaFlag;
@property(nonatomic, copy) NSString *momentTextContent; // @synthesize momentTextContent;
@property(nonatomic) long long pageId; // @synthesize pageId;
@property(nonatomic) unsigned char postType; // @synthesize postType;
@property(nonatomic) long long sendUserId; // @synthesize sendUserId;
@property(nonatomic, copy) NSString *postId; // @synthesize postId;
- (unsigned char)getNotificationType;

@end

