//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@class UITableView, UIView, _TtC8xianliao25SGQueryOpenShopGroupsResp;

@interface _TtC8xianliao21SGNoBuyViewController : SGViewController
{
    // Error parsing type: , name: resp
    // Error parsing type: , name: cellIdentify
    // Error parsing type: , name: tableView
    // Error parsing type: , name: tableHeaderView
}

+ (id)getSGNoBuyViewController;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic) __weak UIView *tableHeaderView; // @synthesize tableHeaderView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;
@property(nonatomic, retain) _TtC8xianliao25SGQueryOpenShopGroupsResp *resp; // @synthesize resp;

@end

