//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface _TtC8xianliao23SGPayScanQRCodeOrderReq : SGHTTPSReqModel
{
    // Error parsing type: , name: payType
    // Error parsing type: , name: amount
    // Error parsing type: , name: transactionId
    // Error parsing type: , name: payPasswd
    // Error parsing type: , name: bankCardNo
}

- (void).cxx_destruct;
- (id)init;
- (int)constructor;
@property(nonatomic, copy) NSString *bankCardNo; // @synthesize bankCardNo;
@property(nonatomic, copy) NSString *payPasswd; // @synthesize payPasswd;
@property(nonatomic, copy) NSString *transactionId; // @synthesize transactionId;
@property(nonatomic) long long amount; // @synthesize amount;
@property(nonatomic) int payType; // @synthesize payType;

@end

