//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSArray;

@interface _TtC8xianliao28SGGetMyHistoryMomentListResp : SGHTTPSResponseModel
{
    // Error parsing type: , name: postList
    // Error parsing type: , name: hasNextFlag
    // Error parsing type: , name: maxOffset
    // Error parsing type: , name: minOffset
}

+ (id)modelContainerPropertyGenericClass;
+ (int)constructor;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic) long long minOffset; // @synthesize minOffset;
@property(nonatomic) long long maxOffset; // @synthesize maxOffset;
@property(nonatomic) _Bool hasNextFlag; // @synthesize hasNextFlag;
@property(nonatomic, copy) NSArray *postList; // @synthesize postList;

@end

