//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@class NSArray, NSLayoutConstraint, UIButton, UICollectionView, UILabel, UIScrollView, UITextField, _TtC8xianliao16IBCornerableView, _TtC8xianliao19SGGCGoodsBannerView;

@interface _TtC8xianliao29SGGCGoodsDetailViewController : SGViewController
{
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: goodsName
    // Error parsing type: , name: marketPrice
    // Error parsing type: , name: totalGCNum
    // Error parsing type: , name: gcNum
    // Error parsing type: , name: goodsNum
    // Error parsing type: , name: progressView
    // Error parsing type: , name: progressWidthConstraint
    // Error parsing type: , name: goodsDetailCollectionView
    // Error parsing type: , name: goodsDetailCollectionViewHeight
    // Error parsing type: , name: cycleView
    // Error parsing type: , name: countTextFeild
    // Error parsing type: , name: saleOutViews
    // Error parsing type: , name: payButton
    // Error parsing type: , name: endLabel
    // Error parsing type: , name: maxNum
    // Error parsing type: , name: accountInfo
    // Error parsing type: , name: activityId
    // Error parsing type: , name: heighCache
    // Error parsing type: , name: goodsInfo
    // Error parsing type: , name: leftNavItem
    // Error parsing type: , name: rightNavItem
    // Error parsing type: , name: navBackAlpha
    // Error parsing type: , name: step
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;
- (void)add:(id)arg1;
- (void)sub:(id)arg1;
- (void)buy:(id)arg1;
- (void)seeAllTap:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UILabel *endLabel; // @synthesize endLabel;
@property(nonatomic) __weak UIButton *payButton; // @synthesize payButton;
@property(nonatomic, copy) NSArray *saleOutViews; // @synthesize saleOutViews;
@property(nonatomic) __weak UITextField *countTextFeild; // @synthesize countTextFeild;
@property(nonatomic) __weak _TtC8xianliao19SGGCGoodsBannerView *cycleView; // @synthesize cycleView;
@property(nonatomic) __weak NSLayoutConstraint *goodsDetailCollectionViewHeight; // @synthesize goodsDetailCollectionViewHeight;
@property(nonatomic) __weak UICollectionView *goodsDetailCollectionView; // @synthesize goodsDetailCollectionView;
@property(nonatomic) __weak NSLayoutConstraint *progressWidthConstraint; // @synthesize progressWidthConstraint;
@property(nonatomic) __weak _TtC8xianliao16IBCornerableView *progressView; // @synthesize progressView;
@property(nonatomic) __weak UILabel *goodsNum; // @synthesize goodsNum;
@property(nonatomic) __weak UILabel *gcNum; // @synthesize gcNum;
@property(nonatomic) __weak UILabel *totalGCNum; // @synthesize totalGCNum;
@property(nonatomic) __weak UILabel *marketPrice; // @synthesize marketPrice;
@property(nonatomic) __weak UILabel *goodsName; // @synthesize goodsName;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView;

@end

