//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC10HHJPreview19SGPreviewScrollView : UIView
{
    // Error parsing type: , name: imageView
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: loadingView.storage
    // Error parsing type: , name: delegate
    // Error parsing type: , name: beginDragging
    // Error parsing type: , name: startDragging
    // Error parsing type: , name: startPoint
    // Error parsing type: , name: animateImageView
    // Error parsing type: , name: frameOfOriginalOfImageView
    // Error parsing type: , name: lastPoint
    // Error parsing type: , name: totalOffset
    // Error parsing type: , name: index
}

- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)longPress:(id)arg1;
- (void)doubleTap:(id)arg1;
- (void)oneTapDismiss:(id)arg1;
@property(nonatomic) struct CGRect frame;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

