//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@interface _TtC8xianliao18SGDeleteStickerReq : SGHTTPSReqModel
{
    // Error parsing type: , name: userId
    // Error parsing type: , name: stickerId
}

- (id)init;
- (int)constructor;
@property(nonatomic) long long stickerId; // @synthesize stickerId;
@property(nonatomic) long long userId; // @synthesize userId;

@end

