//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8xianliao14SGInterestCell.h"

@class UIButton, UIImageView, UILabel;

@interface _TtC8xianliao22SGInterestPostFailCell : _TtC8xianliao14SGInterestCell
{
    // Error parsing type: , name: iconIV
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: stateLabel
    // Error parsing type: , name: resendButton
    // Error parsing type: , name: closeButton
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)closeSend:(id)arg1;
- (void)reSend:(id)arg1;
@property(nonatomic) __weak UIButton *closeButton; // @synthesize closeButton;
@property(nonatomic) __weak UIButton *resendButton; // @synthesize resendButton;
@property(nonatomic) __weak UILabel *stateLabel; // @synthesize stateLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UIImageView *iconIV; // @synthesize iconIV;

@end

