//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@interface _TtC8xianliao31SGSetPaymentAmoutViewController : SGViewController
{
    // Error parsing type: , name: amoutTextField.storage
    // Error parsing type: , name: remarkTextField.storage
    // Error parsing type: , name: sureButton.storage
    // Error parsing type: , name: setAmoutSuccessBlock
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;
- (void)sureButtonClick;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)viewDidLoad;

@end

