//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@interface _TtC8xianliao23SGGroupRecomSeatrchCell : UITableViewCell
{
    // Error parsing type: , name: goodIconView
    // Error parsing type: , name: goodNameLab
    // Error parsing type: , name: priceLab
    // Error parsing type: , name: targetPriceLab
    // Error parsing type: , name: addButton
    // Error parsing type: , name: deleteButton
    // Error parsing type: , name: soldNumberLab
    // Error parsing type: , name: commissionLab
    // Error parsing type: , name: clearAddButton
    // Error parsing type: , name: clearDeleteButton
    // Error parsing type: , name: addOrDeleteBlouser
    // Error parsing type: , name: goodModel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)deleteButtonClick;
- (void)addButtonClick;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

