//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC8xianliao24SGInterestExternInfoCell.h"

@class UIImageView, UILabel;

@interface _TtC8xianliao21SGInterestFictionCell : _TtC8xianliao24SGInterestExternInfoCell
{
    // Error parsing type: , name: coverIV
    // Error parsing type: , name: nameLabel
    // Error parsing type: , name: scoreLabel
    // Error parsing type: , name: descriptionLabel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *descriptionLabel; // @synthesize descriptionLabel;
@property(nonatomic) __weak UILabel *scoreLabel; // @synthesize scoreLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel;
@property(nonatomic) __weak UIImageView *coverIV; // @synthesize coverIV;

@end

