//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@interface _TtC8xianliao33SGLoginServerResultViewController : SGViewController
{
    // Error parsing type: , name: iconVIew.storage
    // Error parsing type: , name: tipLab.storage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)backAction;
- (void)viewDidLoad;
- (void)setSuccessOrFailerWithIsSuccess:(_Bool)arg1 error:(id)arg2;

@end

