//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8xianliao21SGRefundInfoListModel : NSObject
{
    // Error parsing type: , name: leftName
    // Error parsing type: , name: rightTitle
    // Error parsing type: , name: chooseContent
    // Error parsing type: , name: chooseContentColor
    // Error parsing type: , name: isHiddenArrow
    // Error parsing type: , name: isHiddenBottomLine
    // Error parsing type: , name: amoutStr
    // Error parsing type: , name: textFieldText
    // Error parsing type: , name: textFieldCountLimit
    // Error parsing type: , name: textFieldPlaceText
    // Error parsing type: , name: cellType
}

- (void).cxx_destruct;
- (id)init;

@end

