//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

@class SGDialogs, SGGetGroupShopApplyStatusResp;

@interface _TtC8xianliao25SGGoodsMineViewController : SGGoodsBaseViewController
{
    // Error parsing type: , name: sellerBeforeDeliveredNumberButton.storage
    // Error parsing type: , name: sellerBeforeSettleNumberButton.storage
    // Error parsing type: , name: sellerAfterDeliveredNumberButton.storage
    // Error parsing type: , name: buyerBeforeDeliveredNumberButton.storage
    // Error parsing type: , name: buyerAfterDeliveredNumberButton.storage
    // Error parsing type: , name: buyerBeforePayNumberButton.storage
    // Error parsing type: , name: openShopButton.storage
    // Error parsing type: , name: groupDialogs
    // Error parsing type: , name: statusResp
    // Error parsing type: , name: groupResp
    // Error parsing type: , name: bgScrollView
    // Error parsing type: , name: sellerBgView
    // Error parsing type: , name: groupView
    // Error parsing type: , name: buyerBgView
    // Error parsing type: , name: buyerWhiteBgView
    // Error parsing type: , name: isSuccessBlock
    // Error parsing type: , name: type
    // Error parsing type: , name: tallHeight
    // Error parsing type: , name: resp
    // Error parsing type: , name: backTopIconView
    // Error parsing type: , name: loadFildView.storage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)address;
- (void)openButtonShopCLick;
- (void)showSellerOrderListWithSender:(id)arg1;
- (void)showBuyerOrderListWithSender:(id)arg1;
- (void)ownerRecommand;
- (void)closeShop;
- (void)buyerCoupon;
- (void)sellerMyCoupon;
- (void)sellerMyIncome;
- (id)getBtnWithText:(id)arg1 imageName:(id)arg2 frame:(struct CGRect)arg3 action:(SEL)arg4;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)itemClick;
- (void)viewDidLoad;
- (void)backAction;
@property(nonatomic, retain) SGGetGroupShopApplyStatusResp *statusResp; // @synthesize statusResp;
@property(nonatomic, retain) SGDialogs *groupDialogs; // @synthesize groupDialogs;

@end

