//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8xianliao16SGUploadGPSModel : NSObject
{
    // Error parsing type: , name: lng
    // Error parsing type: , name: lat
}

- (id)init;
@property(nonatomic) double lat; // @synthesize lat;
@property(nonatomic) double lng; // @synthesize lng;

@end

