//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class _TtC8xianliao18SGInterestGoodCell;

@protocol _TtP8xianliao30SGInterestGoodBaseCellProtocol_

@optional
- (void)didPayAwayClickWithCell:(_TtC8xianliao18SGInterestGoodCell *)arg1;
@end

