//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JYPacketViewController.h"

#import "UITapLabelDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField;

@interface AddCardStepBViewController : JYPacketViewController <UITextFieldDelegate, UITapLabelDelegate>
{
    float CELL_H;
    float CELL_T_H;
    float CELL_S_H;
    UITextField *CardF;
    _Bool _isAuth;
    _Bool _isIdentify;
    NSString *_userName;
    NSString *_userID;
}

@property(nonatomic) _Bool isIdentify; // @synthesize isIdentify=_isIdentify;
@property(nonatomic) _Bool isAuth; // @synthesize isAuth=_isAuth;
@property(retain, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)doClickActionNext;
- (void)doActionClickHidden;
- (void)doActionChangeFrameWithTag:(long long)arg1 keyBoardDone:(_Bool)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)tapLabel:(id)arg1 touchesWithTag:(long long)arg2;
- (void)postGetUserBankCardRequestData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

