//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface AddressVO : NSObject <NSCoding>
{
    _Bool _defaultFlag;
    int _addressType;
    long long _addressId;
    NSString *_realName;
    NSString *_mobile;
    NSString *_postcode;
    NSString *_province;
    NSString *_city;
    NSString *_area;
    NSString *_detailedAddress;
}

@property(nonatomic) int addressType; // @synthesize addressType=_addressType;
@property(nonatomic) _Bool defaultFlag; // @synthesize defaultFlag=_defaultFlag;
@property(copy, nonatomic) NSString *detailedAddress; // @synthesize detailedAddress=_detailedAddress;
@property(copy, nonatomic) NSString *area; // @synthesize area=_area;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *postcode; // @synthesize postcode=_postcode;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *realName; // @synthesize realName=_realName;
@property(nonatomic) long long addressId; // @synthesize addressId=_addressId;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

