//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "AGEmojiPageViewDelegate-Protocol.h"
#import "SGGiftListCollectionViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, SGGiftListCollectionView, SGInputScoGifItemView, UIButton, UIPageControl, UIScrollView, UISegmentedControl;
@protocol AGEmojiKeyboardViewDataSource, AGEmojiKeyboardViewDelegate;

@interface AGEmojiKeyboardView : UIView <UIScrollViewDelegate, AGEmojiPageViewDelegate, SGGiftListCollectionViewDelegate>
{
    _Bool _isSelectGif;
    UISegmentedControl *_segmentsBar;
    UIPageControl *_pageControl;
    UIScrollView *_emojiPagesScrollView;
    id <AGEmojiKeyboardViewDelegate> _delegate;
    id <AGEmojiKeyboardViewDataSource> _dataSource;
    long long _dialogId;
    CDUnknownBlockType _sendBlock;
    CDUnknownBlockType _addEmojiBlock;
    CDUnknownBlockType _stickerImageBlock;
    NSDictionary *_emojis;
    NSMutableArray *_pageViews;
    NSString *_category;
    SGInputScoGifItemView *_gifItemView;
    SGGiftListCollectionView *_gifListView;
    UIButton *_sendButton;
    UIButton *_addEmojiButton;
    NSArray *_stickerImageList;
}

@property(retain, nonatomic) NSArray *stickerImageList; // @synthesize stickerImageList=_stickerImageList;
@property(retain, nonatomic) UIButton *addEmojiButton; // @synthesize addEmojiButton=_addEmojiButton;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) SGGiftListCollectionView *gifListView; // @synthesize gifListView=_gifListView;
@property(nonatomic) _Bool isSelectGif; // @synthesize isSelectGif=_isSelectGif;
@property(retain, nonatomic) SGInputScoGifItemView *gifItemView; // @synthesize gifItemView=_gifItemView;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
@property(retain, nonatomic) NSMutableArray *pageViews; // @synthesize pageViews=_pageViews;
@property(retain, nonatomic) NSDictionary *emojis; // @synthesize emojis=_emojis;
@property(copy, nonatomic) CDUnknownBlockType stickerImageBlock; // @synthesize stickerImageBlock=_stickerImageBlock;
@property(copy, nonatomic) CDUnknownBlockType addEmojiBlock; // @synthesize addEmojiBlock=_addEmojiBlock;
@property(copy, nonatomic) CDUnknownBlockType sendBlock; // @synthesize sendBlock=_sendBlock;
@property(nonatomic) long long dialogId; // @synthesize dialogId=_dialogId;
@property(nonatomic) __weak id <AGEmojiKeyboardViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <AGEmojiKeyboardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIScrollView *emojiPagesScrollView; // @synthesize emojiPagesScrollView=_emojiPagesScrollView;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UISegmentedControl *segmentsBar; // @synthesize segmentsBar=_segmentsBar;
- (void).cxx_destruct;
- (void)emojiPageViewDidPressBackSpace:(id)arg1;
- (void)emojiPageView:(id)arg1 didUseEmoji:(id)arg2;
- (void)setInRecentsEmoji:(id)arg1;
- (id)emojiTextsForCategory:(id)arg1 fromIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (unsigned long long)numberOfPagesForCategory:(id)arg1 inFrameSize:(struct CGSize)arg2;
- (id)emojiListForCategory:(id)arg1;
- (unsigned long long)numberOfRowsForFrameSize:(struct CGSize)arg1;
- (unsigned long long)numberOfColumnsForFrameSize:(struct CGSize)arg1;
- (void)purgePageViews;
- (void)setPage:(long long)arg1;
- (void)setEmojiPageViewInScrollView:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)usableEmojiPageViewIsImage:(_Bool)arg1;
- (id)synthesizeEmojiPageViewIsImage:(_Bool)arg1;
- (_Bool)requireToSetPageViewForIndex:(unsigned long long)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)pageControlTouched:(id)arg1;
- (void)categoryChangedViaSegmentsBar:(id)arg1;
- (void)setSelectedCategoryImageInSegmentControl:(id)arg1 atIndex:(long long)arg2;
- (_Bool)isImage;
- (void)layoutSubviews;
- (void)setSendButtonEnableWithText:(id)arg1;
- (void)sendButtonClickToSendText;
- (void)didSelectGifCell:(id)arg1;
- (void)scrollViewScrollPage:(id)arg1;
- (void)addEmojiButtonClick;
- (id)initWithFrame:(struct CGRect)arg1 dataSource:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 dataSource:(id)arg2 currentDialogId:(long long)arg3;
- (void)setRecentEmojis:(id)arg1;
- (id)recentEmojis;
- (id)imagesForNonSelectedSegments;
- (id)imagesForSelectedSegments;
- (unsigned long long)recentEmojisMaintainedCount;
- (long long)defaultSelectedCategory;
- (id)categoryNameAtIndex:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

