//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBStringInt64Dictionary;

@interface CheckMessageCompressReq : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBStringInt64Dictionary *groupOffset; // @dynamic groupOffset;
@property(readonly, nonatomic) unsigned long long groupOffset_Count; // @dynamic groupOffset_Count;
@property(nonatomic) long long offset; // @dynamic offset;

@end

