//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface EMVoiceConverter : NSObject
{
}

+ (int)wavToAmr:(id)arg1 amrSavePath:(id)arg2;
+ (int)amrToWav:(id)arg1 wavSavePath:(id)arg2;
+ (int)isAMRFile:(id)arg1;
+ (int)isMP3File:(id)arg1;

@end

