//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt64Array, NSString;

@interface ForwardMessageToGroupChatReq : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBInt64Array *atArray; // @dynamic atArray;
@property(readonly, nonatomic) unsigned long long atArray_Count; // @dynamic atArray_Count;
@property(nonatomic) long long groupId; // @dynamic groupId;
@property(nonatomic) long long localId; // @dynamic localId;
@property(copy, nonatomic) NSString *mediaAttribute; // @dynamic mediaAttribute;
@property(copy, nonatomic) NSString *mediaAttributeReferenced; // @dynamic mediaAttributeReferenced;
@property(nonatomic) int mediaConstructor; // @dynamic mediaConstructor;
@property(nonatomic) int mediaConstructorReferenced; // @dynamic mediaConstructorReferenced;
@property(nonatomic) _Bool mediaFlag; // @dynamic mediaFlag;
@property(nonatomic) _Bool mediaFlagReferenced; // @dynamic mediaFlagReferenced;
@property(nonatomic) long long msgDestIdReferenced; // @dynamic msgDestIdReferenced;
@property(nonatomic) _Bool msgGroupFlagReferenced; // @dynamic msgGroupFlagReferenced;
@property(nonatomic) long long msgGroupIdReferenced; // @dynamic msgGroupIdReferenced;
@property(nonatomic) long long msgIdReferenced; // @dynamic msgIdReferenced;
@property(copy, nonatomic) NSString *msgPostContent; // @dynamic msgPostContent;
@property(copy, nonatomic) NSString *msgPostContentReferenced; // @dynamic msgPostContentReferenced;
@property(copy, nonatomic) NSString *msgPreContent; // @dynamic msgPreContent;
@property(copy, nonatomic) NSString *msgPreContentReferenced; // @dynamic msgPreContentReferenced;
@property(nonatomic) long long msgSendTimeReferenced; // @dynamic msgSendTimeReferenced;
@property(nonatomic) long long msgSrcIdReferenced; // @dynamic msgSrcIdReferenced;

@end

