//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt64Array, NSString;

@interface GetDialogKeyReq : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *clientSign; // @dynamic clientSign;
@property(retain, nonatomic) GPBInt64Array *destIdArray; // @dynamic destIdArray;
@property(readonly, nonatomic) unsigned long long destIdArray_Count; // @dynamic destIdArray_Count;

@end

