//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt64Array, NSMutableDictionary, NSString;

@interface GetDialogKeyResp : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long dialogKeyVersion; // @dynamic dialogKeyVersion;
@property(retain, nonatomic) NSMutableDictionary *entry; // @dynamic entry;
@property(readonly, nonatomic) unsigned long long entry_Count; // @dynamic entry_Count;
@property(nonatomic) int errorCode; // @dynamic errorCode;
@property(copy, nonatomic) NSString *errorMessage; // @dynamic errorMessage;
@property(retain, nonatomic) GPBInt64Array *retryUidArray; // @dynamic retryUidArray;
@property(readonly, nonatomic) unsigned long long retryUidArray_Count; // @dynamic retryUidArray_Count;
@property(copy, nonatomic) NSString *serverSign; // @dynamic serverSign;

@end

