//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GetFriendApplyListResp_FriendApply : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int addMeType; // @dynamic addMeType;
@property(nonatomic) _Bool agreeFlag; // @dynamic agreeFlag;
@property(copy, nonatomic) NSString *leaveComments; // @dynamic leaveComments;
@property(nonatomic) _Bool newFlag; // @dynamic newFlag;
@property(copy, nonatomic) NSString *nickName; // @dynamic nickName;
@property(nonatomic) long long rowId; // @dynamic rowId;
@property(copy, nonatomic) NSString *smallAvatarURL; // @dynamic smallAvatarURL;
@property(nonatomic) long long userId; // @dynamic userId;
@property(copy, nonatomic) NSString *xianliaoId; // @dynamic xianliaoId;

@end

