//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GetGroupMessageShareModel : NSObject
{
    long long _destUin;
    long long _score;
    long long _maxSeqno;
    long long _reqUin;
}

+ (id)initWtih:(long long)arg1 score:(long long)arg2 maxSeqno:(long long)arg3 reqUin:(long long)arg4;
@property(nonatomic) long long reqUin; // @synthesize reqUin=_reqUin;
@property(nonatomic) long long maxSeqno; // @synthesize maxSeqno=_maxSeqno;
@property(nonatomic) long long score; // @synthesize score=_score;
@property(nonatomic) long long destUin; // @synthesize destUin=_destUin;

@end

