//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GetGroupChatHistoryMessageResp : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *dialogMessageArray; // @dynamic dialogMessageArray;
@property(readonly, nonatomic) unsigned long long dialogMessageArray_Count; // @dynamic dialogMessageArray_Count;
@property(nonatomic) int errorCode; // @dynamic errorCode;
@property(copy, nonatomic) NSString *errorMessage; // @dynamic errorMessage;
@property(nonatomic) long long groupId; // @dynamic groupId;
@property(nonatomic) _Bool hasNext; // @dynamic hasNext;
@property(nonatomic) long long minMsgId; // @dynamic minMsgId;

@end

