//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GetGatewayIpListResp : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *antiDosAttackIpListArray; // @dynamic antiDosAttackIpListArray;
@property(readonly, nonatomic) unsigned long long antiDosAttackIpListArray_Count; // @dynamic antiDosAttackIpListArray_Count;
@property(nonatomic) int errorCode; // @dynamic errorCode;
@property(copy, nonatomic) NSString *errorMessage; // @dynamic errorMessage;
@property(retain, nonatomic) NSMutableArray *foreignIpListArray; // @dynamic foreignIpListArray;
@property(readonly, nonatomic) unsigned long long foreignIpListArray_Count; // @dynamic foreignIpListArray_Count;
@property(retain, nonatomic) NSMutableArray *ipListArray; // @dynamic ipListArray;
@property(readonly, nonatomic) unsigned long long ipListArray_Count; // @dynamic ipListArray_Count;
@property(retain, nonatomic) NSMutableArray *tiebaURLArray; // @dynamic tiebaURLArray;
@property(readonly, nonatomic) unsigned long long tiebaURLArray_Count; // @dynamic tiebaURLArray_Count;

@end

