//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GetGroupInvitationListResp_GroupInvite : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool agreedFlag; // @dynamic agreedFlag;
@property(nonatomic) long long agreedTime; // @dynamic agreedTime;
@property(nonatomic) long long createTime; // @dynamic createTime;
@property(nonatomic) _Bool expiredFlag; // @dynamic expiredFlag;
@property(nonatomic) long long invitationId; // @dynamic invitationId;
@property(copy, nonatomic) NSString *memberNickName; // @dynamic memberNickName;
@property(copy, nonatomic) NSString *memberSmallAvatarURL; // @dynamic memberSmallAvatarURL;
@property(nonatomic) long long memberUid; // @dynamic memberUid;
@property(copy, nonatomic) NSString *referenceNickName; // @dynamic referenceNickName;
@property(nonatomic) long long referenceUid; // @dynamic referenceUid;

@end

