//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GroupMemberSilenceInfo : GPBMessage
{
}

+ (id)descriptor;
+ (id)sgSilencememberparaseWithDic:(id)arg1;
- (id)loadSilenceMemberDic;

// Remaining properties
@property(nonatomic) long long endTime; // @dynamic endTime;
@property(copy, nonatomic) NSString *memberAlias; // @dynamic memberAlias;
@property(copy, nonatomic) NSString *memberName; // @dynamic memberName;
@property(copy, nonatomic) NSString *memberSmallAvatarURL; // @dynamic memberSmallAvatarURL;
@property(nonatomic) long long memberUid; // @dynamic memberUid;
@property(nonatomic) long long silenceTime; // @dynamic silenceTime;

@end

