//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GroupbillUserVO : NSObject
{
    unsigned char _participateType;
    unsigned char _actionDoneFlag;
    long long _userId;
    long long _amount;
    NSString *_smallAvatarUrl;
    NSString *_nickName;
    long long _balance;
    NSString *_memberAlias;
}

@property(copy, nonatomic) NSString *memberAlias; // @synthesize memberAlias=_memberAlias;
@property(nonatomic) long long balance; // @synthesize balance=_balance;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *smallAvatarUrl; // @synthesize smallAvatarUrl=_smallAvatarUrl;
@property(nonatomic) unsigned char actionDoneFlag; // @synthesize actionDoneFlag=_actionDoneFlag;
@property(nonatomic) long long amount; // @synthesize amount=_amount;
@property(nonatomic) unsigned char participateType; // @synthesize participateType=_participateType;
@property(nonatomic) long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *displayName;

@end

