//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface GroupInterestTribe : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool groupAuthFlag; // @dynamic groupAuthFlag;
@property(nonatomic) long long groupId; // @dynamic groupId;
@property(retain, nonatomic) NSMutableArray *groupMemberArray; // @dynamic groupMemberArray;
@property(readonly, nonatomic) unsigned long long groupMemberArray_Count; // @dynamic groupMemberArray_Count;
@property(nonatomic) _Bool groupPrivilegeFlag; // @dynamic groupPrivilegeFlag;
@property(copy, nonatomic) NSString *groupTitle; // @dynamic groupTitle;
@property(copy, nonatomic) NSString *interestTribeIntroduction; // @dynamic interestTribeIntroduction;
@property(nonatomic) long long interestTribeTypeId; // @dynamic interestTribeTypeId;
@property(copy, nonatomic) NSString *interestTribeTypeName; // @dynamic interestTribeTypeName;
@property(copy, nonatomic) NSString *interestTribeTypeOriginalAvatarURL; // @dynamic interestTribeTypeOriginalAvatarURL;
@property(copy, nonatomic) NSString *interestTribeTypeSmallAvatarURL; // @dynamic interestTribeTypeSmallAvatarURL;
@property(copy, nonatomic) NSString *interestTribeTypeVipSmallAvatarURL; // @dynamic interestTribeTypeVipSmallAvatarURL;
@property(copy, nonatomic) NSString *originalAvatarURL; // @dynamic originalAvatarURL;
@property(copy, nonatomic) NSString *smallAvatarURL; // @dynamic smallAvatarURL;
@property(nonatomic) int totalMemberNumber; // @dynamic totalMemberNumber;

@end

