//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GroupbillParticipatorVO : NSObject
{
    unsigned char _participateType;
    long long _userId;
    long long _amount;
}

@property(nonatomic) long long amount; // @synthesize amount=_amount;
@property(nonatomic) unsigned char participateType; // @synthesize participateType=_participateType;
@property(nonatomic) long long userId; // @synthesize userId=_userId;

@end

