//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JRMFPacketModel : NSObject
{
    NSString *_packetId;
    NSString *_packetName;
    NSString *_packetSummary;
    unsigned long long _packetType;
    NSString *_numberOfMoney;
    long long _numberOfPackets;
}

@property(nonatomic) long long numberOfPackets; // @synthesize numberOfPackets=_numberOfPackets;
@property(copy, nonatomic) NSString *numberOfMoney; // @synthesize numberOfMoney=_numberOfMoney;
@property(nonatomic) unsigned long long packetType; // @synthesize packetType=_packetType;
@property(copy, nonatomic) NSString *packetSummary; // @synthesize packetSummary=_packetSummary;
@property(copy, nonatomic) NSString *packetName; // @synthesize packetName=_packetName;
@property(copy, nonatomic) NSString *packetId; // @synthesize packetId=_packetId;
- (void).cxx_destruct;

@end

