//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImage, UIImageView;

@interface JRMFEmptyView : UIView
{
    UIImage *_bg_img;
    CDUnknownBlockType _bgClick;
    UIImageView *_bg_img_view;
}

@property(retain, nonatomic) UIImageView *bg_img_view; // @synthesize bg_img_view=_bg_img_view;
@property(copy, nonatomic) CDUnknownBlockType bgClick; // @synthesize bgClick=_bgClick;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *bg_img; // @synthesize bg_img=_bg_img;
- (void)bg_img_viewClick;
- (void)addSubview;
- (void)customerSetting;
- (void)setUp;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

