//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JYPacketViewController.h"

#import "JrmfPayStatDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UITapLabelDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class JRMFPacketSendModel, JSRGroupPacketView, JSRPersonalPacketView, NSMutableArray, NSString, UILabel, UIMultiTextField, UITapLabel, UITextField, UIThemeButton, UIView, typeClipInfo;
@protocol JYEnvelopedDelegate;

@interface JrmfSendPacketViewController : JYPacketViewController <UITextFieldDelegate, UITextViewDelegate, UITapLabelDelegate, UIAlertViewDelegate, JrmfPayStatDelegate>
{
    UIView *topErrorView;
    UILabel *msgLabel;
    JSRGroupPacketView *_groupTopView;
    JSRPersonalPacketView *_personalView;
    UIView *S_M_View;
    UIView *G_C_View;
    UIView *G_M_View;
    UIView *P_BGView;
    UIView *C_BGView;
    UILabel *G_Label;
    UITapLabel *G_Tap_Label;
    _Bool isPin;
    UITextField *currentF;
    UIMultiTextField *s_inputDF;
    UILabel *s_showLabel;
    NSString *s_showString;
    UIThemeButton *s_button;
    typeClipInfo *selectedInfo;
    long long tmpSelectedIndex;
    NSString *payAmount;
    NSString *payPwdString;
    _Bool isNeedPwd;
    _Bool isHasPwd;
    _Bool isHasCard;
    _Bool isAuth;
    _Bool isComp;
    NSMutableArray *cardListArray;
    NSString *jdTradeId;
    NSString *envelopeId;
    NSString *redOrderId;
    NSString *alipayOrderStr;
    NSString *weixinTokenId;
    NSString *tmpString;
    NSString *tmpIuputString;
    long long tmpInputLocation;
    _Bool _isGroup;
    int _maxLimitMoney;
    int _maxCount;
    id <JYEnvelopedDelegate> _enveDelegate;
    NSString *_GroupNumber;
    NSString *_custuid;
    NSString *_receiveID;
    NSString *_userName;
    NSString *_userHeadLink;
    JRMFPacketSendModel *_sendPacketModel;
    NSString *_payParam;
    long long _packetsNum;
}

@property(nonatomic) long long packetsNum; // @synthesize packetsNum=_packetsNum;
@property(copy, nonatomic) NSString *payParam; // @synthesize payParam=_payParam;
@property(retain, nonatomic) JRMFPacketSendModel *sendPacketModel; // @synthesize sendPacketModel=_sendPacketModel;
@property(retain, nonatomic) NSString *userHeadLink; // @synthesize userHeadLink=_userHeadLink;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *receiveID; // @synthesize receiveID=_receiveID;
@property(retain, nonatomic) NSString *custuid; // @synthesize custuid=_custuid;
@property(nonatomic) int maxCount; // @synthesize maxCount=_maxCount;
@property(nonatomic) int maxLimitMoney; // @synthesize maxLimitMoney=_maxLimitMoney;
@property(retain, nonatomic) NSString *GroupNumber; // @synthesize GroupNumber=_GroupNumber;
@property(nonatomic) _Bool isGroup; // @synthesize isGroup=_isGroup;
@property(nonatomic) __weak id <JYEnvelopedDelegate> enveDelegate; // @synthesize enveDelegate=_enveDelegate;
- (void).cxx_destruct;
- (void)addSubview;
- (void)customerSetting;
- (void)dealloc;
- (void)questionBtn;
- (void)doActionClickBack;
- (void)doActionAlipayBack:(id)arg1;
- (void)doActionAlipayBackWith:(id)arg1;
- (void)doCheckInputMsgStatWithCount:(id)arg1 Amount:(id)arg2;
- (void)doChangeViewTextColorWithStat:(_Bool)arg1 WithGroupViewStatM:(_Bool)arg2;
- (void)doResetViewTextColor;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)doReturnValue;
- (void)tapLabel:(id)arg1 touchesWithTag:(long long)arg2;
- (void)doActionClickDown;
- (void)doActionClickSetTradersPwd;
- (void)doActionClickSubmit;
- (void)doJrmfPayStatWithAddNewCardNeedPassword:(_Bool)arg1 Password:(id)arg2 selectedClip:(id)arg3;
- (void)doJrmfPayStatWithBankCardInfo:(id)arg1 JDTradeId:(id)arg2 msgCode:(id)arg3;
- (void)doJrmfPayStatWithThirdStat:(unsigned long long)arg1 selectedClip:(id)arg2;
- (void)doJrmfPayStatWithChargePassword:(id)arg1 selectedClip:(id)arg2;
- (void)doCreateJYangEnvePayViewWithPayClioInfo:(id)arg1 isRepate:(_Bool)arg2;
- (void)doRepateCreatePayView;
- (void)postGetWxOrderMsgRequest;
- (void)doSubmissionResultsWithRepect:(_Bool)arg1 userName:(id)arg2;
- (void)doSaveRedpacketData;
- (void)postGetRedEnvelopePayRequestDataWithParamter:(id)arg1;
- (void)loadPayResult;
- (void)formatDataWithResponseObj:(id)arg1 inputMoney:(id)arg2;
- (void)postGetGroupPayTypeRequestData;
- (void)postGetPersonalPayTypeRequestData;
- (void)doMakeSubmitViewWithOrigin_Y:(double)arg1;
- (void)doSetEnvelopeLabelFrame;
- (void)doMakeRedEnvelopeModelWithOriY:(float)arg1;
- (id)doMakeGroupTopViewWithNumberOfGroup:(id)arg1;
- (id)doMakeSingleTopView;
- (void)doMakeTopErrorMsgView;
- (void)postGetRedPacketMsgRequest;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

