//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface JrmfWalletCell : UITableViewCell
{
    UIImageView *_iconImgView;
    UILabel *_walletItemLabel;
    UILabel *_walletSubLabel;
}

@property(retain, nonatomic) UILabel *walletSubLabel; // @synthesize walletSubLabel=_walletSubLabel;
@property(retain, nonatomic) UILabel *walletItemLabel; // @synthesize walletItemLabel=_walletItemLabel;
@property(retain, nonatomic) UIImageView *iconImgView; // @synthesize iconImgView=_iconImgView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)doBuildingJrmfWalletCell;
- (void)awakeFromNib;

@end

