//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UILabel, UITextField;

@interface JSRGroupPacketView : UIView
{
    UIView *_G_C_View;
    UIView *_P_BGView;
    UIView *_C_BGView;
    UITextField *_g_inputCF;
    UITextField *_s_inputMF;
    UILabel *_CLabel;
    UILabel *_ULabel;
    UILabel *_PC_Label;
    UILabel *_P_MLabel;
    UILabel *_ULabel02;
    UILabel *_C_MLabel;
    UILabel *_C_ULabel02;
    UIColor *_textColor;
}

+ (id)groupTopViewWithMembers:(id)arg1;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(nonatomic) __weak UILabel *C_ULabel02; // @synthesize C_ULabel02=_C_ULabel02;
@property(nonatomic) __weak UILabel *C_MLabel; // @synthesize C_MLabel=_C_MLabel;
@property(nonatomic) __weak UILabel *ULabel02; // @synthesize ULabel02=_ULabel02;
@property(nonatomic) __weak UILabel *P_MLabel; // @synthesize P_MLabel=_P_MLabel;
@property(nonatomic) __weak UILabel *PC_Label; // @synthesize PC_Label=_PC_Label;
@property(nonatomic) __weak UILabel *ULabel; // @synthesize ULabel=_ULabel;
@property(nonatomic) __weak UILabel *CLabel; // @synthesize CLabel=_CLabel;
@property(readonly, nonatomic) __weak UITextField *s_inputMF; // @synthesize s_inputMF=_s_inputMF;
@property(readonly, nonatomic) __weak UITextField *g_inputCF; // @synthesize g_inputCF=_g_inputCF;
@property(readonly, nonatomic) __weak UIView *C_BGView; // @synthesize C_BGView=_C_BGView;
@property(readonly, nonatomic) __weak UIView *P_BGView; // @synthesize P_BGView=_P_BGView;
@property(readonly, nonatomic) __weak UIView *G_C_View; // @synthesize G_C_View=_G_C_View;
- (void).cxx_destruct;
- (void)resetG_C_ViewTextColor;
- (void)resetC_BGViewTextColor;
- (void)resetP_BGViewTextColor;
- (void)resetTextColor:(id)arg1 cashView:(_Bool)arg2 isPin:(_Bool)arg3;
- (void)resetTextColor:(id)arg1;
- (void)doMakeGroupTopViewWithNumberOfGroup:(id)arg1;

@end

