//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"

@class NSString;

@interface JYangLib : NSObject <NSURLSessionDelegate>
{
}

+ (void)mf_setUserIcon:(id)arg1 className:(id)arg2 with:(id)arg3 webImage:(id)arg4 defaultImage:(id)arg5 block:(CDUnknownBlockType)arg6;
+ (void)mf_setUserIcon:(id)arg1 className:(id)arg2 with:(id)arg3 webImage:(id)arg4 defaultImage:(id)arg5;
+ (id)encrypt:(id)arg1 withKey:(id)arg2;
+ (void)submitErrMsg:(id)arg1 userId:(id)arg2 msg:(id)arg3 block:(CDUnknownBlockType)arg4;
+ (void)mf_collectErrorMsg:(id)arg1 userId:(id)arg2;
+ (id)GetJYangToolLibMsg;
+ (id)mf_post:(id)arg1 param:(id)arg2 block:(CDUnknownBlockType)arg3;
+ (id)postGetRequestWithLink:(id)arg1 parameter:(id)arg2 Success:(CDUnknownBlockType)arg3 Fail:(CDUnknownBlockType)arg4;
+ (id)httpPostGetRequestWithLink:(id)arg1 parameter:(id)arg2 Success:(CDUnknownBlockType)arg3 Fail:(CDUnknownBlockType)arg4;
+ (void)mf_hideHUDInView:(id)arg1;
+ (void)mf_showProgressHUDWith:(id)arg1 inView:(id)arg2;
+ (void)JYangLibShowWait:(id)arg1 InViewController:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)JYangLibShowWait:(id)arg1 InViewController:(id)arg2;
+ (void)JYangLibHideWaitWithViewController:(id)arg1;
+ (void)JYangLibShowWaitInViewController:(id)arg1 hint:(id)arg2;
+ (void)JYangLibDownloadImageWithUrl:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)JYangLibsetImageWithImageView:(id)arg1 URL:(id)arg2 placeholderImage:(id)arg3;
+ (id)shareHelper;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

