//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MGCameraImage : NSObject
{
}

+ (id)convertBitmapRGBA8ToUIImage:(char *)arg1 imageWidth:(int)arg2 imageHeight:(int)arg3;
+ (void)imageBufferBGRA2RGBAWithsrc:(const char *)arg1 dst:(char *)arg2 imageWidth:(int)arg3 imageHeight:(int)arg4;

@end

