//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MGFaceIDLiveDetectConfigItem, MGFaceIDLiveDetectCustomConfigItem, MGFaceIDLiveDetectStatisticsManager, NSDictionary, UIImage;

@interface MGFaceIDLiveDetectViewController : UIViewController
{
    MGFaceIDLiveDetectConfigItem *_configItem;
    MGFaceIDLiveDetectCustomConfigItem *_configUIItem;
    unsigned long long _verticalType;
    UIImage *_logoImage;
    CDUnknownBlockType _resultBlock;
    MGFaceIDLiveDetectStatisticsManager *_statisticsManager;
    NSDictionary *_extraObj;
}

@property(retain, nonatomic) NSDictionary *extraObj; // @synthesize extraObj=_extraObj;
@property(retain, nonatomic) MGFaceIDLiveDetectStatisticsManager *statisticsManager; // @synthesize statisticsManager=_statisticsManager;
@property(copy, nonatomic) CDUnknownBlockType resultBlock; // @synthesize resultBlock=_resultBlock;
@property(retain, nonatomic) UIImage *logoImage; // @synthesize logoImage=_logoImage;
@property(nonatomic) unsigned long long verticalType; // @synthesize verticalType=_verticalType;
@property(retain, nonatomic) MGFaceIDLiveDetectCustomConfigItem *configUIItem; // @synthesize configUIItem=_configUIItem;
@property(retain, nonatomic) MGFaceIDLiveDetectConfigItem *configItem; // @synthesize configItem=_configItem;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

