//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MGFaceIDLiveDetectViewController.h"

#import "MGCameraDelegate-Protocol.h"
#import "MGFaceIDLiveDetectAlertDelegate-Protocol.h"
#import "MGFaceIDSilentLiveManagerDelegate-Protocol.h"

@class MGFaceIDCameraManager, MGFaceIDDetectSilentLiveCameraView, MGFaceIDSilentLiveManager, NSString;

@interface MGFaceIDSilentLiveViewController : MGFaceIDLiveDetectViewController <MGCameraDelegate, MGFaceIDSilentLiveManagerDelegate, MGFaceIDLiveDetectAlertDelegate>
{
    int _stillFpsCout;
    MGFaceIDCameraManager *_cameraManager;
    MGFaceIDSilentLiveManager *_silentLiveManager;
    MGFaceIDDetectSilentLiveCameraView *_cameraView;
}

@property(retain, nonatomic) MGFaceIDDetectSilentLiveCameraView *cameraView; // @synthesize cameraView=_cameraView;
@property(retain, nonatomic) MGFaceIDSilentLiveManager *silentLiveManager; // @synthesize silentLiveManager=_silentLiveManager;
@property(retain, nonatomic) MGFaceIDCameraManager *cameraManager; // @synthesize cameraManager=_cameraManager;
@property(nonatomic) int stillFpsCout; // @synthesize stillFpsCout=_stillFpsCout;
- (void).cxx_destruct;
- (void)userClickButtonWithIndex:(unsigned long long)arg1;
- (void)closeFaceIDDetect:(id)arg1;
- (void)faceIDDetectSilentLiveManagerStopVideo;
- (void)faceIDDetectSilentLiveManagerQualityStepError:(int)arg1;
- (void)faceIDDetectSilentLiveManagerFMPStep;
- (void)faceIDDetectSilentLiveManagerQualityStep;
- (void)faceIDDetectSilentLiveManagerDetectProgress:(double)arg1;
- (void)faceIDDetectSilentLiveManagerCancelDetectData:(id)arg1;
- (void)faceIDDetectSilentLiveFinish:(_Bool)arg1 detectData:(id)arg2;
- (void)faceIDDetectSilentLiveManagerStopRecording;
- (void)faceIDDetectSilentLiveManagerResetRecording;
- (void)initCameraManager;
- (void)resetSilentLiveDetect;
- (void)initSilentLiveDetect;
- (void)mgCaptureFailedVideoRecord;
- (void)mgCaptureFinishVideoRecord:(id)arg1;
- (void)mgCaptureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)stopCameraManager;
- (void)startCameraManager;
- (void)goBackGround;
- (void)buildView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

