//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MGFaceIDActionLiveItem : NSObject
{
    int _currentStep;
    int _qualityError;
    int _failedType;
    int _actionType;
    int _actionIndex;
    float _detectTime;
    int _actionCount;
    int _actionTimeout;
    struct MegFaceIDImage _bestImage;
}

@property(nonatomic) int actionTimeout; // @synthesize actionTimeout=_actionTimeout;
@property(nonatomic) int actionCount; // @synthesize actionCount=_actionCount;
@property(nonatomic) float detectTime; // @synthesize detectTime=_detectTime;
@property(nonatomic) int actionIndex; // @synthesize actionIndex=_actionIndex;
@property(nonatomic) struct MegFaceIDImage bestImage; // @synthesize bestImage=_bestImage;
@property(nonatomic) int actionType; // @synthesize actionType=_actionType;
@property(nonatomic) int failedType; // @synthesize failedType=_failedType;
@property(nonatomic) int qualityError; // @synthesize qualityError=_qualityError;
@property(nonatomic) int currentStep; // @synthesize currentStep=_currentStep;

@end

