//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData;

@protocol MGFaceIDSilentLiveManagerDelegate <NSObject>

@optional
- (void)faceIDDetectSilentLiveManagerStopVideo;
- (void)faceIDDetectSilentLiveManagerStopRecording;
- (void)faceIDDetectSilentLiveManagerResetRecording;
- (void)faceIDDetectSilentLiveManagerQualityStepError:(int)arg1;
- (void)faceIDDetectSilentLiveManagerFMPStep;
- (void)faceIDDetectSilentLiveManagerQualityStep;
- (void)faceIDDetectSilentLiveManagerCancelDetectData:(NSData *)arg1;
- (void)faceIDDetectSilentLiveManagerDetectProgress:(double)arg1;
- (void)faceIDDetectSilentLiveFinish:(_Bool)arg1 detectData:(NSData *)arg2;
@end

