//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AVCaptureVideoPreviewLayer, MGFaceIDDetectActionLiveRingLayer, MGFaceIDLiveDetectCustomConfigItem, UIButton, UIImageView, UITextView;

@interface MGFaceIDDetectActionLiveCameraView : UIView
{
    _Bool _stopAnimaiton;
    AVCaptureVideoPreviewLayer *_previewLayer;
    MGFaceIDDetectActionLiveRingLayer *_ringLayer;
    UIButton *_closeButton;
    UIView *_coverView;
    UIView *_actionView;
    UIImageView *_animationImageV;
    UITextView *_messageLabel;
    UIImageView *_activeityIndeView;
    MGFaceIDLiveDetectCustomConfigItem *_customConfigItem;
}

@property(retain, nonatomic) MGFaceIDLiveDetectCustomConfigItem *customConfigItem; // @synthesize customConfigItem=_customConfigItem;
@property(retain, nonatomic) UIImageView *activeityIndeView; // @synthesize activeityIndeView=_activeityIndeView;
@property(retain, nonatomic) UITextView *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIImageView *animationImageV; // @synthesize animationImageV=_animationImageV;
@property(retain, nonatomic) UIView *actionView; // @synthesize actionView=_actionView;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) MGFaceIDDetectActionLiveRingLayer *ringLayer; // @synthesize ringLayer=_ringLayer;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(readonly, nonatomic) _Bool stopAnimaiton; // @synthesize stopAnimaiton=_stopAnimaiton;
- (void).cxx_destruct;
- (void)actionViewMakeActionWithCurrentState:(int)arg1;
- (void)setCurrentActionLiveDetectState:(unsigned long long)arg1;
- (void)showActionFaceIDDetectStage:(long long)arg1 progress:(double)arg2;
- (void)progressHUD:(_Bool)arg1 animation:(_Bool)arg2;
- (void)animationPause;
- (void)isLookMirror;
- (void)showFaceIDDetectLiveDetectCount:(long long)arg1;
- (void)showFaceIDDetectLiveMessage:(id)arg1;
- (void)loadDefaultView:(id)arg1;
- (void)againDrawProgressV;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 uiConfig:(id)arg2 logoImage:(id)arg3;

@end

