//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (appSuperProtecter)
+ (void)rebuildAllDangerMethods;
+ (_Bool)swizzleClassMethod:(SEL)arg1 withClassMethod:(SEL)arg2;
+ (_Bool)swizzleMethod:(SEL)arg1 withMethod:(SEL)arg2;
+ (_Bool)swizzleMethod:(SEL)arg1 origClass:(id)arg2 withMethod:(SEL)arg3 targetClass:(id)arg4;
- (void)printBadParamLog:(SEL)arg1 params:(id)arg2;
- (void)errorHandlingWithBadParam:(SEL)arg1 params:(id)arg2;
- (void)multipleParamFunctionMirror5:(id)arg1 param2:(id)arg2 param3:(id)arg3 param4:(id)arg4;
- (void)multipleParamFunctionMirror4:(id)arg1 param2:(id)arg2 param3:(id)arg3;
- (void)multipleParamFunctionMirror3:(id)arg1 param2:(id)arg2;
- (void)multipleParamFunctionMirror2:(id)arg1;
- (void)multipleParamFunctionMirror1;
- (id)methodSignatureForSelectorMirror:(SEL)arg1;
- (void)forwardInvocationMirror:(id)arg1;
- (void)printUnrecognizedSelectorLog:(SEL)arg1;
- (void)UIAlert:(id)arg1;
- (void)errorHandlingWithUnrecognizedSelector:(SEL)arg1;
@end

