//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (MGFaceIDLiveAttributedString)
- (double)getSpaceLabelHeightwithSpeace:(double)arg1 withLabel:(id)arg2 andAlignment:(long long)arg3 andWidth:(double)arg4;
- (id)stringWithParagraphlineSpeace:(double)arg1 andAlignment:(long long)arg2 andLabel:(id)arg3;
@end

