//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (AES128)
- (id)hexData;
- (id)regex:(id)arg1;
- (id)AES_Decrypt:(id)arg1 withIV:(id)arg2;
- (id)AES_Encrypt:(id)arg1 withIV:(id)arg2;
- (id)aes256_decrypt:(id)arg1 withIV:(id)arg2;
- (id)aes256_encrypt:(id)arg1 withIV:(id)arg2;
- (id)aes256_decrypt:(id)arg1;
- (id)aes256_encrypt:(id)arg1;
- (id)sha256;
- (id)pbkdf2WithSalt:(id)arg1;
- (id)md5;
- (id)aes128_decrypt:(id)arg1;
- (id)aes128_encrypt:(id)arg1;
@end

