//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class OrderVO;

@protocol OrderListDelegate <NSObject>
- (void)inviteFriendForGroupBuy:(OrderVO *)arg1;
- (void)contactGroup:(OrderVO *)arg1;
- (void)showExpressTrances:(OrderVO *)arg1;
- (void)contact:(OrderVO *)arg1;
- (void)payGoods:(OrderVO *)arg1;
- (void)deleteOrder:(OrderVO *)arg1;
@end

