//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt64Array, NSString;

@interface SendGroupChatPokeReq : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long groupId; // @dynamic groupId;
@property(retain, nonatomic) GPBInt64Array *groupMemberUidArray; // @dynamic groupMemberUidArray;
@property(readonly, nonatomic) unsigned long long groupMemberUidArray_Count; // @dynamic groupMemberUidArray_Count;
@property(nonatomic) long long localId; // @dynamic localId;
@property(copy, nonatomic) NSString *pokeContent; // @dynamic pokeContent;
@property(nonatomic) _Bool pokeSomeGroupMemberFlag; // @dynamic pokeSomeGroupMemberFlag;

@end

