//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SendRobotKeywordReq : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long groupId; // @dynamic groupId;
@property(copy, nonatomic) NSString *keywordName; // @dynamic keywordName;
@property(nonatomic) long long localId; // @dynamic localId;
@property(nonatomic) long long robotId; // @dynamic robotId;

@end

