//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView;

@interface SGAccountSettingCell : UITableViewCell
{
    UIImageView *_icon;
    UILabel *_titleLab;
    UIView *_redView;
    UIImageView *_balanceRecommendView;
}

@property(retain, nonatomic) UIImageView *balanceRecommendView; // @synthesize balanceRecommendView=_balanceRecommendView;
@property(retain, nonatomic) UIView *redView; // @synthesize redView=_redView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;
- (void)setShowBalanceRecommendIcon:(_Bool)arg1 imageName:(id)arg2;
- (void)setRedOrigin:(_Bool)arg1;
- (void)setImage:(id)arg1 withTitle:(id)arg2;

@end

