//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, NSTimer, UIButton, UILabel, UITextField;

@interface SGAccountCodeLoginController : SGViewController <UITextFieldDelegate>
{
    UITextField *_codeTF;
    UILabel *_errorLab;
    UIButton *_getCodeBtn;
    UILabel *_checkCodeLabel;
    NSTimer *_timer;
    long long _remainTime;
}

@property(nonatomic) long long remainTime; // @synthesize remainTime=_remainTime;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILabel *checkCodeLabel; // @synthesize checkCodeLabel=_checkCodeLabel;
@property(retain, nonatomic) UIButton *getCodeBtn; // @synthesize getCodeBtn=_getCodeBtn;
@property(retain, nonatomic) UILabel *errorLab; // @synthesize errorLab=_errorLab;
@property(retain, nonatomic) UITextField *codeTF; // @synthesize codeTF=_codeTF;
- (void).cxx_destruct;
- (void)viewWillAppear:(_Bool)arg1;
- (void)inAccountAction;
- (void)signUpAction;
- (void)enableCHeckdumButton:(id)arg1;
- (void)getSmsCode;
- (void)LoginAction;
- (void)nextAction;
- (void)textFieldDidChange:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)myEndEditing;
- (void)initView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

