//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGBaseSettingController.h"

#import "UIAlertViewDelegate-Protocol.h"

@class NSString, NSTimer, SGAccountProfileController, SGAccountSettingCellModel, SGGetUserVipInfoResp, SGHeadImageCellModel, SGSectionModel, UIAlertView;

@interface SGAccountSettingController : SGBaseSettingController <UIAlertViewDelegate>
{
    _Bool _setPWState;
    SGGetUserVipInfoResp *_vipInfoResp;
    UIAlertView *_alertView;
    SGHeadImageCellModel *_headimageCell;
    SGAccountSettingCellModel *_interestCell;
    SGSectionModel *_balanceSection;
    SGAccountSettingCellModel *_balanceCell;
    SGAccountSettingCellModel *_TLbalanceCell;
    SGAccountSettingCellModel *_redPacketCell;
    SGAccountSettingCellModel *_popularizeCell;
    SGAccountSettingCellModel *_myGiftCell;
    SGSectionModel *_gameSection;
    SGAccountSettingCellModel *_settingCell;
    SGAccountSettingCellModel *_jrmfPacketCell;
    SGAccountSettingCellModel *_collectCell;
    SGSectionModel *_interestSection;
    SGAccountSettingCellModel *_pointCell;
    SGAccountSettingCellModel *_goodsCell;
    SGSectionModel *_qrcodeSection;
    NSTimer *_loadVIPInfoTimer;
    SGAccountProfileController *_profileVC;
}

@property(nonatomic) _Bool setPWState; // @synthesize setPWState=_setPWState;
@property(nonatomic) __weak SGAccountProfileController *profileVC; // @synthesize profileVC=_profileVC;
@property(retain, nonatomic) NSTimer *loadVIPInfoTimer; // @synthesize loadVIPInfoTimer=_loadVIPInfoTimer;
@property(retain, nonatomic) SGSectionModel *qrcodeSection; // @synthesize qrcodeSection=_qrcodeSection;
@property(retain, nonatomic) SGAccountSettingCellModel *goodsCell; // @synthesize goodsCell=_goodsCell;
@property(retain, nonatomic) SGAccountSettingCellModel *pointCell; // @synthesize pointCell=_pointCell;
@property(retain, nonatomic) SGSectionModel *interestSection; // @synthesize interestSection=_interestSection;
@property(retain, nonatomic) SGAccountSettingCellModel *collectCell; // @synthesize collectCell=_collectCell;
@property(retain, nonatomic) SGAccountSettingCellModel *jrmfPacketCell; // @synthesize jrmfPacketCell=_jrmfPacketCell;
@property(retain, nonatomic) SGAccountSettingCellModel *settingCell; // @synthesize settingCell=_settingCell;
@property(retain, nonatomic) SGSectionModel *gameSection; // @synthesize gameSection=_gameSection;
@property(retain, nonatomic) SGAccountSettingCellModel *myGiftCell; // @synthesize myGiftCell=_myGiftCell;
@property(retain, nonatomic) SGAccountSettingCellModel *popularizeCell; // @synthesize popularizeCell=_popularizeCell;
@property(retain, nonatomic) SGAccountSettingCellModel *redPacketCell; // @synthesize redPacketCell=_redPacketCell;
@property(retain, nonatomic) SGAccountSettingCellModel *TLbalanceCell; // @synthesize TLbalanceCell=_TLbalanceCell;
@property(retain, nonatomic) SGAccountSettingCellModel *balanceCell; // @synthesize balanceCell=_balanceCell;
@property(retain, nonatomic) SGSectionModel *balanceSection; // @synthesize balanceSection=_balanceSection;
@property(retain, nonatomic) SGAccountSettingCellModel *interestCell; // @synthesize interestCell=_interestCell;
@property(retain, nonatomic) SGHeadImageCellModel *headimageCell; // @synthesize headimageCell=_headimageCell;
@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) SGGetUserVipInfoResp *vipInfoResp; // @synthesize vipInfoResp=_vipInfoResp;
- (void).cxx_destruct;
- (void)dealloc;
- (void)createPointCell;
- (void)tableViewCellSelectMyGiftCell;
- (void)tableViewCellSelectPopuarCell;
- (void)tableViewCellSelectHelpCell;
- (void)tableViewCellSelectSettingCell;
- (void)tableViewCellSelectCollectCell;
- (void)tableViewCellSelectGoodsceCell;
- (void)tableViewCellSelectAliRedPacketCell;
- (void)tableViewCellSelectJrmfCell;
- (void)tableViewCellSelectTLBanlanceCell;
- (void)tableViewCellSelectOldBalanceCell;
- (void)tableViewCellSelectXianLiaoNet;
- (void)tableViewCellSelectSqan;
- (void)tableViewCellSelectQRCode;
- (void)tableViewCellSelectPoint;
- (void)tableViewCellSelectInterest;
- (void)tableViewCellSelectHeadImageCell;
- (void)checkBindCard:(CDUnknownBlockType)arg1;
- (void)authForResp:(id)arg1 nextBlock:(CDUnknownBlockType)arg2;
- (void)checkAlipayAuthState:(CDUnknownBlockType)arg1;
- (void)enterAlipayRedPacket;
- (void)checkIsRealNameAuht:(CDUnknownBlockType)arg1;
- (void)sgGetFindMeByPhoneNumer;
- (void)loadsgGetPasswordSetFlag;
- (void)resefrshSettingCellWithState:(_Bool)arg1;
- (void)setVipInfo:(id)arg1;
- (void)loadVIPInof;
- (void)reloadSystemConfig;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

