//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSArray, NSString;

@interface SGAddSelfDefinedGroupGoodsReq : SGHTTPSReqModel
{
    long long _groupId;
    NSString *_goodsName;
    NSString *_goodsSmallPhotoUrl;
    NSString *_goodsBigPhotoUrl;
    NSArray *_descPhotoUrlList;
    NSString *_goodsDescription;
    long long _salePrice;
    long long _totalNumber;
    long long _goldenbeanNum;
}

@property(nonatomic) long long goldenbeanNum; // @synthesize goldenbeanNum=_goldenbeanNum;
@property(nonatomic) long long totalNumber; // @synthesize totalNumber=_totalNumber;
@property(nonatomic) long long salePrice; // @synthesize salePrice=_salePrice;
@property(copy, nonatomic) NSString *goodsDescription; // @synthesize goodsDescription=_goodsDescription;
@property(retain, nonatomic) NSArray *descPhotoUrlList; // @synthesize descPhotoUrlList=_descPhotoUrlList;
@property(copy, nonatomic) NSString *goodsBigPhotoUrl; // @synthesize goodsBigPhotoUrl=_goodsBigPhotoUrl;
@property(copy, nonatomic) NSString *goodsSmallPhotoUrl; // @synthesize goodsSmallPhotoUrl=_goodsSmallPhotoUrl;
@property(copy, nonatomic) NSString *goodsName; // @synthesize goodsName=_goodsName;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;
- (int)constructor;

@end

