//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, OSSPutObjectRequest, SGAddMoreGoodIconView, SGGoodsListDataVO, UIButton, UIImageView, UILabel, UIScrollView, UITextField, UITextView, UIView;

@interface SGAddThirdGoodViewController : SGViewController <UITextViewDelegate, UITextFieldDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate>
{
    _Bool _isHaveEdite;
    long long _groupID;
    CDUnknownBlockType _addSelfBlock;
    SGGoodsListDataVO *_listModel;
    SGViewController *_navgationLastViewController;
    UIImageView *_coverIconView;
    UIView *_coverProgressView;
    UILabel *_coverProgressLab;
    NSString *_smallCoverKey;
    NSString *_goodsSmallPhotoUrl;
    OSSPutObjectRequest *_coverRequest;
    UIImageView *_deleteCoverView;
    SGAddMoreGoodIconView *_addIconView;
    UIScrollView *_scrollerView;
    UITextView *_goodsNameTextField;
    UITextView *_reamrkTextView;
    UILabel *_remarkPlacholdLab;
    UILabel *_namePlacholdLab;
    UITextField *_rmbTextField;
    UIButton *_addGoodButton;
    UITextField *_goldTextField;
    UITextField *_inventoryTextField;
}

@property(nonatomic) _Bool isHaveEdite; // @synthesize isHaveEdite=_isHaveEdite;
@property(retain, nonatomic) UITextField *inventoryTextField; // @synthesize inventoryTextField=_inventoryTextField;
@property(retain, nonatomic) UITextField *goldTextField; // @synthesize goldTextField=_goldTextField;
@property(retain, nonatomic) UIButton *addGoodButton; // @synthesize addGoodButton=_addGoodButton;
@property(retain, nonatomic) UITextField *rmbTextField; // @synthesize rmbTextField=_rmbTextField;
@property(retain, nonatomic) UILabel *namePlacholdLab; // @synthesize namePlacholdLab=_namePlacholdLab;
@property(retain, nonatomic) UILabel *remarkPlacholdLab; // @synthesize remarkPlacholdLab=_remarkPlacholdLab;
@property(retain, nonatomic) UITextView *reamrkTextView; // @synthesize reamrkTextView=_reamrkTextView;
@property(retain, nonatomic) UITextView *goodsNameTextField; // @synthesize goodsNameTextField=_goodsNameTextField;
@property(retain, nonatomic) UIScrollView *scrollerView; // @synthesize scrollerView=_scrollerView;
@property(retain, nonatomic) SGAddMoreGoodIconView *addIconView; // @synthesize addIconView=_addIconView;
@property(retain, nonatomic) UIImageView *deleteCoverView; // @synthesize deleteCoverView=_deleteCoverView;
@property(retain, nonatomic) OSSPutObjectRequest *coverRequest; // @synthesize coverRequest=_coverRequest;
@property(copy, nonatomic) NSString *goodsSmallPhotoUrl; // @synthesize goodsSmallPhotoUrl=_goodsSmallPhotoUrl;
@property(copy, nonatomic) NSString *smallCoverKey; // @synthesize smallCoverKey=_smallCoverKey;
@property(retain, nonatomic) UILabel *coverProgressLab; // @synthesize coverProgressLab=_coverProgressLab;
@property(retain, nonatomic) UIView *coverProgressView; // @synthesize coverProgressView=_coverProgressView;
@property(retain, nonatomic) UIImageView *coverIconView; // @synthesize coverIconView=_coverIconView;
@property(nonatomic) __weak SGViewController *navgationLastViewController; // @synthesize navgationLastViewController=_navgationLastViewController;
@property(retain, nonatomic) SGGoodsListDataVO *listModel; // @synthesize listModel=_listModel;
@property(copy, nonatomic) CDUnknownBlockType addSelfBlock; // @synthesize addSelfBlock=_addSelfBlock;
@property(nonatomic) long long groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (_Bool)addThirdGoodIsEmpty:(id)arg1;
- (void)addThirdGoodClickAdd;
- (void)dealloc;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)textFieldTextChange:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)deleteCoverImage;
- (void)resendCover;
- (void)uploadCoverProgress:(id)arg1;
- (void)chooseCoverImage;
- (void)askHelp;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)addThirdGoodEndEdit;
- (void)creatChildView;
- (void)viewDidLoad;
- (void)backAction;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

