//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, SGGetRedPacketMoneyLimitResp;

@interface SGAlipayManger : NSObject
{
    _Bool _isOpenAlipay;
    _Bool _isAlipayRedpacketMessage;
    CDUnknownBlockType _authBindBlock;
    SGGetRedPacketMoneyLimitResp *_redPacketLimitResp;
    NSMutableDictionary *_showAlipayPacketDictM;
    NSMutableDictionary *_getAliPacketBeforeOpenDictM;
    NSMutableDictionary *_aliPayAccountDictM;
    CDUnknownBlockType _authResultBlock;
}

+ (id)shareInstance;
@property(copy, nonatomic) CDUnknownBlockType authResultBlock; // @synthesize authResultBlock=_authResultBlock;
@property(retain, nonatomic) NSMutableDictionary *aliPayAccountDictM; // @synthesize aliPayAccountDictM=_aliPayAccountDictM;
@property(retain, nonatomic) NSMutableDictionary *getAliPacketBeforeOpenDictM; // @synthesize getAliPacketBeforeOpenDictM=_getAliPacketBeforeOpenDictM;
@property(retain, nonatomic) NSMutableDictionary *showAlipayPacketDictM; // @synthesize showAlipayPacketDictM=_showAlipayPacketDictM;
@property(retain, nonatomic) SGGetRedPacketMoneyLimitResp *redPacketLimitResp; // @synthesize redPacketLimitResp=_redPacketLimitResp;
@property(nonatomic) _Bool isAlipayRedpacketMessage; // @synthesize isAlipayRedpacketMessage=_isAlipayRedpacketMessage;
@property(nonatomic) _Bool isOpenAlipay; // @synthesize isOpenAlipay=_isOpenAlipay;
@property(copy, nonatomic) CDUnknownBlockType authBindBlock; // @synthesize authBindBlock=_authBindBlock;
- (void).cxx_destruct;
- (id)getAlipayAccount:(id)arg1;
- (void)cachAliPayAccount:(id)arg1 accout:(id)arg2;
- (id)getAliPayRedpacketData:(long long)arg1;
- (id)getAliPayPacketInfoBeforeOpenData:(long long)arg1;
- (void)cachGetAliPayPacketInfoBeforeOpenResp:(long long)arg1 packetResp:(id)arg2;
- (void)cachAliPayRedpacket:(long long)arg1 packetResp:(id)arg2;
- (id)getAlipAccount;
- (void)findAliPayAccountWithAlipay_user_id:(id)arg1 accountComplention:(CDUnknownBlockType)arg2;
- (void)cleanAlipayAuth;
- (void)getWithdrawMoneyLimit:(CDUnknownBlockType)arg1;
- (id)getRedPacketMoneyLimitResp;
- (void)loadRedpacketMoneyLimit:(_Bool)arg1;
- (void)cleanCachAlipayConfig;
- (void)jumpAlipay;
- (_Bool)canOpenAlipay;
- (void)sendGroupPrivilegeRandomPacketFromAlipayRevGroupId:(long long)arg1 count:(long long)arg2 packetId:(long long)arg3 appointedIdList:(id)arg4 packetNum:(long long)arg5 totalPacketAmount:(long long)arg6 wishContent:(id)arg7 out_order_no:(id)arg8 out_request_no:(id)arg9:(CDUnknownBlockType)arg10;
- (void)sendGroupPrivilegePacketFromAlipayRevGroupId:(long long)arg1 count:(long long)arg2 packetId:(long long)arg3 appointedIdList:(id)arg4 singlePacketAmount:(long long)arg5 packetNum:(long long)arg6 wishContent:(id)arg7 out_order_no:(id)arg8 out_request_no:(id)arg9:(CDUnknownBlockType)arg10;
- (void)sendGroupRandomPacketFromAlipayRevGroupId:(long long)arg1 count:(long long)arg2 packetId:(long long)arg3 totalPacketAmount:(long long)arg4 packetNum:(long long)arg5 wishContent:(id)arg6 out_order_no:(id)arg7 out_request_no:(id)arg8:(CDUnknownBlockType)arg9;
- (void)sendGroupPacketFromAlipayRevGroupId:(long long)arg1 count:(long long)arg2 packetId:(long long)arg3 singlePacketAmount:(long long)arg4 packetNum:(long long)arg5 wishContent:(id)arg6 out_order_no:(id)arg7 out_request_no:(id)arg8:(CDUnknownBlockType)arg9;
- (void)sendUserPacketFromAlipay:(long long)arg1 count:(long long)arg2 packetId:(long long)arg3 packetAmount:(long long)arg4 wishContent:(id)arg5 out_order_no:(id)arg6 out_request_no:(id)arg7:(CDUnknownBlockType)arg8;
- (void)requestOrderInfo:(long long)arg1 aliPayOrderTitle:(id)arg2 aliPayOrderJson:(id)arg3 aliPayAmout:(long long)arg4:(CDUnknownBlockType)arg5;
- (void)blindAlipay:(id)arg1 blindAlipayCode:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)setAliAuthResult:(id)arg1;
- (void)handleAuthResult:(id)arg1;
- (void)startAlipayAuth:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)blindAliPayAccount:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestToAlipayAuth:(CDUnknownBlockType)arg1;
- (id)requestIsAlipayAuthSet:(CDUnknownBlockType)arg1;

@end

