//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "GLImagePreviewDelegate-Protocol.h"

@class NSArray, NSLayoutConstraint, NSMutableArray, NSString, SGGameObject, UIButton, UIImageView, UILabel, UIScrollView, UIView;

@interface SGApplyDetailController : SGViewController <GLImagePreviewDelegate>
{
    SGGameObject *_gameVO;
    NSLayoutConstraint *_descriptionHeight;
    UIButton *_descriptonButton;
    NSLayoutConstraint *_descriptionButtonHeight;
    UILabel *_descriptionLable;
    UILabel *_desctipitonTitle;
    UIView *_descriptionView;
    UIButton *_applyButton;
    UIView *_applyView;
    UIScrollView *_gameImageScrollview;
    NSLayoutConstraint *_scrollViewHeight;
    UIImageView *_gameImageView;
    NSMutableArray *_subGameImageViews;
    NSArray *_scrollImageNames;
    UIButton *_currentLongPressImageView;
    UILabel *_thirdTitleLabel;
    UILabel *_thirdTitleOne;
    UILabel *_thirdSubTitleOne;
    UILabel *_thirdTitleTwo;
    UILabel *_thirdSubTitleTwo;
    UILabel *_thirdTitleThree;
    UILabel *_thirdSubTitleThree;
}

@property(nonatomic) __weak UILabel *thirdSubTitleThree; // @synthesize thirdSubTitleThree=_thirdSubTitleThree;
@property(nonatomic) __weak UILabel *thirdTitleThree; // @synthesize thirdTitleThree=_thirdTitleThree;
@property(nonatomic) __weak UILabel *thirdSubTitleTwo; // @synthesize thirdSubTitleTwo=_thirdSubTitleTwo;
@property(nonatomic) __weak UILabel *thirdTitleTwo; // @synthesize thirdTitleTwo=_thirdTitleTwo;
@property(nonatomic) __weak UILabel *thirdSubTitleOne; // @synthesize thirdSubTitleOne=_thirdSubTitleOne;
@property(nonatomic) __weak UILabel *thirdTitleOne; // @synthesize thirdTitleOne=_thirdTitleOne;
@property(nonatomic) __weak UILabel *thirdTitleLabel; // @synthesize thirdTitleLabel=_thirdTitleLabel;
@property(retain, nonatomic) UIButton *currentLongPressImageView; // @synthesize currentLongPressImageView=_currentLongPressImageView;
@property(retain, nonatomic) NSArray *scrollImageNames; // @synthesize scrollImageNames=_scrollImageNames;
@property(retain, nonatomic) NSMutableArray *subGameImageViews; // @synthesize subGameImageViews=_subGameImageViews;
@property(nonatomic) __weak UIImageView *gameImageView; // @synthesize gameImageView=_gameImageView;
@property(nonatomic) __weak NSLayoutConstraint *scrollViewHeight; // @synthesize scrollViewHeight=_scrollViewHeight;
@property(nonatomic) __weak UIScrollView *gameImageScrollview; // @synthesize gameImageScrollview=_gameImageScrollview;
@property(nonatomic) __weak UIView *applyView; // @synthesize applyView=_applyView;
@property(nonatomic) __weak UIButton *applyButton; // @synthesize applyButton=_applyButton;
@property(nonatomic) __weak UIView *descriptionView; // @synthesize descriptionView=_descriptionView;
@property(nonatomic) __weak UILabel *desctipitonTitle; // @synthesize desctipitonTitle=_desctipitonTitle;
@property(nonatomic) __weak UILabel *descriptionLable; // @synthesize descriptionLable=_descriptionLable;
@property(nonatomic) __weak NSLayoutConstraint *descriptionButtonHeight; // @synthesize descriptionButtonHeight=_descriptionButtonHeight;
@property(nonatomic) __weak UIButton *descriptonButton; // @synthesize descriptonButton=_descriptonButton;
@property(nonatomic) __weak NSLayoutConstraint *descriptionHeight; // @synthesize descriptionHeight=_descriptionHeight;
@property(retain, nonatomic) SGGameObject *gameVO; // @synthesize gameVO=_gameVO;
- (void).cxx_destruct;
- (id)conversationPreviewHiddenSuperView:(id)arg1;
- (_Bool)previewGetImageData:(id)arg1 imageViewForIndex:(long long)arg2 finished:(CDUnknownBlockType)arg3;
- (id)preview:(id)arg1 highQualityImageURLForIndex:(long long)arg2;
- (id)preview:(id)arg1 imageViewForIndex:(long long)arg2;
- (_Bool)conversationCanDownLoad:(id)arg1 index:(long long)arg2;
- (void)apply;
- (void)setDescriptionlabelHeight;
- (void)desctiptionChangHegiht:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)showBigImage:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

