//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SGCombatListModel, UIImageView;

@protocol SGBigCombatListCellDelegate <NSObject>

@optional
- (void)tapLeftImageIdentify:(UIImageView *)arg1;
- (void)tapRightImageIdentify:(UIImageView *)arg1;
- (void)tapButton:(SGCombatListModel *)arg1;
@end

