//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SGCombatListModel, UIButton, UIImageView, UILabel;
@protocol SGBigCombatListCellDelegate;

@interface SGBigCombatListCell : UITableViewCell
{
    SGCombatListModel *_model;
    id <SGBigCombatListCellDelegate> _cellDelegate;
    UILabel *_titleLabel;
    UILabel *_label1;
    UILabel *_label2;
    UIImageView *_headImageView;
    UIImageView *_rightImageView;
    UIButton *_rightButton;
}

@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIImageView *rightImageView; // @synthesize rightImageView=_rightImageView;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) UILabel *label2; // @synthesize label2=_label2;
@property(retain, nonatomic) UILabel *label1; // @synthesize label1=_label1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <SGBigCombatListCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(retain, nonatomic) SGCombatListModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)clickLeftImage;
- (void)clickRightImage;
- (void)clcikButton:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

