//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGBroadcastViewCell.h"

@class UIButton, UILabel, UIView;

@interface SGBroadcastTextCell : SGBroadcastViewCell
{
    UIView *_backView;
    UILabel *_receiverLabel;
    UILabel *_messageLabel;
    UIView *_topView;
    UIButton *_againButton;
}

@property(nonatomic) __weak UIButton *againButton; // @synthesize againButton=_againButton;
@property(nonatomic) __weak UIView *topView; // @synthesize topView=_topView;
@property(nonatomic) __weak UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) __weak UILabel *receiverLabel; // @synthesize receiverLabel=_receiverLabel;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)againButtonClick:(id)arg1;
- (void)longPress:(id)arg1;
- (void)setModel:(id)arg1;
- (void)awakeFromNib;

@end

