//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGBroadcastModel.h"

@class NSAttributedString;

@interface SGBroadcastTextModel : SGBroadcastModel
{
    NSAttributedString *_messageAttribute;
    NSAttributedString *_receiverAttribute;
    struct CGSize _textSize;
    struct CGSize _receiverSize;
}

@property(nonatomic) struct CGSize receiverSize; // @synthesize receiverSize=_receiverSize;
@property(copy, nonatomic) NSAttributedString *receiverAttribute; // @synthesize receiverAttribute=_receiverAttribute;
@property(nonatomic) struct CGSize textSize; // @synthesize textSize=_textSize;
@property(copy, nonatomic) NSAttributedString *messageAttribute; // @synthesize messageAttribute=_messageAttribute;
- (void).cxx_destruct;
- (Class)getCellClass;
- (double)cellHeight;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

