//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SGGroupMember, SGUser;

@interface SGChooseContactsCellModel : NSObject
{
    _Bool _isNeedDelete;
    SGUser *_user;
    SGGroupMember *_groupMember;
    struct CGSize _size;
}

@property(retain, nonatomic) SGGroupMember *groupMember; // @synthesize groupMember=_groupMember;
@property(nonatomic) _Bool isNeedDelete; // @synthesize isNeedDelete=_isNeedDelete;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) SGUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)setSizeByName:(id)arg1;

@end

