//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SGChooseSearchMatchManger : NSObject
{
}

+ (id)breakStringInfoPart:(id)arg1;
+ (void)array:(id)arg1 addObjectFromArray:(id)arg2;
+ (id)hanyuSearchMatch:(id)arg1 matchContent:(id)arg2;
+ (id)searchMatch:(id)arg1 matchContent:(id)arg2;

@end

