//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

@class SGSetGameLoadingView;

@interface SGCloseGroupShopViewController : SGGoodsBaseViewController
{
    long long _groupID;
    SGSetGameLoadingView *_loadingView;
}

@property(retain, nonatomic) SGSetGameLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) long long groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)clickSureButton;
- (void)clickCloseButton;
- (void)creatChildView:(long long)arg1 day:(long long)arg2 isApplying:(_Bool)arg3;
- (void)retryRequest;
- (void)resuqestCanCLoseStore;
- (void)viewDidLoad;

@end

