//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASWatcher-Protocol.h"

@class ASHandle, NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface SGContactsManager : NSObject <ASWatcher>
{
    ASHandle *_actionHandle;
    NSDictionary *_contactsDict;
    NSArray *_keys;
    NSDictionary *_addressBookDic;
    NSArray *_addressBookKeys;
    NSMutableArray *_friendsArray;
    NSMutableDictionary *_friendUinDic;
    NSArray *_addressBookArray;
    NSMutableArray *_blacklist;
    NSDate *_lastGetFriendRequestDate;
}

+ (_Bool)isSystemAsstant:(long long)arg1;
+ (id)resolveContactsDict:(id)arg1;
+ (id)sharedContactsManager;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSDate *lastGetFriendRequestDate; // @synthesize lastGetFriendRequestDate=_lastGetFriendRequestDate;
@property(retain, nonatomic) NSMutableArray *blacklist; // @synthesize blacklist=_blacklist;
@property(retain, nonatomic) NSArray *addressBookArray; // @synthesize addressBookArray=_addressBookArray;
@property(retain, nonatomic) NSMutableDictionary *friendUinDic; // @synthesize friendUinDic=_friendUinDic;
@property(retain, nonatomic) NSMutableArray *friendsArray; // @synthesize friendsArray=_friendsArray;
@property(retain, nonatomic) NSArray *addressBookKeys; // @synthesize addressBookKeys=_addressBookKeys;
@property(retain, nonatomic) NSDictionary *addressBookDic; // @synthesize addressBookDic=_addressBookDic;
@property(retain, nonatomic) NSArray *keys; // @synthesize keys=_keys;
@property(retain, nonatomic) NSDictionary *contactsDict; // @synthesize contactsDict=_contactsDict;
@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
- (void).cxx_destruct;
- (void)updateBlackUser:(id)arg1;
- (void)judgeToAddToFriend:(long long)arg1;
- (id)matchAddressBookSearchResult:(id)arg1 isLocal:(_Bool)arg2;
- (id)matchUserArraySearchResult:(id)arg1 withUserArray:(id)arg2;
- (id)matchAddressBookSearchResult:(id)arg1;
- (void)getUserInfoDidUpdateStoreWithUserIds:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestBlacklistWithresult:(CDUnknownBlockType)arg1;
- (void)updateBlacklistWithUserUin:(long long)arg1 isBlacklist:(_Bool)arg2 result:(CDUnknownBlockType)arg3;
- (id)queryUserWhetherBlacklist:(long long)arg1;
- (id)getBlacklist;
- (_Bool)addUser:(id)arg1;
- (void)modifyUserInfo:(id)arg1;
- (_Bool)fromDataSourceToRemoveUser:(id)arg1;
- (id)queryUserFromCacheByUin:(long long)arg1;
- (void)sortDataSource;
- (void)updateCacheWithDataDict:(id)arg1 keys:(id)arg2;
- (void)archivedDataWithUsers:(id)arg1 contactAddressBookInfo:(CDUnknownBlockType)arg2;
- (void)uploadAddressBook:(id)arg1 replaceFlag:(_Bool)arg2 contactAddressBookInfo:(CDUnknownBlockType)arg3;
- (void)regetFriendLlist:(CDUnknownBlockType)arg1;
- (void)getFriendsList:(CDUnknownBlockType)arg1 isNotice:(_Bool)arg2;
- (void)getAddressBook:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)traversePhoneAndUpload:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)getLocalNameWithPhone:(id)arg1;
- (id)getFriendsArray;
- (id)getAddressBookKeys;
- (id)getAddressBookDict;
- (id)getContactsKeys;
- (id)getContactsDict;
- (void)clearFriendDic;
- (void)addFriendToFriendDic:(id)arg1;
- (void)removeFriendFromFriendDicBy:(long long)arg1;
- (id)getUserFromFriendFromFriendDicBy:(long long)arg1;
- (void)reSetFriendUinDic;
- (void)setCurrentVersion;
- (_Bool)isCurrentVersion;
- (id)getContactsVersion;
- (void)releaseContactsMemory;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

