//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class SGGroupCardShopModel;

@interface SGCouponsCellModel : SGDialogDetailCellModel
{
    SGGroupCardShopModel *_shopModel;
    struct CGRect _topTextFrame;
    struct CGRect _titleFrame;
    struct CGRect _bgViewFrame;
    struct CGRect _imageVFrame;
    struct CGRect _iconImageFrame;
    struct CGRect _shopNameFrame;
    struct CGRect _RMBLabelFrame;
}

@property(retain, nonatomic) SGGroupCardShopModel *shopModel; // @synthesize shopModel=_shopModel;
@property(nonatomic) struct CGRect RMBLabelFrame; // @synthesize RMBLabelFrame=_RMBLabelFrame;
@property(nonatomic) struct CGRect shopNameFrame; // @synthesize shopNameFrame=_shopNameFrame;
@property(nonatomic) struct CGRect iconImageFrame; // @synthesize iconImageFrame=_iconImageFrame;
@property(nonatomic) struct CGRect imageVFrame; // @synthesize imageVFrame=_imageVFrame;
@property(nonatomic) struct CGRect bgViewFrame; // @synthesize bgViewFrame=_bgViewFrame;
@property(nonatomic) struct CGRect titleFrame; // @synthesize titleFrame=_titleFrame;
@property(nonatomic) struct CGRect topTextFrame; // @synthesize topTextFrame=_topTextFrame;
- (void).cxx_destruct;
- (Class)getCellClass;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

