//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface SGConfirmSendPacketFromAllinpayReq : SGHTTPSReqModel
{
    NSString *_req_trace_num;
    long long _packetId;
}

@property(nonatomic) long long packetId; // @synthesize packetId=_packetId;
@property(copy, nonatomic) NSString *req_trace_num; // @synthesize req_trace_num=_req_trace_num;
- (void).cxx_destruct;
- (int)constructor;

@end

