//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGCollectViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface SGCollectCommonViewCell : SGCollectViewCell
{
    UIImageView *_senderIcon;
    UILabel *_senderNameLabel;
    UILabel *_collectTimeLabel;
    UILabel *_contentTitleLabel;
    UIImageView *_commonImageView;
    UILabel *_contentDetailLabel;
    NSLayoutConstraint *_top;
}

@property(nonatomic) __weak NSLayoutConstraint *top; // @synthesize top=_top;
@property(nonatomic) __weak UILabel *contentDetailLabel; // @synthesize contentDetailLabel=_contentDetailLabel;
@property(nonatomic) __weak UIImageView *commonImageView; // @synthesize commonImageView=_commonImageView;
@property(nonatomic) __weak UILabel *contentTitleLabel; // @synthesize contentTitleLabel=_contentTitleLabel;
@property(nonatomic) __weak UILabel *collectTimeLabel; // @synthesize collectTimeLabel=_collectTimeLabel;
@property(nonatomic) __weak UILabel *senderNameLabel; // @synthesize senderNameLabel=_senderNameLabel;
@property(nonatomic) __weak UIImageView *senderIcon; // @synthesize senderIcon=_senderIcon;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setModel:(id)arg1;
- (void)awakeFromNib;

@end

