//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

@class UIImageView, UILabel, UIView;

@interface SGCouponsTableViewCell : SGDialogDeatilBaseCell
{
    UILabel *_topLabel;
    UILabel *_titleLabel;
    UIView *_bgView;
    UILabel *_rmbLabel;
    UIImageView *_imageV;
    UIImageView *_iconView;
    UILabel *_shopName;
}

@property(retain, nonatomic) UILabel *shopName; // @synthesize shopName=_shopName;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIImageView *imageV; // @synthesize imageV=_imageV;
@property(retain, nonatomic) UILabel *rmbLabel; // @synthesize rmbLabel=_rmbLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)awakeFromNib;

@end

