//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSString, UILabel;

@interface SGCombatListModel : NSObject
{
    NSString *_imageUrl;
    NSString *_line1;
    NSString *_line2;
    NSString *_line3;
    NSString *_rightImageUrl;
    NSString *_buttonName;
    NSString *_buttonUrl;
    NSAttributedString *_line1Str;
    NSAttributedString *_line2Str;
    NSAttributedString *_line3Str;
    UILabel *_label1;
    UILabel *_label2;
    UILabel *_label3;
}

+ (void)load;
@property(nonatomic) __weak UILabel *label3; // @synthesize label3=_label3;
@property(nonatomic) __weak UILabel *label2; // @synthesize label2=_label2;
@property(nonatomic) __weak UILabel *label1; // @synthesize label1=_label1;
@property(copy, nonatomic) NSAttributedString *line3Str; // @synthesize line3Str=_line3Str;
@property(copy, nonatomic) NSAttributedString *line2Str; // @synthesize line2Str=_line2Str;
@property(copy, nonatomic) NSAttributedString *line1Str; // @synthesize line1Str=_line1Str;
@property(copy, nonatomic) NSString *buttonUrl; // @synthesize buttonUrl=_buttonUrl;
@property(copy, nonatomic) NSString *buttonName; // @synthesize buttonName=_buttonName;
@property(copy, nonatomic) NSString *rightImageUrl; // @synthesize rightImageUrl=_rightImageUrl;
@property(copy, nonatomic) NSString *line3; // @synthesize line3=_line3;
@property(copy, nonatomic) NSString *line2; // @synthesize line2=_line2;
@property(copy, nonatomic) NSString *line1; // @synthesize line1=_line1;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
- (void).cxx_destruct;
- (void)setLin3InLabel:(id)arg1;
- (void)setLin2InLabel:(id)arg1;
- (void)setLin1InLabel:(id)arg1;
- (id)linStringWtiht:(id)arg1;

@end

