//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SGCouponTemplateInfoVO;

@interface SGCouponReceiveVO : NSObject
{
    _Bool _couponsIsShow;
    _Bool _isChoose;
    int _usedStatus;
    long long _receiverId;
    long long _sendId;
    long long _templateId;
    long long _receiverUid;
    long long _senderUid;
    long long _destGroupId;
    long long _receiveTime;
    long long _usedTime;
    NSString *_orderNo;
    long long _createTime;
    NSString *_groupIconUrl;
    NSString *_groupTitle;
    NSString *_receiverNickName;
    NSString *_receiverSmallAvatarUrl;
    SGCouponTemplateInfoVO *_couponTemplateInfoVO;
    double _couponDescHeight;
}

+ (id)modelContainerPropertyGenericClass;
@property(nonatomic) _Bool isChoose; // @synthesize isChoose=_isChoose;
@property(nonatomic) _Bool couponsIsShow; // @synthesize couponsIsShow=_couponsIsShow;
@property(nonatomic) double couponDescHeight; // @synthesize couponDescHeight=_couponDescHeight;
@property(retain, nonatomic) SGCouponTemplateInfoVO *couponTemplateInfoVO; // @synthesize couponTemplateInfoVO=_couponTemplateInfoVO;
@property(copy, nonatomic) NSString *receiverSmallAvatarUrl; // @synthesize receiverSmallAvatarUrl=_receiverSmallAvatarUrl;
@property(copy, nonatomic) NSString *receiverNickName; // @synthesize receiverNickName=_receiverNickName;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(copy, nonatomic) NSString *groupIconUrl; // @synthesize groupIconUrl=_groupIconUrl;
@property(nonatomic) long long createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(nonatomic) long long usedTime; // @synthesize usedTime=_usedTime;
@property(nonatomic) int usedStatus; // @synthesize usedStatus=_usedStatus;
@property(nonatomic) long long receiveTime; // @synthesize receiveTime=_receiveTime;
@property(nonatomic) long long destGroupId; // @synthesize destGroupId=_destGroupId;
@property(nonatomic) long long senderUid; // @synthesize senderUid=_senderUid;
@property(nonatomic) long long receiverUid; // @synthesize receiverUid=_receiverUid;
@property(nonatomic) long long templateId; // @synthesize templateId=_templateId;
@property(nonatomic) long long sendId; // @synthesize sendId=_sendId;
@property(nonatomic) long long receiverId; // @synthesize receiverId=_receiverId;
- (void).cxx_destruct;

@end

