//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SGExpressTrace, SGSGMessageTextCellTextView, UILabel, UIView;
@protocol SGCourierCellDelegate;

@interface SGCourierCell : UITableViewCell
{
    SGExpressTrace *_model;
    id <SGCourierCellDelegate> _cellDelegate;
    SGSGMessageTextCellTextView *_stateDescLab;
    UILabel *_timeLab;
    UIView *_pointView;
    UIView *_verLineView;
}

@property(retain, nonatomic) UIView *verLineView; // @synthesize verLineView=_verLineView;
@property(retain, nonatomic) UIView *pointView; // @synthesize pointView=_pointView;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) SGSGMessageTextCellTextView *stateDescLab; // @synthesize stateDescLab=_stateDescLab;
@property(nonatomic) __weak id <SGCourierCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(retain, nonatomic) SGExpressTrace *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

