//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SGAdvententModel;

@interface SGCouponNoticeModel : NSObject
{
    int _jumpType;
    long long _groupId;
    long long _sendId;
    long long _receiverId;
    long long _templateId;
    long long _receiveTime;
    long long _discountAmount;
    long long _senderUid;
    NSString *_senderNickName;
    long long _receiverUid;
    NSString *_receiverNickName;
    NSString *_title;
    NSString *_content;
    long long _sendTime;
    NSString *_jumpDesc;
    NSString *_advertising;
    SGAdvententModel *_advertModel;
}

@property(retain, nonatomic) SGAdvententModel *advertModel; // @synthesize advertModel=_advertModel;
@property(copy, nonatomic) NSString *advertising; // @synthesize advertising=_advertising;
@property(copy, nonatomic) NSString *jumpDesc; // @synthesize jumpDesc=_jumpDesc;
@property(nonatomic) int jumpType; // @synthesize jumpType=_jumpType;
@property(nonatomic) long long sendTime; // @synthesize sendTime=_sendTime;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *receiverNickName; // @synthesize receiverNickName=_receiverNickName;
@property(nonatomic) long long receiverUid; // @synthesize receiverUid=_receiverUid;
@property(copy, nonatomic) NSString *senderNickName; // @synthesize senderNickName=_senderNickName;
@property(nonatomic) long long senderUid; // @synthesize senderUid=_senderUid;
@property(nonatomic) long long discountAmount; // @synthesize discountAmount=_discountAmount;
@property(nonatomic) long long receiveTime; // @synthesize receiveTime=_receiveTime;
@property(nonatomic) long long templateId; // @synthesize templateId=_templateId;
@property(nonatomic) long long receiverId; // @synthesize receiverId=_receiverId;
@property(nonatomic) long long sendId; // @synthesize sendId=_sendId;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;

@end

