//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGCouponTemplateInfoVO : NSObject
{
    int _couponScope;
    int _goodsScope;
    int _couponStatus;
    int _timeType;
    int _validDays;
    int _limitNum;
    NSString *_couponTitle;
    long long _startTime;
    long long _endTime;
    long long _thresholdAmount;
    long long _discountAmount;
    NSString *_couponDesc;
    long long _invalidTime;
    NSString *_useRules;
}

@property(copy, nonatomic) NSString *useRules; // @synthesize useRules=_useRules;
@property(nonatomic) long long invalidTime; // @synthesize invalidTime=_invalidTime;
@property(copy, nonatomic) NSString *couponDesc; // @synthesize couponDesc=_couponDesc;
@property(nonatomic) int limitNum; // @synthesize limitNum=_limitNum;
@property(nonatomic) long long discountAmount; // @synthesize discountAmount=_discountAmount;
@property(nonatomic) long long thresholdAmount; // @synthesize thresholdAmount=_thresholdAmount;
@property(nonatomic) int validDays; // @synthesize validDays=_validDays;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
@property(nonatomic) int timeType; // @synthesize timeType=_timeType;
@property(nonatomic) int couponStatus; // @synthesize couponStatus=_couponStatus;
@property(nonatomic) int goodsScope; // @synthesize goodsScope=_goodsScope;
@property(nonatomic) int couponScope; // @synthesize couponScope=_couponScope;
@property(copy, nonatomic) NSString *couponTitle; // @synthesize couponTitle=_couponTitle;
- (void).cxx_destruct;

@end

