//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface SGConfigItem : NSObject <NSCoding>
{
    NSString *_key;
    NSString *_value;
}

+ (id)getIPKeyFromType:(unsigned long long)arg1;
+ (id)getHttpsKeyFromType:(unsigned long long)arg1;
+ (id)getKeyFromType:(unsigned long long)arg1;
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)resp_deserialize:(id)arg1;

@end

