//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

@class NSString, SGScanCouponQrCodeResp, SGVerifyCouponInvitationLinkResp, UIButton, UIImageView, UILabel, UIView;

@interface SGCouponsToGroupViewController : SGGoodsBaseViewController
{
    NSString *_jsonString;
    SGScanCouponQrCodeResp *_resp;
    CDUnknownBlockType _block;
    SGVerifyCouponInvitationLinkResp *_couponLinkresp;
    UIView *_bgView;
    UIImageView *_titleImage;
    UILabel *_titleLabel;
    UIView *_couponsView;
    UILabel *_couponsNum;
    UILabel *_couponsTxt;
    UILabel *_typeLabel;
    UILabel *_goodsName;
    UILabel *_couponsTime;
    UIButton *_addGroup;
    UIImageView *_groupImage;
    UILabel *_groupTitle;
    UILabel *_downTitle;
    UILabel *_tipsLabel1;
    UILabel *_tipsLabel2;
}

@property(retain, nonatomic) UILabel *tipsLabel2; // @synthesize tipsLabel2=_tipsLabel2;
@property(retain, nonatomic) UILabel *tipsLabel1; // @synthesize tipsLabel1=_tipsLabel1;
@property(retain, nonatomic) UILabel *downTitle; // @synthesize downTitle=_downTitle;
@property(retain, nonatomic) UILabel *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(retain, nonatomic) UIImageView *groupImage; // @synthesize groupImage=_groupImage;
@property(retain, nonatomic) UIButton *addGroup; // @synthesize addGroup=_addGroup;
@property(retain, nonatomic) UILabel *couponsTime; // @synthesize couponsTime=_couponsTime;
@property(retain, nonatomic) UILabel *goodsName; // @synthesize goodsName=_goodsName;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) UILabel *couponsTxt; // @synthesize couponsTxt=_couponsTxt;
@property(retain, nonatomic) UILabel *couponsNum; // @synthesize couponsNum=_couponsNum;
@property(retain, nonatomic) UIView *couponsView; // @synthesize couponsView=_couponsView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *titleImage; // @synthesize titleImage=_titleImage;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) SGVerifyCouponInvitationLinkResp *couponLinkresp; // @synthesize couponLinkresp=_couponLinkresp;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) SGScanCouponQrCodeResp *resp; // @synthesize resp=_resp;
@property(copy, nonatomic) NSString *jsonString; // @synthesize jsonString=_jsonString;
- (void).cxx_destruct;
- (void)addShadowToView:(id)arg1 withColor:(id)arg2;
- (void)comeToGood:(id)arg1;
- (void)addGroupDetail:(id)arg1;
- (void)loadData;
- (void)viewDidLoad;

@end

