//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIImageView, UILabel;

@interface SGCustomAlertView : UIView
{
    UIImageView *_iconImageView;
    UILabel *_showTopLab;
    UIView *_centerView;
    CDUnknownBlockType _alertBlock;
    double _topH;
    NSArray *_otherButtonArray;
}

+ (id)showAlertViewWithAlerStyle:(long long)arg1 title:(id)arg2 otherButtonTitles:(id)arg3 handler:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) NSArray *otherButtonArray; // @synthesize otherButtonArray=_otherButtonArray;
@property(nonatomic) double topH; // @synthesize topH=_topH;
@property(copy, nonatomic) CDUnknownBlockType alertBlock; // @synthesize alertBlock=_alertBlock;
@property(nonatomic) __weak UIView *centerView; // @synthesize centerView=_centerView;
@property(retain, nonatomic) UILabel *showTopLab; // @synthesize showTopLab=_showTopLab;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (id)lineView;
- (void)dismiss;
- (void)clickButtonToSelect:(id)arg1;
- (void)creatChiledView:(id)arg1;

@end

