//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabaseQueue, GetGroupChatFunctionConfigResp, GetUserOpenIdResp, NSArray, NSMutableArray, NSString, NSTimer, SGGoldenBeanSwitchAndLimitResp;
@protocol OS_dispatch_queue;

@interface SGDatabase : NSObject
{
    _Bool _msgHasMediaConstructor;
    _Bool _updateMessageReceptFlag;
    _Bool _hasSg_message;
    _Bool _reloadDb;
    NSString *_dbPath;
    FMDatabaseQueue *_queue;
    NSObject<OS_dispatch_queue> *_updateQueue;
    long long _dbVersion;
    long long _oldDbVersion;
    NSMutableArray *_stickers;
    NSArray *_configItemList;
    SGGoldenBeanSwitchAndLimitResp *_goldBeanSwitchResp;
    GetGroupChatFunctionConfigResp *_groupChatConfigResp;
    GetUserOpenIdResp *_userOpenIdResp;
    NSArray *_sensitiveWordsList;
    NSTimer *_updateDecodeMessagesTimer;
    NSMutableArray *_updateDecodeMessages;
    NSMutableArray *_sg_message_sqls;
    long long _reSetDbErrorCount;
}

+ (void)updataQueue:(CDUnknownBlockType)arg1;
+ (id)updataQueue;
+ (id)DataBase;
@property(nonatomic) _Bool reloadDb; // @synthesize reloadDb=_reloadDb;
@property(nonatomic) long long reSetDbErrorCount; // @synthesize reSetDbErrorCount=_reSetDbErrorCount;
@property(nonatomic) _Bool hasSg_message; // @synthesize hasSg_message=_hasSg_message;
@property(retain, nonatomic) NSMutableArray *sg_message_sqls; // @synthesize sg_message_sqls=_sg_message_sqls;
@property(retain, nonatomic) NSMutableArray *updateDecodeMessages; // @synthesize updateDecodeMessages=_updateDecodeMessages;
@property(retain, nonatomic) NSTimer *updateDecodeMessagesTimer; // @synthesize updateDecodeMessagesTimer=_updateDecodeMessagesTimer;
@property(nonatomic) _Bool updateMessageReceptFlag; // @synthesize updateMessageReceptFlag=_updateMessageReceptFlag;
@property(retain, nonatomic) NSArray *sensitiveWordsList; // @synthesize sensitiveWordsList=_sensitiveWordsList;
@property(retain, nonatomic) GetUserOpenIdResp *userOpenIdResp; // @synthesize userOpenIdResp=_userOpenIdResp;
@property(retain, nonatomic) GetGroupChatFunctionConfigResp *groupChatConfigResp; // @synthesize groupChatConfigResp=_groupChatConfigResp;
@property(retain, nonatomic) SGGoldenBeanSwitchAndLimitResp *goldBeanSwitchResp; // @synthesize goldBeanSwitchResp=_goldBeanSwitchResp;
@property(retain, nonatomic) NSArray *configItemList; // @synthesize configItemList=_configItemList;
@property(retain, nonatomic) NSMutableArray *stickers; // @synthesize stickers=_stickers;
@property(nonatomic) long long oldDbVersion; // @synthesize oldDbVersion=_oldDbVersion;
@property(nonatomic) long long dbVersion; // @synthesize dbVersion=_dbVersion;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *updateQueue; // @synthesize updateQueue=_updateQueue;
@property(retain, nonatomic) FMDatabaseQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSString *dbPath; // @synthesize dbPath=_dbPath;
@property(nonatomic) _Bool msgHasMediaConstructor; // @synthesize msgHasMediaConstructor=_msgHasMediaConstructor;
- (void).cxx_destruct;
- (void)deleteInterestNoti;
- (id)selectInterestNoits:(long long)arg1 count:(int)arg2;
- (void)updateInteretNotis:(id)arg1;
- (void)createIntereseNotiTable:(id)arg1;
- (void)deleteInterestFrom:(long long)arg1 to:(long long)arg2;
- (void)deleteInterest:(long long)arg1;
- (id)selectInterestPost:(long long)arg1 fail:(_Bool)arg2;
- (void)updateInterest:(id)arg1;
- (void)createInterestTable:(id)arg1;
- (void)deleteTimingMessage:(long long)arg1 timerInterval:(double)arg2;
- (void)deleteBurnMessage:(long long)arg1;
- (void)deleteMessageWithMessages:(id)arg1;
- (void)deleteMessageWithMessageId:(long long)arg1 dilogId:(long long)arg2 db:(id)arg3;
- (void)deleteMessageWithMessageId:(long long)arg1 dilogId:(long long)arg2;
- (void)deleteMessageWithLocalId:(long long)arg1 dilogId:(long long)arg2 db:(id)arg3;
- (void)deleteMessageWithLocalId:(long long)arg1 dilogId:(long long)arg2;
- (void)updateRecallMessageWithDialogId:(long long)arg1 messageId:(long long)arg2 withMessage:(id)arg3;
- (id)cachePath;
- (void)saveOldDbData;
- (void)deleteDb;
- (void)reSetDb;
- (void)resetSgMessage:(id)arg1;
- (void)addsg_messageSql:(id)arg1 value:(id)arg2;
- (void)reportsg_message_error:(id)arg1;
- (void)deleteMessageWithUin:(long long)arg1;
- (id)loadLastMessageWithDialogId:(long long)arg1;
- (long long)selectedMessageCountWithDialogId:(long long)arg1 minMsgSendTime:(long long)arg2 maxMsgSendTime:(long long)arg3 mediaConstructor:(id)arg4;
- (id)selectMessageWithDialogId:(long long)arg1 Count:(long long)arg2 rowId:(long long)arg3 mediaConstructor:(id)arg4;
- (id)selectUpMessageWithDialogId:(long long)arg1 Count:(long long)arg2 appearRowId:(long long)arg3 rowId:(long long)arg4 groupMessageLifetime:(long long)arg5;
- (id)selectMessageWithDialogId:(long long)arg1 Count:(long long)arg2 rowId:(long long)arg3;
- (id)selectMessageWithdialogId:(long long)arg1 Count:(long long)arg2 mediaConstructor:(id)arg3;
- (id)selectMessageWithdialogIds:(id)arg1 Count:(long long)arg2;
- (id)selectMessageBySql:(id)arg1 arguments:(id)arg2 db:(id)arg3;
- (id)selectMessageWithdialogId:(long long)arg1 Count:(long long)arg2;
- (long long)getRowId;
- (void)updateMessageArr:(id)arg1 offset:(long long)arg2;
- (_Bool)updateMessage:(id)arg1 sql:(id)arg2 db:(id)arg3 dataModel:(id)arg4;
- (void)updateMessage:(id)arg1;
- (void)creatSg_message_table:(long long)arg1 db:(id)arg2;
- (id)sg_message_tableName:(long long)arg1;
- (id)selectGroupChat;
- (void)deleteGroupChatWithGroupId:(long long)arg1;
- (void)updateGroupChat:(id)arg1;
- (void)deleteAllDialogs;
- (void)deleteDialog:(long long)arg1;
- (void)updateDialogSeqno:(id)arg1;
- (void)updateDialogs:(id)arg1;
- (void)updateDialog:(id)arg1;
- (id)selectAllDialogs;
- (id)dataDecryption:(id)arg1 dialogId:(long long)arg2;
- (id)dialogsModelWithDBResult:(id)arg1;
- (id)loadAllGroupInfos;
- (void)removeGroupInfo:(long long)arg1;
- (void)updateGroupInfo:(id)arg1;
- (void)updateAccount:(id)arg1;
- (void)deleteSg_aeskey:(id)arg1;
- (void)deleteAllData;
- (id)getAccount;
- (void)dataBaseOperation:(CDUnknownBlockType)arg1;
- (void)updateMessageMediaConstructorBy:(id)arg1;
- (void)updateMessageMediaConstructor:(id)arg1;
- (void)SGDBVersion23To24:(id)arg1;
- (void)SGDBVersion22To23:(id)arg1;
- (void)SGDBVersion21To22:(id)arg1;
- (void)SGDBVersion20To21:(id)arg1;
- (void)SGDBVersion19To20:(id)arg1;
- (void)SGDBVersion18To19:(id)arg1;
- (void)SGDBVersion17To18:(id)arg1;
- (void)SGDBVersion16To17:(id)arg1;
- (void)SGDBVersion15To16:(id)arg1;
- (void)SGDBVersion14To15:(id)arg1;
- (void)SGDBVersion13To14:(id)arg1;
- (void)SGDBVersion12To13:(id)arg1;
- (void)SGDBVersion11To12:(id)arg1;
- (void)SGDBVersion10To11:(id)arg1;
- (void)SGDBVersion9To10:(id)arg1;
- (void)SGDBVersion8To9:(id)arg1;
- (void)SGDBVersion7To8:(id)arg1;
- (void)SGDBVersion6To7:(id)arg1;
- (void)SGDBVersion5To6:(id)arg1;
- (void)SGDBVersion4To5:(id)arg1;
- (void)SGDBVersion3To4:(id)arg1;
- (void)SGDBVersion2To3:(id)arg1;
- (void)SGDBVersion1To2:(id)arg1;
- (void)SGDBVersion0To1:(id)arg1;
- (void)updateDataBaseTable;
- (void)initDataBase;
- (void)updateunDecodeMessage;
- (void)addunDecodeMessage:(id)arg1;

@end

