//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface SGDeleteAlipayPacketReceiveReq : SGHTTPSReqModel
{
    _Bool _deleteAll;
    NSString *_packetIdList;
}

@property(copy, nonatomic) NSString *packetIdList; // @synthesize packetIdList=_packetIdList;
@property(nonatomic) _Bool deleteAll; // @synthesize deleteAll=_deleteAll;
- (void).cxx_destruct;
- (int)constructor;

@end

