//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSString;

@interface SGDialogHelperRedEnvelopeNotice : SGDialogDetailCellModel
{
    NSString *_redPacketRefundStr;
    NSString *_dateLabelText;
    NSString *_amountLabelText;
    NSString *_refundMoneyWay;
    NSString *_arrivalTimeStr;
    NSString *_refundReason;
    NSString *_remarkText;
}

@property(copy, nonatomic) NSString *remarkText; // @synthesize remarkText=_remarkText;
@property(copy, nonatomic) NSString *refundReason; // @synthesize refundReason=_refundReason;
@property(copy, nonatomic) NSString *arrivalTimeStr; // @synthesize arrivalTimeStr=_arrivalTimeStr;
@property(copy, nonatomic) NSString *refundMoneyWay; // @synthesize refundMoneyWay=_refundMoneyWay;
@property(copy, nonatomic) NSString *amountLabelText; // @synthesize amountLabelText=_amountLabelText;
@property(copy, nonatomic) NSString *dateLabelText; // @synthesize dateLabelText=_dateLabelText;
@property(copy, nonatomic) NSString *redPacketRefundStr; // @synthesize redPacketRefundStr=_redPacketRefundStr;
- (void).cxx_destruct;
- (double)cellHeight;
- (Class)getCellClass;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

