//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UILabel, UISearchController, UITableView, UIView;
@protocol SGDialogListSearchDelegate;

@interface SGDialogListSearchViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchResultsUpdating>
{
    int _searchType;
    NSArray *_dialogList;
    id <SGDialogListSearchDelegate> _delegate;
    UISearchController *_searchBar;
    UITableView *_tableView;
    NSMutableArray *_dataSource;
    NSString *_searchResult;
    UIView *_footView;
    UILabel *_tipsLabel;
    UIView *_noDataView;
}

@property(retain, nonatomic) UIView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UIView *footView; // @synthesize footView=_footView;
@property(copy, nonatomic) NSString *searchResult; // @synthesize searchResult=_searchResult;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UISearchController *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) int searchType; // @synthesize searchType=_searchType;
@property(nonatomic) __weak id <SGDialogListSearchDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *dialogList; // @synthesize dialogList=_dialogList;
- (void).cxx_destruct;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)diaogSearchUpdateTableView;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

