//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogHelperNoticeCell.h"

@class UIImageView, UILabel, UIView;

@interface SGDialogHelperTop_upDelayNoticeCell : SGDialogHelperNoticeCell
{
    UILabel *_title;
    UILabel *_dateLabel;
    UILabel *_contentLabel;
    UILabel *_nameLabel;
    UILabel *_payLabel;
    UILabel *_amountLabel;
    UILabel *_paySide;
    UIView *_bgView;
    UIImageView *_dotImageView;
}

@property(nonatomic) __weak UIImageView *dotImageView; // @synthesize dotImageView=_dotImageView;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak UILabel *paySide; // @synthesize paySide=_paySide;
@property(nonatomic) __weak UILabel *amountLabel; // @synthesize amountLabel=_amountLabel;
@property(nonatomic) __weak UILabel *payLabel; // @synthesize payLabel=_payLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(nonatomic) __weak UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) __weak UILabel *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)setModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

