//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogHelperNoticeCell.h"

@class UIButton, UILabel, UIView;

@interface SGDialogHelperPromotionNoticeCell : SGDialogHelperNoticeCell
{
    UILabel *_promotionLabel;
    UILabel *_timeLabel;
    UIView *_bgView;
    UILabel *_contentLabel;
    UILabel *_explainLabel;
    UILabel *_linkLabel;
    UIButton *_linkButton;
    UILabel *_lineSeperatorLabel;
}

@property(nonatomic) __weak UILabel *lineSeperatorLabel; // @synthesize lineSeperatorLabel=_lineSeperatorLabel;
@property(nonatomic) __weak UIButton *linkButton; // @synthesize linkButton=_linkButton;
@property(nonatomic) __weak UILabel *linkLabel; // @synthesize linkLabel=_linkLabel;
@property(nonatomic) __weak UILabel *explainLabel; // @synthesize explainLabel=_explainLabel;
@property(nonatomic) __weak UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *promotionLabel; // @synthesize promotionLabel=_promotionLabel;
- (void).cxx_destruct;
- (void)setModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)linkButtonClick:(id)arg1;
- (void)awakeFromNib;

@end

