//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, SGCombatListModel, SGDialogDeatilBaseCell, SGDialogDetailCellModel, SGGroupMember, UIView;

@protocol SGDialogDetailCellModelDelegate <NSObject>
- (void)conversationRecallMessageEditAgain:(SGDialogDetailCellModel *)arg1;
- (void)conversationDoubleClickTableViewContent:(SGDialogDetailCellModel *)arg1;
- (void)combataCellButtonTap:(SGCombatListModel *)arg1 a:(NSDictionary *)arg2;
- (void)touchesEndAction;
- (_Bool)conversationSelectedMore:(SGDialogDetailCellModel *)arg1;
- (_Bool)canLongPressUser;
- (void)userAvatarTap:(SGGroupMember *)arg1;
- (void)conversationResendMessage:(SGDialogDetailCellModel *)arg1;
- (void)conversationTableViewLongGestureMessageModel:(SGDialogDetailCellModel *)arg1 tapView:(UIView *)arg2;
- (void)tableViewAudioTap:(SGDialogDetailCellModel *)arg1 cell:(SGDialogDeatilBaseCell *)arg2;
- (void)conversationTableViewOtherContentTap:(SGDialogDetailCellModel *)arg1;
- (void)conversationTableViewContentTap:(SGDialogDetailCellModel *)arg1 userId:(long long)arg2;
- (void)conversationTableViewContentTap:(SGDialogDetailCellModel *)arg1;
@end

