//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSDictionary, NSString, UIImage;

@interface SGDialogMessageLocationCellModel : SGDialogDetailCellModel
{
    NSString *_title;
    NSString *_content;
    UIImage *_locationImage;
    NSDictionary *_loacitonDic;
    struct CLLocationCoordinate2D _coordinate;
    struct CGRect _titleFrame;
    struct CGRect _contentFrame;
    struct CGRect _locationImageFrame;
}

@property(retain, nonatomic) NSDictionary *loacitonDic; // @synthesize loacitonDic=_loacitonDic;
@property(nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
@property(nonatomic) struct CGRect locationImageFrame; // @synthesize locationImageFrame=_locationImageFrame;
@property(copy, nonatomic) UIImage *locationImage; // @synthesize locationImage=_locationImage;
@property(nonatomic) struct CGRect contentFrame; // @synthesize contentFrame=_contentFrame;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) struct CGRect titleFrame; // @synthesize titleFrame=_titleFrame;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (Class)getCellClass;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

