//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSDictionary, NSMutableAttributedString, NSMutableDictionary, NSString, SGSGMessageTextCellTextView;

@interface SGDialogMessageGiftCellModel : SGDialogDetailCellModel
{
    NSMutableAttributedString *_sendGiftTitleAttributeStr;
    NSString *_giftUrl;
    NSString *_giftIconName;
    NSMutableAttributedString *_messageAttributeStr;
    SGSGMessageTextCellTextView *_messageTextView;
    NSMutableDictionary *_urlStrDic;
    NSDictionary *_contentDict;
    struct _NSRange _range;
    struct _NSRange _tempRange;
    struct CGRect _titleFrame;
    struct CGRect _bgImageViewFrame;
    struct CGRect _giftImageFrame;
    struct CGRect _sendGiftTitleFrame;
}

@property(retain, nonatomic) NSDictionary *contentDict; // @synthesize contentDict=_contentDict;
@property(nonatomic) struct _NSRange tempRange; // @synthesize tempRange=_tempRange;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
@property(retain, nonatomic) NSMutableDictionary *urlStrDic; // @synthesize urlStrDic=_urlStrDic;
@property(retain, nonatomic) SGSGMessageTextCellTextView *messageTextView; // @synthesize messageTextView=_messageTextView;
@property(retain, nonatomic) NSMutableAttributedString *messageAttributeStr; // @synthesize messageAttributeStr=_messageAttributeStr;
@property(copy, nonatomic) NSString *giftIconName; // @synthesize giftIconName=_giftIconName;
@property(copy, nonatomic) NSString *giftUrl; // @synthesize giftUrl=_giftUrl;
@property(retain, nonatomic) NSMutableAttributedString *sendGiftTitleAttributeStr; // @synthesize sendGiftTitleAttributeStr=_sendGiftTitleAttributeStr;
@property(nonatomic) struct CGRect sendGiftTitleFrame; // @synthesize sendGiftTitleFrame=_sendGiftTitleFrame;
@property(nonatomic) struct CGRect giftImageFrame; // @synthesize giftImageFrame=_giftImageFrame;
@property(nonatomic) struct CGRect bgImageViewFrame; // @synthesize bgImageViewFrame=_bgImageViewFrame;
@property(nonatomic) struct CGRect titleFrame; // @synthesize titleFrame=_titleFrame;
- (void).cxx_destruct;
- (id)getCellby:(id)arg1;
- (Class)getCellClass;
- (double)cellHeight;
- (id)getNewGoldSendGiftSharePostent:(id)arg1;
- (id)backPostTent:(id)arg1;
- (id)attributeWithText:(id)arg1 isHasImage:(_Bool)arg2 color:(long long)arg3;
- (id)getMessageAttributedStringWithMessage:(id)arg1 color:(long long)arg2;
- (struct CGSize)getSizeBy:(id)arg1 maxSize:(struct CGSize)arg2;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

