//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSDictionary, NSString;

@interface SGDialogMessageAudioCellModel : SGDialogDetailCellModel
{
    _Bool _isPlaying;
    _Bool _isDownLoad;
    _Bool _isDownLoading;
    NSDictionary *_audioDict;
    NSString *_during;
    NSString *_filePath;
    NSString *_audioFilePath;
    struct CGRect _durationLabelFrame;
    struct CGRect _voiceImageViewFrame;
    struct CGRect _noReadHintIVFrame;
}

@property(copy, nonatomic) NSString *audioFilePath; // @synthesize audioFilePath=_audioFilePath;
@property(nonatomic) _Bool isDownLoading; // @synthesize isDownLoading=_isDownLoading;
@property(nonatomic) _Bool isDownLoad; // @synthesize isDownLoad=_isDownLoad;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(nonatomic) struct CGRect noReadHintIVFrame; // @synthesize noReadHintIVFrame=_noReadHintIVFrame;
@property(nonatomic) struct CGRect voiceImageViewFrame; // @synthesize voiceImageViewFrame=_voiceImageViewFrame;
@property(nonatomic) struct CGRect durationLabelFrame; // @synthesize durationLabelFrame=_durationLabelFrame;
@property(copy, nonatomic) NSString *during; // @synthesize during=_during;
@property(retain, nonatomic) NSDictionary *audioDict; // @synthesize audioDict=_audioDict;
- (void).cxx_destruct;
- (Class)getCellClass;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

