//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

@class UIImageView, UILabel;

@interface SGDialogMessageTransferCell : SGDialogDeatilBaseCell
{
    _Bool _isShouldHidden;
    UIImageView *_transferImageView;
    UILabel *_transLabel;
    UILabel *_amountLabel;
    UILabel *_whiteLabel;
    UILabel *_descriptionLabel;
}

@property(nonatomic) _Bool isShouldHidden; // @synthesize isShouldHidden=_isShouldHidden;
@property(nonatomic) __weak UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(nonatomic) __weak UILabel *whiteLabel; // @synthesize whiteLabel=_whiteLabel;
@property(nonatomic) __weak UILabel *amountLabel; // @synthesize amountLabel=_amountLabel;
@property(nonatomic) __weak UILabel *transLabel; // @synthesize transLabel=_transLabel;
@property(nonatomic) __weak UIImageView *transferImageView; // @synthesize transferImageView=_transferImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

