//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

@class SGSGMessageTextCellTextView, UIImageView, UILabel;

@interface SGDialogMessageGiftCell : SGDialogDeatilBaseCell
{
    SGSGMessageTextCellTextView *_titleLabel;
    UILabel *_leftLineLabel;
    UILabel *_rightLineLabel;
    UIImageView *_giftImageView;
    UILabel *_sendGiftLabel;
    UILabel *_giftContentLabel;
    struct _NSRange _range;
    struct _NSRange _tempRange;
}

@property(nonatomic) __weak UILabel *giftContentLabel; // @synthesize giftContentLabel=_giftContentLabel;
@property(nonatomic) __weak UILabel *sendGiftLabel; // @synthesize sendGiftLabel=_sendGiftLabel;
@property(nonatomic) __weak UIImageView *giftImageView; // @synthesize giftImageView=_giftImageView;
@property(nonatomic) struct _NSRange tempRange; // @synthesize tempRange=_tempRange;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
@property(nonatomic) __weak UILabel *rightLineLabel; // @synthesize rightLineLabel=_rightLineLabel;
@property(nonatomic) __weak UILabel *leftLineLabel; // @synthesize leftLineLabel=_leftLineLabel;
@property(retain, nonatomic) SGSGMessageTextCellTextView *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)awakeFromNib;

@end

