//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

@class UIActivityIndicatorView, UIImageView, UILabel, UIView;

@interface SGDialogMessageVideoCell : SGDialogDeatilBaseCell
{
    UIImageView *_picImageview;
    UIImageView *_playiCon;
    UIView *_loadingvView;
    UIActivityIndicatorView *_loading;
    UILabel *_tips;
}

@property(nonatomic) __weak UILabel *tips; // @synthesize tips=_tips;
@property(nonatomic) __weak UIActivityIndicatorView *loading; // @synthesize loading=_loading;
@property(nonatomic) __weak UIView *loadingvView; // @synthesize loadingvView=_loadingvView;
@property(nonatomic) __weak UIImageView *playiCon; // @synthesize playiCon=_playiCon;
@property(nonatomic) __weak UIImageView *picImageview; // @synthesize picImageview=_picImageview;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

