//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

@class UIImageView, UILabel, UIView;

@interface SGDynamicAmoutNoticeCell : SGDialogDeatilBaseCell
{
    UILabel *_noticeTitleLab;
    UILabel *_noticeTimeLab;
    UILabel *_noticeAmoutLab;
    UILabel *_noticeBanlanceTextLab;
    UILabel *_firstKeyLab;
    UILabel *_firstValueLab;
    UILabel *_secondKeyLab;
    UILabel *_secondValueLab;
    UILabel *_thirdKeyLab;
    UILabel *_thirdValueLab;
    UILabel *_fourthKeyLab;
    UILabel *_fourthValueLab;
    UILabel *_fifKeyLab;
    UILabel *_fifValueLab;
    UILabel *_sixKeyLab;
    UILabel *_sixValueLab;
    UILabel *_sevenKeyLab;
    UILabel *_sevenValueLab;
    UILabel *_eightKeyLab;
    UILabel *_eightValueLab;
    UIView *_lineView;
    UILabel *_bottomTextLab;
    UIImageView *_arrowImageView;
    UIView *_whiteView;
}

@property(nonatomic) __weak UIView *whiteView; // @synthesize whiteView=_whiteView;
@property(nonatomic) __weak UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(nonatomic) __weak UILabel *bottomTextLab; // @synthesize bottomTextLab=_bottomTextLab;
@property(nonatomic) __weak UIView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) __weak UILabel *eightValueLab; // @synthesize eightValueLab=_eightValueLab;
@property(nonatomic) __weak UILabel *eightKeyLab; // @synthesize eightKeyLab=_eightKeyLab;
@property(nonatomic) __weak UILabel *sevenValueLab; // @synthesize sevenValueLab=_sevenValueLab;
@property(nonatomic) __weak UILabel *sevenKeyLab; // @synthesize sevenKeyLab=_sevenKeyLab;
@property(nonatomic) __weak UILabel *sixValueLab; // @synthesize sixValueLab=_sixValueLab;
@property(nonatomic) __weak UILabel *sixKeyLab; // @synthesize sixKeyLab=_sixKeyLab;
@property(nonatomic) __weak UILabel *fifValueLab; // @synthesize fifValueLab=_fifValueLab;
@property(nonatomic) __weak UILabel *fifKeyLab; // @synthesize fifKeyLab=_fifKeyLab;
@property(nonatomic) __weak UILabel *fourthValueLab; // @synthesize fourthValueLab=_fourthValueLab;
@property(nonatomic) __weak UILabel *fourthKeyLab; // @synthesize fourthKeyLab=_fourthKeyLab;
@property(nonatomic) __weak UILabel *thirdValueLab; // @synthesize thirdValueLab=_thirdValueLab;
@property(nonatomic) __weak UILabel *thirdKeyLab; // @synthesize thirdKeyLab=_thirdKeyLab;
@property(nonatomic) __weak UILabel *secondValueLab; // @synthesize secondValueLab=_secondValueLab;
@property(nonatomic) __weak UILabel *secondKeyLab; // @synthesize secondKeyLab=_secondKeyLab;
@property(nonatomic) __weak UILabel *firstValueLab; // @synthesize firstValueLab=_firstValueLab;
@property(nonatomic) __weak UILabel *firstKeyLab; // @synthesize firstKeyLab=_firstKeyLab;
@property(nonatomic) __weak UILabel *noticeBanlanceTextLab; // @synthesize noticeBanlanceTextLab=_noticeBanlanceTextLab;
@property(nonatomic) __weak UILabel *noticeAmoutLab; // @synthesize noticeAmoutLab=_noticeAmoutLab;
@property(nonatomic) __weak UILabel *noticeTimeLab; // @synthesize noticeTimeLab=_noticeTimeLab;
@property(nonatomic) __weak UILabel *noticeTitleLab; // @synthesize noticeTitleLab=_noticeTitleLab;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)setValueLabelTextColor:(id)arg1;
- (void)setKeyLabelTextColor:(id)arg1;
- (void)awakeFromNib;

@end

