//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSString;

@interface SGEnterLqtMainResp : SGHTTPSResponseModel
{
    _Bool _openFlag;
    long long _lqtCashAmount;
    long long _totalProfit;
    NSString *_annualRateIn7days;
    NSString *_fundName;
    NSString *_supportedPartnerName;
    NSString *_fundDetailUrl;
    NSString *_fundHelpUrl;
    NSString *_openUrl;
    NSString *_buyUrl;
    NSString *_disposableAmtRemark;
    long long _disposableAmt;
    long long _yesterdayIncome;
    NSString *_lqtAmountExplain;
    NSString *_lqtPurchaseExplain;
    NSString *_lqtRepayExplain;
    NSString *_withdrawDesc;
}

+ (int)constructor;
@property(copy, nonatomic) NSString *withdrawDesc; // @synthesize withdrawDesc=_withdrawDesc;
@property(copy, nonatomic) NSString *lqtRepayExplain; // @synthesize lqtRepayExplain=_lqtRepayExplain;
@property(copy, nonatomic) NSString *lqtPurchaseExplain; // @synthesize lqtPurchaseExplain=_lqtPurchaseExplain;
@property(copy, nonatomic) NSString *lqtAmountExplain; // @synthesize lqtAmountExplain=_lqtAmountExplain;
@property(nonatomic) long long yesterdayIncome; // @synthesize yesterdayIncome=_yesterdayIncome;
@property(nonatomic) long long disposableAmt; // @synthesize disposableAmt=_disposableAmt;
@property(copy, nonatomic) NSString *disposableAmtRemark; // @synthesize disposableAmtRemark=_disposableAmtRemark;
@property(copy, nonatomic) NSString *buyUrl; // @synthesize buyUrl=_buyUrl;
@property(copy, nonatomic) NSString *openUrl; // @synthesize openUrl=_openUrl;
@property(copy, nonatomic) NSString *fundHelpUrl; // @synthesize fundHelpUrl=_fundHelpUrl;
@property(copy, nonatomic) NSString *fundDetailUrl; // @synthesize fundDetailUrl=_fundDetailUrl;
@property(copy, nonatomic) NSString *supportedPartnerName; // @synthesize supportedPartnerName=_supportedPartnerName;
@property(copy, nonatomic) NSString *fundName; // @synthesize fundName=_fundName;
@property(copy, nonatomic) NSString *annualRateIn7days; // @synthesize annualRateIn7days=_annualRateIn7days;
@property(nonatomic) long long totalProfit; // @synthesize totalProfit=_totalProfit;
@property(nonatomic) long long lqtCashAmount; // @synthesize lqtCashAmount=_lqtCashAmount;
@property(nonatomic) _Bool openFlag; // @synthesize openFlag=_openFlag;
- (void).cxx_destruct;

@end

