//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, NSTimer, SGButton, UIButton, UILabel, UITextField;

@interface SGFindPasswordViewController : SGViewController <UITextFieldDelegate>
{
    NSString *_phone;
    NSString *_langCode;
    UILabel *_countryCodeLab;
    UITextField *_phoneTF;
    SGButton *_nextButton;
    UILabel *_errorLab;
    NSString *_countryCode;
    UITextField *_codeTF;
    UIButton *_getCodeBtn;
    UILabel *_checkCodeLabel;
    UILabel *_codeLabel;
    long long _remainTime;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) long long remainTime; // @synthesize remainTime=_remainTime;
@property(retain, nonatomic) UILabel *codeLabel; // @synthesize codeLabel=_codeLabel;
@property(retain, nonatomic) UILabel *checkCodeLabel; // @synthesize checkCodeLabel=_checkCodeLabel;
@property(retain, nonatomic) UIButton *getCodeBtn; // @synthesize getCodeBtn=_getCodeBtn;
@property(retain, nonatomic) UITextField *codeTF; // @synthesize codeTF=_codeTF;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(retain, nonatomic) UILabel *errorLab; // @synthesize errorLab=_errorLab;
@property(retain, nonatomic) SGButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) UITextField *phoneTF; // @synthesize phoneTF=_phoneTF;
@property(retain, nonatomic) UILabel *countryCodeLab; // @synthesize countryCodeLab=_countryCodeLab;
@property(copy, nonatomic) NSString *langCode; // @synthesize langCode=_langCode;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
- (void).cxx_destruct;
- (void)enableCHeckdumButton:(id)arg1;
- (void)getSmsCode;
- (void)textFieldDidChange:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)sgEndEditing;
- (void)chooseCountryAction;
- (void)confirmAction;
- (void)setBtnEnabledWithState:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

