//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSArray;

@interface SGGetReceivedGiftStatisticsResp : SGHTTPSResponseModel
{
    long long _totalReceiveNum;
    long long _totalCharm;
    NSArray *_itemList;
}

+ (id)modelContainerPropertyGenericClass;
+ (int)constructor;
@property(retain, nonatomic) NSArray *itemList; // @synthesize itemList=_itemList;
@property(nonatomic) long long totalCharm; // @synthesize totalCharm=_totalCharm;
@property(nonatomic) long long totalReceiveNum; // @synthesize totalReceiveNum=_totalReceiveNum;
- (void).cxx_destruct;

@end

