//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface SGGetXianliaoImConfigResp : SGHTTPSResponseModel <NSCoding>
{
    NSString *_xlimemojiUrl;
    long long _dataVersion;
    double _loadTimeInterval;
}

+ (int)constructor;
@property(nonatomic) double loadTimeInterval; // @synthesize loadTimeInterval=_loadTimeInterval;
@property(nonatomic) long long dataVersion; // @synthesize dataVersion=_dataVersion;
@property(copy, nonatomic) NSString *xlimemojiUrl; // @synthesize xlimemojiUrl=_xlimemojiUrl;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

