//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@interface SGGetGroupGoodsListReq : SGHTTPSReqModel
{
    _Bool _delInvalidFlag;
    _Bool _adminFlag;
    int _pageNo;
    int _pageSize;
    long long _groupId;
}

@property(nonatomic) _Bool adminFlag; // @synthesize adminFlag=_adminFlag;
@property(nonatomic) _Bool delInvalidFlag; // @synthesize delInvalidFlag=_delInvalidFlag;
@property(nonatomic) int pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) int pageNo; // @synthesize pageNo=_pageNo;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (int)constructor;

@end

