//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSArray;

@interface SGGetGroupGoodsListResp : SGHTTPSResponseModel
{
    NSArray *_officialGoodsList;
    NSArray *_selfDefinedGoodsList;
    NSArray *_officialGoodsIdList;
}

+ (id)modelContainerPropertyGenericClass;
+ (int)constructor;
@property(retain, nonatomic) NSArray *officialGoodsIdList; // @synthesize officialGoodsIdList=_officialGoodsIdList;
@property(retain, nonatomic) NSArray *selfDefinedGoodsList; // @synthesize selfDefinedGoodsList=_selfDefinedGoodsList;
@property(retain, nonatomic) NSArray *officialGoodsList; // @synthesize officialGoodsList=_officialGoodsList;
- (void).cxx_destruct;

@end

