//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@interface SGGetDonateIdBeforeSendResp : SGHTTPSResponseModel
{
    int _remainBeanNum;
    long long _donateId;
}

+ (int)constructor;
@property(nonatomic) int remainBeanNum; // @synthesize remainBeanNum=_remainBeanNum;
@property(nonatomic) long long donateId; // @synthesize donateId=_donateId;

@end

