//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@interface SGGetTransIdBeforeSendResp : SGHTTPSResponseModel
{
    long long _transferId;
    long long _cashAmount;
    long long _unlockTime;
}

+ (int)constructor;
@property(nonatomic) long long unlockTime; // @synthesize unlockTime=_unlockTime;
@property(nonatomic) long long cashAmount; // @synthesize cashAmount=_cashAmount;
@property(nonatomic) long long transferId; // @synthesize transferId=_transferId;

@end

