//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSArray, NSString;

@interface SGGetAliPacketRecListResp : SGHTTPSResponseModel
{
    int _totalNum;
    long long _totalAmount;
    NSArray *_packetRevList;
    NSString *_alipay_user_id;
    NSString *_alipay_nick_name;
    NSString *_alipay_avatar;
    NSString *_payeeLogonId;
}

+ (id)modelContainerPropertyGenericClass;
+ (int)constructor;
@property(copy, nonatomic) NSString *payeeLogonId; // @synthesize payeeLogonId=_payeeLogonId;
@property(copy, nonatomic) NSString *alipay_avatar; // @synthesize alipay_avatar=_alipay_avatar;
@property(copy, nonatomic) NSString *alipay_nick_name; // @synthesize alipay_nick_name=_alipay_nick_name;
@property(copy, nonatomic) NSString *alipay_user_id; // @synthesize alipay_user_id=_alipay_user_id;
@property(retain, nonatomic) NSArray *packetRevList; // @synthesize packetRevList=_packetRevList;
@property(nonatomic) int totalNum; // @synthesize totalNum=_totalNum;
@property(nonatomic) long long totalAmount; // @synthesize totalAmount=_totalAmount;
- (void).cxx_destruct;

@end

