//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@interface SGGetSpikeActivityListReq : SGHTTPSReqModel
{
    int _limit;
    int _pageNum;
    int _pageSize;
    long long _groupId;
}

@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
@property(nonatomic) int pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) int pageNum; // @synthesize pageNum=_pageNum;
@property(nonatomic) int limit; // @synthesize limit=_limit;
- (int)constructor;

@end

