//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPageControl.h>

@interface SGGoodsPageControl : UIPageControl
{
    long long _totalPageNum;
}

@property(nonatomic) long long totalPageNum; // @synthesize totalPageNum=_totalPageNum;
- (id)getViewImageView:(id)arg1;
- (void)setCurrentPage:(long long)arg1;
- (void)layoutSubviews;
- (id)init;

@end

