//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITextViewDelegate-Protocol.h"

@class NSString, SGDialogs, SGGetDonateIdBeforeSendResp, UIButton, UILabel, UITextField, UITextView;

@interface SGGoldBeanDonatedController : SGViewController <UITextViewDelegate>
{
    SGDialogs *_groupDialog;
    UITextField *_goldBeanAmount;
    UITextView *_wishTextView;
    UILabel *_wishPlaceholderLabel;
    NSString *_oldText;
    UIButton *_donatButton;
    SGGetDonateIdBeforeSendResp *_beforeResp;
}

@property(retain, nonatomic) SGGetDonateIdBeforeSendResp *beforeResp; // @synthesize beforeResp=_beforeResp;
@property(nonatomic) __weak UIButton *donatButton; // @synthesize donatButton=_donatButton;
@property(copy, nonatomic) NSString *oldText; // @synthesize oldText=_oldText;
@property(retain, nonatomic) UILabel *wishPlaceholderLabel; // @synthesize wishPlaceholderLabel=_wishPlaceholderLabel;
@property(nonatomic) __weak UITextView *wishTextView; // @synthesize wishTextView=_wishTextView;
@property(nonatomic) __weak UITextField *goldBeanAmount; // @synthesize goldBeanAmount=_goldBeanAmount;
@property(retain, nonatomic) SGDialogs *groupDialog; // @synthesize groupDialog=_groupDialog;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)donatButtonClick;
- (void)getDonateIdBeforeSendResp;
- (void)setCorner;
- (void)textViewDidChange:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

