//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ASWatcher-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class ASHandle, GoodsDetail, NSArray, NSMutableArray, NSString, SGGoodsDetailPageView, SGTopIconButton, UIButton, UICollectionView, _TtC8xianliao24SGGoodVideoPoritFullView, _TtC8xianliao26SGGoodsDetailPLayVideoView;
@protocol SGGoodsDetailCycleViewDelegate;

@interface SGGoodsDetailCycleView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, ASWatcher>
{
    _Bool _isContailVideo;
    _Bool _isShowVideo;
    _Bool _isLandscapeWithBackGround;
    NSArray *_goodsPhotoUrlList;
    id <SGGoodsDetailCycleViewDelegate> _delegate;
    GoodsDetail *_goodsModell;
    UICollectionView *_collectionView;
    NSMutableArray *_dataSource;
    NSMutableArray *_videoIconSource;
    SGGoodsDetailPageView *_pageView;
    UIView *_showSwitchVideoIconView;
    SGTopIconButton *_videoButton;
    UIButton *_iconButton;
    UIButton *_voiceButton;
    _TtC8xianliao26SGGoodsDetailPLayVideoView *_playView;
    UIView *_playOrignParentView;
    _TtC8xianliao24SGGoodVideoPoritFullView *_portVideoView;
    ASHandle *_actionHandle;
    struct CGRect _playOrignFrame;
}

@property(nonatomic) _Bool isLandscapeWithBackGround; // @synthesize isLandscapeWithBackGround=_isLandscapeWithBackGround;
@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
@property(nonatomic) __weak _TtC8xianliao24SGGoodVideoPoritFullView *portVideoView; // @synthesize portVideoView=_portVideoView;
@property(nonatomic) struct CGRect playOrignFrame; // @synthesize playOrignFrame=_playOrignFrame;
@property(nonatomic) __weak UIView *playOrignParentView; // @synthesize playOrignParentView=_playOrignParentView;
@property(retain, nonatomic) _TtC8xianliao26SGGoodsDetailPLayVideoView *playView; // @synthesize playView=_playView;
@property(nonatomic) _Bool isShowVideo; // @synthesize isShowVideo=_isShowVideo;
@property(retain, nonatomic) UIButton *voiceButton; // @synthesize voiceButton=_voiceButton;
@property(retain, nonatomic) UIButton *iconButton; // @synthesize iconButton=_iconButton;
@property(retain, nonatomic) SGTopIconButton *videoButton; // @synthesize videoButton=_videoButton;
@property(retain, nonatomic) UIView *showSwitchVideoIconView; // @synthesize showSwitchVideoIconView=_showSwitchVideoIconView;
@property(nonatomic) _Bool isContailVideo; // @synthesize isContailVideo=_isContailVideo;
@property(retain, nonatomic) SGGoodsDetailPageView *pageView; // @synthesize pageView=_pageView;
@property(retain, nonatomic) NSMutableArray *videoIconSource; // @synthesize videoIconSource=_videoIconSource;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) GoodsDetail *goodsModell; // @synthesize goodsModell=_goodsModell;
@property(nonatomic) __weak id <SGGoodsDetailCycleViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *goodsPhotoUrlList; // @synthesize goodsPhotoUrlList=_goodsPhotoUrlList;
- (void).cxx_destruct;
- (void)dealloc;
- (void)pausePlay;
- (void)voiceButtonClick;
- (void)resetVideoAndIconButton:(_Bool)arg1;
- (void)scrollSwitchVideoAndIcon:(_Bool)arg1;
- (void)iconButtonClick;
- (void)videoButtonClick;
- (id)getNowShowCoverImage;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)swiftchLandscapePlay;
- (void)switchPortrtaitPlay:(struct CGSize)arg1;
- (void)appWillEnterBackground:(id)arg1;
- (void)actionStageResourceDispatched:(id)arg1 resource:(id)arg2 arguments:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

