//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView;

@interface SGGoldRewardDetailCell : UITableViewCell
{
    UIImageView *_headImageView;
    UILabel *_nickLab;
    UILabel *_timeLab;
    UILabel *_moneyLab;
    UILabel *_luckLab;
    UIView *_lineV;
}

@property(retain, nonatomic) UIView *lineV; // @synthesize lineV=_lineV;
@property(retain, nonatomic) UILabel *luckLab; // @synthesize luckLab=_luckLab;
@property(retain, nonatomic) UILabel *moneyLab; // @synthesize moneyLab=_moneyLab;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) UILabel *nickLab; // @synthesize nickLab=_nickLab;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void).cxx_destruct;
- (void)setReciveUserModel:(id)arg1;
- (void)creatChildView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

