//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

@class SGIdentifyXCodeResp, SGScanGoodsQrCodeResp, UIButton, UIImageView, UILabel, UIView;

@interface SGGoodToGroupViewController : SGGoodsBaseViewController
{
    SGScanGoodsQrCodeResp *_resp;
    SGIdentifyXCodeResp *_coderesp;
    CDUnknownBlockType _block;
    CDUnknownBlockType _codeBlock;
    UIView *_bgView;
    UIImageView *_imageV;
    UILabel *_titleLabel;
    UILabel *_priceLabel;
    UILabel *_noPriceLabel;
    UILabel *_groupTitle;
    UIImageView *_groupImage;
    UIImageView *_shareIcon;
    UILabel *_shareName;
    UIButton *_addGroup;
    double _screenFloat;
    UILabel *_middleLine;
}

@property(retain, nonatomic) UILabel *middleLine; // @synthesize middleLine=_middleLine;
@property(nonatomic) double screenFloat; // @synthesize screenFloat=_screenFloat;
@property(retain, nonatomic) UIButton *addGroup; // @synthesize addGroup=_addGroup;
@property(retain, nonatomic) UILabel *shareName; // @synthesize shareName=_shareName;
@property(retain, nonatomic) UIImageView *shareIcon; // @synthesize shareIcon=_shareIcon;
@property(retain, nonatomic) UIImageView *groupImage; // @synthesize groupImage=_groupImage;
@property(retain, nonatomic) UILabel *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(retain, nonatomic) UILabel *noPriceLabel; // @synthesize noPriceLabel=_noPriceLabel;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageV; // @synthesize imageV=_imageV;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType codeBlock; // @synthesize codeBlock=_codeBlock;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) SGIdentifyXCodeResp *coderesp; // @synthesize coderesp=_coderesp;
@property(retain, nonatomic) SGScanGoodsQrCodeResp *resp; // @synthesize resp=_resp;
- (void).cxx_destruct;
- (void)addGroupDetail:(id)arg1;
- (void)tapGestureEvent:(id)arg1;
- (void)loadCodeRespData;
- (void)loadRespData;
- (void)viewDidLoad;

@end

