//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@class SGShowDonateResp, UIImageView, UILabel;

@interface SGGoldDonateDetailViewController : SGViewController
{
    _Bool _isSend;
    SGShowDonateResp *_showResp;
    UIImageView *_headImageView;
    UILabel *_moneyLab;
    UILabel *_stateLab;
    UILabel *_timeLab;
    UILabel *_nickLab;
    UILabel *_remarkLab;
    UILabel *_bottomLab;
}

@property(retain, nonatomic) UILabel *bottomLab; // @synthesize bottomLab=_bottomLab;
@property(retain, nonatomic) UILabel *remarkLab; // @synthesize remarkLab=_remarkLab;
@property(retain, nonatomic) UILabel *nickLab; // @synthesize nickLab=_nickLab;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) UILabel *stateLab; // @synthesize stateLab=_stateLab;
@property(retain, nonatomic) UILabel *moneyLab; // @synthesize moneyLab=_moneyLab;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(nonatomic) _Bool isSend; // @synthesize isSend=_isSend;
@property(retain, nonatomic) SGShowDonateResp *showResp; // @synthesize showResp=_showResp;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)refuseClick;
- (void)agreeClick;
- (void)creatChildView;
- (void)viewDidLoad;

@end

