//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class SGGoodsListDataVO, UIImageView, UILabel;

@interface SGGoodsTypeCollectionViewCell : UICollectionViewCell
{
    SGGoodsListDataVO *_model;
    UIImageView *_goodsIconView;
    UILabel *_goodsNameLab;
    UILabel *_priceLab;
    UILabel *_numLab;
    UILabel *_tagsPriceLab;
    UILabel *_activityNameLab;
    UILabel *_advertismentLab;
}

@property(retain, nonatomic) UILabel *advertismentLab; // @synthesize advertismentLab=_advertismentLab;
@property(retain, nonatomic) UILabel *activityNameLab; // @synthesize activityNameLab=_activityNameLab;
@property(retain, nonatomic) UILabel *tagsPriceLab; // @synthesize tagsPriceLab=_tagsPriceLab;
@property(retain, nonatomic) UILabel *numLab; // @synthesize numLab=_numLab;
@property(retain, nonatomic) UILabel *priceLab; // @synthesize priceLab=_priceLab;
@property(retain, nonatomic) UILabel *goodsNameLab; // @synthesize goodsNameLab=_goodsNameLab;
@property(retain, nonatomic) UIImageView *goodsIconView; // @synthesize goodsIconView=_goodsIconView;
@property(retain, nonatomic) SGGoodsListDataVO *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

