//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface SGGoodsDetailCustomBackitemView : UIView
{
    UIImageView *_blackArrowIconView;
    UIImageView *_backIconView;
}

@property(retain, nonatomic) UIImageView *backIconView; // @synthesize backIconView=_backIconView;
@property(retain, nonatomic) UIImageView *blackArrowIconView; // @synthesize blackArrowIconView=_blackArrowIconView;
- (void).cxx_destruct;
- (void)addTarget:(id)arg1 withSelector:(SEL)arg2;
- (void)reloadShowWithAlpha:(double)arg1;
- (void)setRightFirstArrowImage:(id)arg1 withSecondImageName:(id)arg2;
- (void)setLeftFirstArrowImage:(id)arg1 withSecondImageName:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

