//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGInnerObject.h"

@class NSMutableArray;

@interface SGGroupChatMessage : SGInnerObject
{
    long long _groupId;
    long long _userId;
    NSMutableArray *_msgIdList;
}

@property(retain, nonatomic) NSMutableArray *msgIdList; // @synthesize msgIdList=_msgIdList;
@property(nonatomic) long long userId; // @synthesize userId=_userId;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;

@end

