//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@class NSArray, NSString, SGMessage, UIButton, UILabel, VerifyGroupChatInvitationLinkNewResp;

@interface SGGroupInvitationController : SGViewController
{
    _Bool _isInvitedByAdmin;
    _Bool _groupAuthFlag;
    NSArray *_memberArr;
    VerifyGroupChatInvitationLinkNewResp *_respGroupInvite;
    unsigned long long _invitation;
    NSArray *_urlArr;
    NSString *_groupTitle;
    NSString *_invitator;
    long long _num;
    long long _groupUin;
    long long _invitatorUin;
    long long _createTime;
    UIButton *_joinBtn;
    SGMessage *_message;
    UILabel *_promptLabel;
}

+ (_Bool)pushGourpInvitaByErrorCode:(int)arg1 weakvc:(id)arg2 message:(id)arg3 createTime:(long long)arg4;
+ (void)groupInvitationClick:(id)arg1 message:(id)arg2 from:(id)arg3;
@property(retain, nonatomic) UILabel *promptLabel; // @synthesize promptLabel=_promptLabel;
@property(retain, nonatomic) SGMessage *message; // @synthesize message=_message;
@property(retain, nonatomic) UIButton *joinBtn; // @synthesize joinBtn=_joinBtn;
@property(nonatomic) long long createTime; // @synthesize createTime=_createTime;
@property(nonatomic) long long invitatorUin; // @synthesize invitatorUin=_invitatorUin;
@property(nonatomic) long long groupUin; // @synthesize groupUin=_groupUin;
@property(nonatomic) long long num; // @synthesize num=_num;
@property(retain, nonatomic) NSString *invitator; // @synthesize invitator=_invitator;
@property(retain, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(retain, nonatomic) NSArray *urlArr; // @synthesize urlArr=_urlArr;
@property(nonatomic) unsigned long long invitation; // @synthesize invitation=_invitation;
@property(retain, nonatomic) VerifyGroupChatInvitationLinkNewResp *respGroupInvite; // @synthesize respGroupInvite=_respGroupInvite;
@property(retain, nonatomic) NSArray *memberArr; // @synthesize memberArr=_memberArr;
@property(nonatomic) _Bool groupAuthFlag; // @synthesize groupAuthFlag=_groupAuthFlag;
@property(nonatomic) _Bool isInvitedByAdmin; // @synthesize isInvitedByAdmin=_isInvitedByAdmin;
- (void).cxx_destruct;
- (void)joinAfterResp:(id)arg1 errorCode:(int)arg2 errorMessage:(id)arg3;
- (void)joinAction;
- (void)addEnterGroup;
- (void)addClickLinkUrl;
- (void)viewDidLoad;
- (id)initWithInvitationType:(unsigned long long)arg1 withUrlArr:(id)arg2 withGroupTitle:(id)arg3 withGroupMemberTotalOfNum:(long long)arg4 withGroupUin:(long long)arg5 withFromInvitation:(id)arg6 withInvitatorUin:(long long)arg7 withCreatTime:(long long)arg8;

@end

