//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, SGGroupInfo, SGUser, UILabel, UITableView, UIView;

@interface SGGroupAdminViewController : SGViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isEdit;
    SGGroupInfo *_groupInfo;
    CDUnknownBlockType _adminChangeBlock;
    UITableView *_tableView;
    UIView *_footerView;
    NSMutableArray *_adminArray;
    NSMutableArray *_memberArray;
    NSArray *_adminsLoadArray;
    SGUser *_ownerUser;
    UILabel *_noDataLabel;
}

@property(retain, nonatomic) UILabel *noDataLabel; // @synthesize noDataLabel=_noDataLabel;
@property(retain, nonatomic) SGUser *ownerUser; // @synthesize ownerUser=_ownerUser;
@property(retain, nonatomic) NSArray *adminsLoadArray; // @synthesize adminsLoadArray=_adminsLoadArray;
@property(retain, nonatomic) NSMutableArray *memberArray; // @synthesize memberArray=_memberArray;
@property(retain, nonatomic) NSMutableArray *adminArray; // @synthesize adminArray=_adminArray;
@property(nonatomic) _Bool isEdit; // @synthesize isEdit=_isEdit;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) CDUnknownBlockType adminChangeBlock; // @synthesize adminChangeBlock=_adminChangeBlock;
@property(retain, nonatomic) SGGroupInfo *groupInfo; // @synthesize groupInfo=_groupInfo;
- (void).cxx_destruct;
- (void)dealloc;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)cancelAdminClick:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)pushChooseVC;
- (void)editAdmin:(id)arg1;
- (void)reloadTableViewData;
- (void)rightBarHidden;
- (void)initData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

