//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class GoodsDetail, NSString, SGGroupShopShareViewModel, SGViewController;

@interface SGGroupShopShareView : UIView <UIGestureRecognizerDelegate>
{
    SGViewController *_vc;
    UIView *_bgView;
    UIView *_saveView;
    SGGroupShopShareViewModel *_shareModel;
    GoodsDetail *_goods;
    long long _groupId;
}

@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
@property(retain, nonatomic) GoodsDetail *goods; // @synthesize goods=_goods;
@property(retain, nonatomic) SGGroupShopShareViewModel *shareModel; // @synthesize shareModel=_shareModel;
@property(retain, nonatomic) UIView *saveView; // @synthesize saveView=_saveView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) SGViewController *vc; // @synthesize vc=_vc;
- (void).cxx_destruct;
- (void)saveToImage:(id)arg1;
- (void)generateXCodeReq;
- (void)clickAction:(id)arg1;
- (void)cancelAction;
- (void)tapGestureEvent:(id)arg1;
- (void)initSaveView;
- (id)initGroupShopShareWithFrame:(struct CGRect)arg1 withObj:(id)arg2 withGroupId:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

