//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, UIButton, UILabel, UITableView, UIView;

@interface SGGroupImazamoxController : SGViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isOwner;
    int _pagNo;
    int _pagSize;
    int _pagNo1;
    long long _groupId;
    long long _destId;
    UIView *_donateView;
    UITableView *_dataTableView;
    UIView *_buttonView;
    NSMutableArray *_dataSource;
    NSMutableArray *_groupMemberDataSource;
    UIButton *_myImazamoxButton;
    UIButton *_groupmemberImazamoxButton;
    UILabel *_lineLabel;
    NSMutableDictionary *_dataDic;
    NSMutableDictionary *_memberDataDict;
    UILabel *_userGoldenBean;
    UILabel *_allGoldenBean;
    UIView *_noDataView;
    UIView *_navLine;
}

@property(retain, nonatomic) UIView *navLine; // @synthesize navLine=_navLine;
@property(retain, nonatomic) UIView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UILabel *allGoldenBean; // @synthesize allGoldenBean=_allGoldenBean;
@property(retain, nonatomic) UILabel *userGoldenBean; // @synthesize userGoldenBean=_userGoldenBean;
@property(retain, nonatomic) NSMutableDictionary *memberDataDict; // @synthesize memberDataDict=_memberDataDict;
@property(retain, nonatomic) NSMutableDictionary *dataDic; // @synthesize dataDic=_dataDic;
@property(nonatomic) int pagNo1; // @synthesize pagNo1=_pagNo1;
@property(nonatomic) int pagSize; // @synthesize pagSize=_pagSize;
@property(nonatomic) int pagNo; // @synthesize pagNo=_pagNo;
@property(retain, nonatomic) UILabel *lineLabel; // @synthesize lineLabel=_lineLabel;
@property(retain, nonatomic) UIButton *groupmemberImazamoxButton; // @synthesize groupmemberImazamoxButton=_groupmemberImazamoxButton;
@property(retain, nonatomic) UIButton *myImazamoxButton; // @synthesize myImazamoxButton=_myImazamoxButton;
@property(nonatomic) _Bool isOwner; // @synthesize isOwner=_isOwner;
@property(retain, nonatomic) NSMutableArray *groupMemberDataSource; // @synthesize groupMemberDataSource=_groupMemberDataSource;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UIView *buttonView; // @synthesize buttonView=_buttonView;
@property(retain, nonatomic) UITableView *dataTableView; // @synthesize dataTableView=_dataTableView;
@property(retain, nonatomic) UIView *donateView; // @synthesize donateView=_donateView;
@property(nonatomic) long long destId; // @synthesize destId=_destId;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)groupmemberImazamoxButtonClick:(id)arg1;
- (void)changeLineFrameWithButtonClick:(id)arg1;
- (void)myImazamoxButtonClickWithButton:(id)arg1;
- (void)addButtonView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)loadData;
- (void)showNoDataView:(_Bool)arg1;
- (void)loadFirstData;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithGroupId:(long long)arg1 destId:(long long)arg2 isOwner:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

