//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface SGGroupChatManager : NSObject
{
    NSMutableArray *_groupChats;
}

+ (id)sharedGroupChatManager;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSMutableArray *groupChats; // @synthesize groupChats=_groupChats;
- (void).cxx_destruct;
- (id)selectGroupChat;
- (id)selectGroupChatWithGroupId:(long long)arg1;
- (void)updateGroupChat:(id)arg1;
- (void)deleteGroupChatWithGroupId:(long long)arg1;
- (id)init;
- (void)clearGroupChat;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

