//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SGGroupCardShopModel : NSObject
{
    _Bool _thirdFlag;
    _Bool _selfDefinedFlag;
    _Bool _isKillDiscountGoods;
    long long _goodsId;
    NSString *_goodsName;
    NSString *_goodsSmallPhotoUrl;
    long long _goldenbeanNum;
    NSString *_h5Url;
    long long _origPrice;
    long long _tagPrice;
    long long _minSalePrice;
    long long _minGroupbuyPrice;
    long long _totalSoldNumber;
    NSString *_goodsDetailToken;
    long long _groupId;
    long long _activityId;
    long long _beginTime;
    NSString *_goodsQrCodeString;
    long long _qrCodeExpireTime;
    NSArray *_goodsPhotoUrlList;
    long long _promoActivityId;
    NSString *_activityPriceName;
    NSString *_groupbuyPriceAlias;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *groupbuyPriceAlias; // @synthesize groupbuyPriceAlias=_groupbuyPriceAlias;
@property(copy, nonatomic) NSString *activityPriceName; // @synthesize activityPriceName=_activityPriceName;
@property(nonatomic) long long promoActivityId; // @synthesize promoActivityId=_promoActivityId;
@property(retain, nonatomic) NSArray *goodsPhotoUrlList; // @synthesize goodsPhotoUrlList=_goodsPhotoUrlList;
@property(nonatomic) long long qrCodeExpireTime; // @synthesize qrCodeExpireTime=_qrCodeExpireTime;
@property(copy, nonatomic) NSString *goodsQrCodeString; // @synthesize goodsQrCodeString=_goodsQrCodeString;
@property(nonatomic) long long beginTime; // @synthesize beginTime=_beginTime;
@property(nonatomic) long long activityId; // @synthesize activityId=_activityId;
@property(nonatomic) _Bool isKillDiscountGoods; // @synthesize isKillDiscountGoods=_isKillDiscountGoods;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
@property(copy, nonatomic) NSString *goodsDetailToken; // @synthesize goodsDetailToken=_goodsDetailToken;
@property(nonatomic) _Bool selfDefinedFlag; // @synthesize selfDefinedFlag=_selfDefinedFlag;
@property(nonatomic) long long totalSoldNumber; // @synthesize totalSoldNumber=_totalSoldNumber;
@property(nonatomic) long long minGroupbuyPrice; // @synthesize minGroupbuyPrice=_minGroupbuyPrice;
@property(nonatomic) long long minSalePrice; // @synthesize minSalePrice=_minSalePrice;
@property(nonatomic) long long tagPrice; // @synthesize tagPrice=_tagPrice;
@property(nonatomic) long long origPrice; // @synthesize origPrice=_origPrice;
@property(copy, nonatomic) NSString *h5Url; // @synthesize h5Url=_h5Url;
@property(nonatomic) long long goldenbeanNum; // @synthesize goldenbeanNum=_goldenbeanNum;
@property(nonatomic) _Bool thirdFlag; // @synthesize thirdFlag=_thirdFlag;
@property(copy, nonatomic) NSString *goodsSmallPhotoUrl; // @synthesize goodsSmallPhotoUrl=_goodsSmallPhotoUrl;
@property(copy, nonatomic) NSString *goodsName; // @synthesize goodsName=_goodsName;
@property(nonatomic) long long goodsId; // @synthesize goodsId=_goodsId;
- (void).cxx_destruct;

@end

