//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSAttributedString, NSMutableAttributedString, SGGroupShopShareViewModel;

@interface SGGroupShopShareCellModel : SGDialogDetailCellModel
{
    NSAttributedString *_topAttributeStr;
    NSAttributedString *_titleAttributeStr;
    NSAttributedString *_activityAttributeStr;
    NSAttributedString *_goldAttributeStr;
    NSMutableAttributedString *_rmbAttributeStr;
    NSMutableAttributedString *_showTextAttributeStr;
    NSMutableAttributedString *_shopAttributeStr;
    NSMutableAttributedString *_tatPriceAttributeStr;
    SGGroupShopShareViewModel *_shopModel;
    struct CGRect _topTextFrame;
    struct CGRect _topIconFrame;
    struct CGRect _titleFrame;
    struct CGRect _linelFrame;
    struct CGRect _showTextFrame;
    struct CGRect _bottomShopFrame;
    struct CGRect _rmbFrame;
    struct CGRect _targetPriceFrame;
    struct CGRect _targetPriceLinelFrame;
    struct CGRect _goldFrame;
    struct CGRect _officeButtonFrame;
    struct CGRect _goodIconFrame;
    struct CGRect _activityNameFrame;
}

@property(retain, nonatomic) SGGroupShopShareViewModel *shopModel; // @synthesize shopModel=_shopModel;
@property(nonatomic) struct CGRect activityNameFrame; // @synthesize activityNameFrame=_activityNameFrame;
@property(nonatomic) struct CGRect goodIconFrame; // @synthesize goodIconFrame=_goodIconFrame;
@property(nonatomic) struct CGRect officeButtonFrame; // @synthesize officeButtonFrame=_officeButtonFrame;
@property(nonatomic) struct CGRect goldFrame; // @synthesize goldFrame=_goldFrame;
@property(nonatomic) struct CGRect targetPriceLinelFrame; // @synthesize targetPriceLinelFrame=_targetPriceLinelFrame;
@property(nonatomic) struct CGRect targetPriceFrame; // @synthesize targetPriceFrame=_targetPriceFrame;
@property(nonatomic) struct CGRect rmbFrame; // @synthesize rmbFrame=_rmbFrame;
@property(nonatomic) struct CGRect bottomShopFrame; // @synthesize bottomShopFrame=_bottomShopFrame;
@property(nonatomic) struct CGRect showTextFrame; // @synthesize showTextFrame=_showTextFrame;
@property(nonatomic) struct CGRect linelFrame; // @synthesize linelFrame=_linelFrame;
@property(nonatomic) struct CGRect titleFrame; // @synthesize titleFrame=_titleFrame;
@property(nonatomic) struct CGRect topIconFrame; // @synthesize topIconFrame=_topIconFrame;
@property(nonatomic) struct CGRect topTextFrame; // @synthesize topTextFrame=_topTextFrame;
@property(retain, nonatomic) NSMutableAttributedString *tatPriceAttributeStr; // @synthesize tatPriceAttributeStr=_tatPriceAttributeStr;
@property(retain, nonatomic) NSMutableAttributedString *shopAttributeStr; // @synthesize shopAttributeStr=_shopAttributeStr;
@property(retain, nonatomic) NSMutableAttributedString *showTextAttributeStr; // @synthesize showTextAttributeStr=_showTextAttributeStr;
@property(retain, nonatomic) NSMutableAttributedString *rmbAttributeStr; // @synthesize rmbAttributeStr=_rmbAttributeStr;
@property(copy, nonatomic) NSAttributedString *goldAttributeStr; // @synthesize goldAttributeStr=_goldAttributeStr;
@property(copy, nonatomic) NSAttributedString *activityAttributeStr; // @synthesize activityAttributeStr=_activityAttributeStr;
@property(copy, nonatomic) NSAttributedString *titleAttributeStr; // @synthesize titleAttributeStr=_titleAttributeStr;
@property(copy, nonatomic) NSAttributedString *topAttributeStr; // @synthesize topAttributeStr=_topAttributeStr;
- (void).cxx_destruct;
- (Class)getCellClass;
- (id)getMessageAttributedStringWithText:(id)arg1 font:(id)arg2;
- (id)getMessageAttributedStringWithText:(id)arg1 contentColor:(id)arg2 font:(id)arg3;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

