//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface SGGroupMemberTagManager : NSObject
{
    NSMutableDictionary *_memberTagInfoDic;
}

+ (id)sharedGroupMemberTagManager;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSMutableDictionary *memberTagInfoDic; // @synthesize memberTagInfoDic=_memberTagInfoDic;
- (void).cxx_destruct;
- (void)deleteGroupMemberTagInfoWithGroupId:(long long)arg1 destUserId:(long long)arg2 memberTagInfo:(id)arg3;
- (void)addGroupMemberTagInfoWithGroupId:(long long)arg1 destUserId:(long long)arg2 memberTagInfo:(id)arg3;
- (id)queryMemberTagWithGroupId:(long long)arg1 destUserId:(long long)arg2;
- (void)updateGroupMemberTagInfoWithGroupId:(long long)arg1 destUin:(long long)arg2 WithTagArray:(id)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

