//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SGGuideView : UIView
{
    CDUnknownBlockType _cancel;
    CDUnknownBlockType _next;
}

+ (id)initWithType:(unsigned long long)arg1 cancelBlock:(CDUnknownBlockType)arg2 nextBlock:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType next; // @synthesize next=_next;
@property(copy, nonatomic) CDUnknownBlockType cancel; // @synthesize cancel=_cancel;
- (void).cxx_destruct;
- (void)clearAction;
- (void)disAppear;
- (void)nextClick;
- (void)cancelClick;
- (void)didMoveToSuperview;
- (id)buttonWith:(struct CGRect)arg1 action:(SEL)arg2 title:(id)arg3 color:(id)arg4;
- (id)nextButtonWithFrame:(struct CGRect)arg1 titile:(id)arg2;
- (id)cancelButtonWithFrame:(struct CGRect)arg1 titile:(id)arg2;
- (id)crateLabelWith:(id)arg1 frame:(struct CGRect)arg2;
- (void)addParagraph:(id)arg1;
- (id)titleString:(id)arg1;
- (id)detailTwoSectionPreString:(id)arg1 sufString:(id)arg2;
- (id)addLabelBackView:(id)arg1 top:(double)arg2 bottom:(_Bool)arg3;
- (id)addArrow:(id)arg1;

@end

