//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSString;

@interface SGH5QrDepositResp : SGHTTPSResponseModel
{
    NSString *_qrCode;
    NSString *_aliPayURL;
    long long _depositId;
}

+ (int)constructor;
@property(nonatomic) long long depositId; // @synthesize depositId=_depositId;
@property(copy, nonatomic) NSString *aliPayURL; // @synthesize aliPayURL=_aliPayURL;
@property(copy, nonatomic) NSString *qrCode; // @synthesize qrCode=_qrCode;
- (void).cxx_destruct;

@end

