//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class UIImageView, UILabel;

@interface SGHelperTableViewController : UITableViewController
{
    int _type;
    UIImageView *_icon;
    UILabel *_xianliaoAsistant;
    UILabel *_functionIntroduction;
    UILabel *_functionContent;
}

@property(nonatomic) __weak UILabel *functionContent; // @synthesize functionContent=_functionContent;
@property(nonatomic) __weak UILabel *functionIntroduction; // @synthesize functionIntroduction=_functionIntroduction;
@property(nonatomic) __weak UILabel *xianliaoAsistant; // @synthesize xianliaoAsistant=_xianliaoAsistant;
@property(nonatomic) __weak UIImageView *icon; // @synthesize icon=_icon;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

