//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class SGHomeSecondkillTimeView, SGIndexSpikeGoodsVO, SGTopIconButton, UIButton, UIImageView, UILabel, UIView;
@protocol HomeGoodSecondKillDelegate;

@interface SGHomeGoodSecondKillCell : UICollectionViewCell
{
    SGIndexSpikeGoodsVO *_model;
    long long _serverTime;
    id <HomeGoodSecondKillDelegate> _cellDelegate;
    UIImageView *_goodsIconView;
    UILabel *_goodsNameLab;
    UILabel *_goodNumberLab;
    UILabel *_goodPriceLab;
    UILabel *_orignPriceLab;
    UIImageView *_clockImageView;
    UILabel *_waitTimeLab;
    UIButton *_rewindButton;
    SGHomeSecondkillTimeView *_timeView;
    UILabel *_totalNumLab;
    UIView *_progressView;
    UIView *_bkgProgressView;
    SGTopIconButton *_buyButton;
    UIImageView *_soldOutView;
}

@property(retain, nonatomic) UIImageView *soldOutView; // @synthesize soldOutView=_soldOutView;
@property(retain, nonatomic) SGTopIconButton *buyButton; // @synthesize buyButton=_buyButton;
@property(retain, nonatomic) UIView *bkgProgressView; // @synthesize bkgProgressView=_bkgProgressView;
@property(retain, nonatomic) UIView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *totalNumLab; // @synthesize totalNumLab=_totalNumLab;
@property(retain, nonatomic) SGHomeSecondkillTimeView *timeView; // @synthesize timeView=_timeView;
@property(retain, nonatomic) UIButton *rewindButton; // @synthesize rewindButton=_rewindButton;
@property(retain, nonatomic) UILabel *waitTimeLab; // @synthesize waitTimeLab=_waitTimeLab;
@property(retain, nonatomic) UIImageView *clockImageView; // @synthesize clockImageView=_clockImageView;
@property(retain, nonatomic) UILabel *orignPriceLab; // @synthesize orignPriceLab=_orignPriceLab;
@property(retain, nonatomic) UILabel *goodPriceLab; // @synthesize goodPriceLab=_goodPriceLab;
@property(retain, nonatomic) UILabel *goodNumberLab; // @synthesize goodNumberLab=_goodNumberLab;
@property(retain, nonatomic) UILabel *goodsNameLab; // @synthesize goodsNameLab=_goodsNameLab;
@property(retain, nonatomic) UIImageView *goodsIconView; // @synthesize goodsIconView=_goodsIconView;
@property(nonatomic) __weak id <HomeGoodSecondKillDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(nonatomic) long long serverTime; // @synthesize serverTime=_serverTime;
@property(retain, nonatomic) SGIndexSpikeGoodsVO *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)rewaindButtonClick:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

