//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface SGHomeSecondkillTimeView : UIView
{
    UILabel *_secondLab;
    UILabel *_minuteLab;
    UILabel *_hourLab;
}

@property(retain, nonatomic) UILabel *hourLab; // @synthesize hourLab=_hourLab;
@property(retain, nonatomic) UILabel *minuteLab; // @synthesize minuteLab=_minuteLab;
@property(retain, nonatomic) UILabel *secondLab; // @synthesize secondLab=_secondLab;
- (void).cxx_destruct;
- (void)setCountDownTime:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

