//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSString, SGInterstSystemNoticeModel;

@interface SGInterstSystemNoticeCellModel : SGDialogDetailCellModel
{
    SGInterstSystemNoticeModel *_model;
    NSString *_noticeTitle;
    NSString *_noticeTime;
    NSString *_noticeContent;
    NSString *_noticeJumpDesc;
    struct CGRect _noticeTitleFrame;
    struct CGRect _noticeTimeFrame;
    struct CGRect _noticeContentFrame;
    struct CGRect _lineFrame;
    struct CGRect _bottomtextFrame;
}

@property(nonatomic) struct CGRect bottomtextFrame; // @synthesize bottomtextFrame=_bottomtextFrame;
@property(nonatomic) struct CGRect lineFrame; // @synthesize lineFrame=_lineFrame;
@property(nonatomic) struct CGRect noticeContentFrame; // @synthesize noticeContentFrame=_noticeContentFrame;
@property(nonatomic) struct CGRect noticeTimeFrame; // @synthesize noticeTimeFrame=_noticeTimeFrame;
@property(nonatomic) struct CGRect noticeTitleFrame; // @synthesize noticeTitleFrame=_noticeTitleFrame;
@property(copy, nonatomic) NSString *noticeJumpDesc; // @synthesize noticeJumpDesc=_noticeJumpDesc;
@property(copy, nonatomic) NSString *noticeContent; // @synthesize noticeContent=_noticeContent;
@property(copy, nonatomic) NSString *noticeTime; // @synthesize noticeTime=_noticeTime;
@property(copy, nonatomic) NSString *noticeTitle; // @synthesize noticeTitle=_noticeTitle;
@property(retain, nonatomic) SGInterstSystemNoticeModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (Class)getCellClass;
- (struct CGSize)getSizeBy:(id)arg1 strFont:(double)arg2 maxSize:(struct CGSize)arg3;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

