//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

@class UILabel, UIView;

@interface SGInterstSystemNoticeCell : SGDialogDeatilBaseCell
{
    UILabel *_noticeTitleLab;
    UILabel *_noticeTimeLab;
    UILabel *_noticeContentLab;
    UIView *_lineView;
    UILabel *_bottomTextLab;
    UIView *_whiteView;
}

@property(nonatomic) __weak UIView *whiteView; // @synthesize whiteView=_whiteView;
@property(nonatomic) __weak UILabel *bottomTextLab; // @synthesize bottomTextLab=_bottomTextLab;
@property(nonatomic) __weak UIView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) __weak UILabel *noticeContentLab; // @synthesize noticeContentLab=_noticeContentLab;
@property(nonatomic) __weak UILabel *noticeTimeLab; // @synthesize noticeTimeLab=_noticeTimeLab;
@property(nonatomic) __weak UILabel *noticeTitleLab; // @synthesize noticeTitleLab=_noticeTitleLab;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)awakeFromNib;

@end

