//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class InterestTribeType, UIImageView, UILabel;

@interface SGInterstCategoryCell : UITableViewCell
{
    _Bool _isSelectInterst;
    InterestTribeType *_model;
    UIImageView *_logoImageView;
    UILabel *_nameLabel;
    UIImageView *_selectIconView;
}

@property(retain, nonatomic) UIImageView *selectIconView; // @synthesize selectIconView=_selectIconView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(nonatomic) _Bool isSelectInterst; // @synthesize isSelectInterst=_isSelectInterst;
@property(retain, nonatomic) InterestTribeType *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)creatChildView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

