//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel;

@interface SGItemCell : UICollectionViewCell
{
    _Bool _isMemoryWarning;
    _Bool _isOwner;
    int _cellType;
    UIImageView *_image;
    UILabel *_textLab;
    UILabel *_adminLabel;
}

@property(nonatomic) _Bool isOwner; // @synthesize isOwner=_isOwner;
@property(retain, nonatomic) UILabel *adminLabel; // @synthesize adminLabel=_adminLabel;
@property(retain, nonatomic) UILabel *textLab; // @synthesize textLab=_textLab;
@property(retain, nonatomic) UIImageView *image; // @synthesize image=_image;
@property(nonatomic) int cellType; // @synthesize cellType=_cellType;
@property(nonatomic) _Bool isMemoryWarning; // @synthesize isMemoryWarning=_isMemoryWarning;
- (void).cxx_destruct;
- (void)setImageURL:(id)arg1 withText:(id)arg2 withUin:(long long)arg3;
- (void)setImageURL:(id)arg1 withText:(id)arg2 withUin:(long long)arg3 withAdminLabelHidden:(_Bool)arg4 withOwner:(_Bool)arg5;
- (id)initWithFrame:(struct CGRect)arg1;

@end

