//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGJirmRedPacket : NSObject
{
    unsigned char _category;
    unsigned char _groupFlag;
    unsigned char _state;
    long long _packetSendTime;
    NSString *_redPacketId;
    long long _senderId;
    long long _destId;
    NSString *_redPacketName;
    NSString *_blessing;
}

@property(nonatomic) unsigned char state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *blessing; // @synthesize blessing=_blessing;
@property(copy, nonatomic) NSString *redPacketName; // @synthesize redPacketName=_redPacketName;
@property(nonatomic) unsigned char groupFlag; // @synthesize groupFlag=_groupFlag;
@property(nonatomic) long long destId; // @synthesize destId=_destId;
@property(nonatomic) long long senderId; // @synthesize senderId=_senderId;
@property(nonatomic) unsigned char category; // @synthesize category=_category;
@property(copy, nonatomic) NSString *redPacketId; // @synthesize redPacketId=_redPacketId;
@property(nonatomic) long long packetSendTime; // @synthesize packetSendTime=_packetSendTime;
- (void).cxx_destruct;

@end

