//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSMutableAttributedString, SGJirmRedPacket;

@interface SGJirmRedPacketCellModel : SGDialogDetailCellModel
{
    NSMutableAttributedString *_blessAttributeStr;
    NSMutableAttributedString *_contentAttributeStr;
    NSMutableAttributedString *_descriptionAttributeStr;
    SGJirmRedPacket *_redPacketModel;
    struct CGRect _redPacketImageFrame;
    struct CGRect _blessLabelFrame;
    struct CGRect _contentLabelFrame;
    struct CGRect _descriptionLabelFrame;
    struct CGRect _whiteBackViewFrame;
}

@property(retain, nonatomic) SGJirmRedPacket *redPacketModel; // @synthesize redPacketModel=_redPacketModel;
@property(nonatomic) struct CGRect whiteBackViewFrame; // @synthesize whiteBackViewFrame=_whiteBackViewFrame;
@property(nonatomic) struct CGRect descriptionLabelFrame; // @synthesize descriptionLabelFrame=_descriptionLabelFrame;
@property(nonatomic) struct CGRect contentLabelFrame; // @synthesize contentLabelFrame=_contentLabelFrame;
@property(nonatomic) struct CGRect blessLabelFrame; // @synthesize blessLabelFrame=_blessLabelFrame;
@property(nonatomic) struct CGRect redPacketImageFrame; // @synthesize redPacketImageFrame=_redPacketImageFrame;
@property(retain, nonatomic) NSMutableAttributedString *descriptionAttributeStr; // @synthesize descriptionAttributeStr=_descriptionAttributeStr;
@property(retain, nonatomic) NSMutableAttributedString *contentAttributeStr; // @synthesize contentAttributeStr=_contentAttributeStr;
@property(retain, nonatomic) NSMutableAttributedString *blessAttributeStr; // @synthesize blessAttributeStr=_blessAttributeStr;
- (void).cxx_destruct;
- (void)refershModelRedPacketDict;
- (Class)getCellClass;
- (id)getMessageAttributedString:(id)arg1 paragraph:(_Bool)arg2 font:(id)arg3 color:(id)arg4 reply:(_Bool)arg5 urlDicBlock:(CDUnknownBlockType)arg6;
- (id)getMessageAttributedStringWithText:(id)arg1 font:(id)arg2;
- (void)calculateSubView;
- (void)messageTextWithDict;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

