//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@interface SGJoinGroupChatByCouponInvitationLinkReq : SGHTTPSReqModel
{
    int _channel;
    long long _groupId;
    long long _invitedFromUid;
    long long _sendId;
    long long _templateId;
}

@property(nonatomic) long long templateId; // @synthesize templateId=_templateId;
@property(nonatomic) long long sendId; // @synthesize sendId=_sendId;
@property(nonatomic) int channel; // @synthesize channel=_channel;
@property(nonatomic) long long invitedFromUid; // @synthesize invitedFromUid=_invitedFromUid;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (int)constructor;

@end

