//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGJrmfGroupOpenNoticeModel : NSObject
{
    _Bool _lastPacketFlag;
    long long _groupId;
    long long _senderUid;
    long long _receiverUid;
    NSString *_redPacketId;
    NSString *_senderNickName;
    NSString *_receiverNickName;
}

@property(nonatomic) _Bool lastPacketFlag; // @synthesize lastPacketFlag=_lastPacketFlag;
@property(copy, nonatomic) NSString *receiverNickName; // @synthesize receiverNickName=_receiverNickName;
@property(copy, nonatomic) NSString *senderNickName; // @synthesize senderNickName=_senderNickName;
@property(copy, nonatomic) NSString *redPacketId; // @synthesize redPacketId=_redPacketId;
@property(nonatomic) long long receiverUid; // @synthesize receiverUid=_receiverUid;
@property(nonatomic) long long senderUid; // @synthesize senderUid=_senderUid;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;
- (id)getActionText;

@end

