//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, UIButton, UILabel, UITableView, UIView;

@interface SGLeaveGroupChatListController : SGViewController <UITableViewDataSource, UITableViewDelegate>
{
    int _pageNo;
    NSArray *_keys;
    NSDictionary *_friendsDic;
    NSArray *_searchArr;
    NSMutableArray *_chooseArr;
    UITableView *_contactsTableView;
    UILabel *_groupmemberOverTips;
    UIButton *_nextBtn;
    NSArray *_groupMember;
    NSMutableArray *_friendsArray;
    UIView *_footView;
    UILabel *_tipsLabel;
    long long _groupId;
    UIView *_emptyView;
}

@property(retain, nonatomic) UIView *emptyView; // @synthesize emptyView=_emptyView;
@property(nonatomic) int pageNo; // @synthesize pageNo=_pageNo;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UIView *footView; // @synthesize footView=_footView;
@property(retain, nonatomic) NSMutableArray *friendsArray; // @synthesize friendsArray=_friendsArray;
@property(retain, nonatomic) NSArray *groupMember; // @synthesize groupMember=_groupMember;
@property(retain, nonatomic) UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(retain, nonatomic) UILabel *groupmemberOverTips; // @synthesize groupmemberOverTips=_groupmemberOverTips;
@property(retain, nonatomic) UITableView *contactsTableView; // @synthesize contactsTableView=_contactsTableView;
@property(retain, nonatomic) NSMutableArray *chooseArr; // @synthesize chooseArr=_chooseArr;
@property(retain, nonatomic) NSArray *searchArr; // @synthesize searchArr=_searchArr;
@property(retain, nonatomic) NSDictionary *friendsDic; // @synthesize friendsDic=_friendsDic;
@property(retain, nonatomic) NSArray *keys; // @synthesize keys=_keys;
- (void).cxx_destruct;
- (void)backNavgation;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (void)filterFriends:(id)arg1 admindsArr:(id)arg2;
- (void)loadData;
- (void)dealloc;
- (void)setNavBar;
- (void)viewDidLoad;
- (id)initWithGroupId:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

