//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, SGButton, UILabel, UITextField;

@interface SGLoginController : SGViewController <UITextFieldDelegate>
{
    UILabel *_countryCodeLab;
    UITextField *_phoneTF;
    UITextField *_passwordTF;
    UILabel *_errorLab;
    SGButton *_nextButton;
    NSString *_countryCode;
}

@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(retain, nonatomic) SGButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) UILabel *errorLab; // @synthesize errorLab=_errorLab;
@property(retain, nonatomic) UITextField *passwordTF; // @synthesize passwordTF=_passwordTF;
@property(retain, nonatomic) UITextField *phoneTF; // @synthesize phoneTF=_phoneTF;
@property(retain, nonatomic) UILabel *countryCodeLab; // @synthesize countryCodeLab=_countryCodeLab;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)chooseCountryAction;
- (void)forgetAction;
- (void)codeLoginAction;
- (void)signUpAction;
- (void)nextAction;
- (void)myEndEditing;
- (void)textFieldDidChange:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)initView;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)initData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

