//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UISearchControllerDelegate-Protocol.h"
#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, UILabel, UISearchController, UITableView, UIView;

@interface SGMatchFriendsController : SGViewController <UITableViewDelegate, UITableViewDataSource, UISearchControllerDelegate, UISearchResultsUpdating>
{
    _Bool _isRejectedAuth;
    _Bool _isSearch;
    NSMutableArray *_internalArr;
    NSArray *_searchResultArr;
    UITableView *_tableView;
    UIView *_noDataView;
    UILabel *_noDataLab;
    UISearchController *_searchController;
    NSDictionary *_addressBookDict;
    NSArray *_keys;
    UILabel *_userNumLab;
}

@property(nonatomic) _Bool isSearch; // @synthesize isSearch=_isSearch;
@property(retain, nonatomic) UILabel *userNumLab; // @synthesize userNumLab=_userNumLab;
@property(retain, nonatomic) NSArray *keys; // @synthesize keys=_keys;
@property(retain, nonatomic) NSDictionary *addressBookDict; // @synthesize addressBookDict=_addressBookDict;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) __weak UILabel *noDataLab; // @synthesize noDataLab=_noDataLab;
@property(retain, nonatomic) UIView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSArray *searchResultArr; // @synthesize searchResultArr=_searchResultArr;
@property(retain, nonatomic) NSMutableArray *internalArr; // @synthesize internalArr=_internalArr;
@property(nonatomic) _Bool isRejectedAuth; // @synthesize isRejectedAuth=_isRejectedAuth;
- (void).cxx_destruct;
- (void)matchFriendsCellAddActionIndexPath:(id)arg1;
- (void)relaodSearchData;
- (void)willDismissSearchController:(id)arg1;
- (void)willPresentSearchController:(id)arg1;
- (void)sgSearchText:(id)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)refreshData;
- (void)matchContactsList;
- (void)goSetAction;
- (void)getUserNumView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

