//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGMangerKeyWordModel : NSObject
{
    NSString *_partnerUrl;
    NSString *_groupTitle;
    NSString *_sign;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *sign; // @synthesize sign=_sign;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(copy, nonatomic) NSString *partnerUrl; // @synthesize partnerUrl=_partnerUrl;
- (void).cxx_destruct;

@end

