//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SGMessageOrder : NSObject
{
}

+ (_Bool)isCheckRecognitionMediaconstructor:(int)arg1;
+ (id)getLayOutNotificationOrder;
+ (_Bool)isShowJumpSharingAttributeMediaController:(int)arg1;
+ (_Bool)isShowJumpAttributeMediaController:(int)arg1;
+ (_Bool)isNeedLayOutNotificationOrder:(int)arg1;
+ (_Bool)isExistNotificationOrder:(int)arg1;
+ (_Bool)isExistWithOrder:(int)arg1;
+ (_Bool)isExistorderNeedImage:(int)arg1;
+ (_Bool)isCheckOrderMediaConstructor:(int)arg1;
+ (_Bool)isNeedCalcutUnreadMessageOrder:(int)arg1;
+ (void)initialize;

@end

