//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGMergerMessageBaseCell.h"

@class SGMergerMessageDetailModel, UIImageView, UILabel;
@protocol MergerShopCellDelegate;

@interface SGMergerShopCell : SGMergerMessageBaseCell
{
    SGMergerMessageDetailModel *_model;
    id <MergerShopCellDelegate> _cellDelegate;
    UILabel *_rmbLab;
    UILabel *_coinLab;
    UILabel *_titleLab;
    UIImageView *_goodIconView;
}

@property(retain, nonatomic) UIImageView *goodIconView; // @synthesize goodIconView=_goodIconView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UILabel *coinLab; // @synthesize coinLab=_coinLab;
@property(retain, nonatomic) UILabel *rmbLab; // @synthesize rmbLab=_rmbLab;
@property(nonatomic) __weak id <MergerShopCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(retain, nonatomic) SGMergerMessageDetailModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setData:(id)arg1;
- (void)tapWhiteBkgView:(id)arg1;
- (void)setChildView;

@end

