//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGMessageBoardInfoVO : NSObject
{
    long long _messageId;
    NSString *_messageBoard;
    NSString *_descAlias;
}

@property(copy, nonatomic) NSString *descAlias; // @synthesize descAlias=_descAlias;
@property(copy, nonatomic) NSString *messageBoard; // @synthesize messageBoard=_messageBoard;
@property(nonatomic) long long messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;

@end

