//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGMergerMessageBaseCell.h"

@class SGCombatListView, SGMergerMessageDetailModel, UIImageView, UILabel, UIView;
@protocol MergerCombatCelDelegate;

@interface SGMergerCombatCell : SGMergerMessageBaseCell
{
    SGMergerMessageDetailModel *_model;
    id <MergerCombatCelDelegate> _cellDelegate;
    UILabel *_titleLabel;
    UILabel *_lightTitleLabel;
    UIView *_topLineView;
    UIImageView *_gameImageView;
    UILabel *_gameNameLabel;
    SGCombatListView *_combatListView;
    UIView *_whiteView;
}

@property(retain, nonatomic) UIView *whiteView; // @synthesize whiteView=_whiteView;
@property(retain, nonatomic) SGCombatListView *combatListView; // @synthesize combatListView=_combatListView;
@property(retain, nonatomic) UILabel *gameNameLabel; // @synthesize gameNameLabel=_gameNameLabel;
@property(retain, nonatomic) UIImageView *gameImageView; // @synthesize gameImageView=_gameImageView;
@property(retain, nonatomic) UIView *topLineView; // @synthesize topLineView=_topLineView;
@property(retain, nonatomic) UILabel *lightTitleLabel; // @synthesize lightTitleLabel=_lightTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <MergerCombatCelDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(retain, nonatomic) SGMergerMessageDetailModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)tapWhiteView;
- (void)setChildView;

@end

