//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, SGMessage, SGModernButton, UIImageView, UILabel;
@protocol SGModernConversationAssociatePanelDelegate;

@interface SGModernConversationAssociatedPanel : UIView
{
    _Bool _isForward;
    _Bool _isReply;
    id <SGModernConversationAssociatePanelDelegate> _delegate;
    NSString *_authorName;
    NSString *_messageText;
    SGMessage *_message;
    UIView *_lineView;
    UILabel *_authorNameLabel;
    UILabel *_messageTextLabel;
    UIImageView *_messageAssociateView;
    UIImageView *_messageContentImageView;
    SGModernButton *_cancelButton;
}

@property(retain, nonatomic) SGModernButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIImageView *messageContentImageView; // @synthesize messageContentImageView=_messageContentImageView;
@property(retain, nonatomic) UIImageView *messageAssociateView; // @synthesize messageAssociateView=_messageAssociateView;
@property(retain, nonatomic) UILabel *messageTextLabel; // @synthesize messageTextLabel=_messageTextLabel;
@property(retain, nonatomic) UILabel *authorNameLabel; // @synthesize authorNameLabel=_authorNameLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) SGMessage *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *messageText; // @synthesize messageText=_messageText;
@property(retain, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(nonatomic) _Bool isReply; // @synthesize isReply=_isReply;
@property(nonatomic) _Bool isForward; // @synthesize isForward=_isForward;
@property(nonatomic) __weak id <SGModernConversationAssociatePanelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)cancelButton:(id)arg1;
- (void)setPanelMessage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

