//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "AGEmojiKeyboardViewDataSource-Protocol.h"
#import "AGEmojiKeyboardViewDelegate-Protocol.h"
#import "ASWatcher-Protocol.h"
#import "HPGrowingTextViewDelegate-Protocol.h"
#import "SGAddActionClickDelegate-Protocol.h"
#import "SGModernConversationAssociatePanelDelegate-Protocol.h"

@class AGEmojiKeyboardView, ASHandle, CALayer, HPGrowingTextView, NSArray, NSString, NSTimer, SGAddActionView, SGDialogs, SGGroupInfo, SGModernButton, SGModernConversationAssociatedPanel, UIActivityIndicatorView, UIButton, UIEvent, UIImageView, UILabel, UIMenuItem, UIViewController;
@protocol SGModernConversationInputTextPanelDelegate;

@interface SGModernConversationInputTextPanel : UIView <HPGrowingTextViewDelegate, SGModernConversationAssociatePanelDelegate, ASWatcher, AGEmojiKeyboardViewDataSource, AGEmojiKeyboardViewDelegate, SGAddActionClickDelegate>
{
    CALayer *_stripeLayer;
    UIView *_backgroundView;
    double _sendButtonWidth;
    UIImageView *_micButtonIconView;
    UIEvent *recordEvent;
    UIView *_audioRecordingContainer;
    unsigned long long _audioRecordingDurationSeconds;
    unsigned long long _audioRecordingDurationMilliseconds;
    NSTimer *_audioRecordingTimer;
    UIImageView *_recordIndicatorView;
    UILabel *_recordDurationLabel;
    UIImageView *_slideToCancelArrow;
    UILabel *_slideToCancelLabel;
    double _recordingInterfaceShowTime;
    SGModernButton *_keyboardModeButton;
    SGModernButton *_stickerModeButton;
    SGModernButton *_commandModeButton;
    SGModernButton *_broadcastButton;
    SGModernButton *_progressButton;
    SGModernButton *_emotionButton;
    UIActivityIndicatorView *_progressButtonIndicator;
    NSArray *_modeButtons;
    _Bool _shouldShowKeyboardAutomatically;
    UIView *_overlayDisabledView;
    struct CGSize _parentSize;
    _Bool _removeGifTabTextOnDeactivation;
    UILabel *_contextPlaceholderLabel;
    _Bool _recording;
    _Bool _messageEditingContextInvalidated;
    int fieldTextLength;
    _Bool _changingKeyboardMode;
    _Bool _enableKeyboard;
    _Bool _canShowKeyboardAutomatically;
    _Bool _isBeDelete;
    _Bool _hasBots;
    _Bool _inputDisabled;
    _Bool _displayProgress;
    _Bool _isAddsociateHeight;
    _Bool _isAssociatePanel;
    _Bool _recordPermissionGranted;
    _Bool _setOriginalInputTextFieldHeight;
    UIImageView *_fieldBackground;
    UIButton *_attachButton;
    SGAddActionView *_addView;
    UIButton *_micButton;
    UIButton *_recordButton;
    UIButton *_keyboardButton;
    ASHandle *_actionHandle;
    UIView *_inputFieldClippingContainer;
    HPGrowingTextView *_inputField;
    UIImageView *_inputFieldPlaceholder;
    NSString *_contextPlaceholder;
    UIView *_panelAccessoryView;
    SGModernConversationAssociatedPanel *_associatePanel;
    long long _conversationId;
    double _touchDownTime;
    CDUnknownBlockType _block;
    UIViewController *_weakSuper;
    UILabel *_muteLabel;
    SGDialogs *_shopDialog;
    CDUnknownBlockType _loadCloudRedPackage;
    AGEmojiKeyboardView *_emojiKeyboardView;
    NSTimer *_inputPanelWillChangeHeightTimer;
    id <SGModernConversationInputTextPanelDelegate> _delegate;
    UIMenuItem *_huanHangItem;
    double _keyboardHeight;
    SGDialogs *_groupDialogs;
    SGGroupInfo *_groupInfo;
    struct CGSize _messageAreaSize;
}

+ (id)linkCandidateInText:(id)arg1;
+ (void)replaceMention:(id)arg1 inputField:(id)arg2;
@property(retain, nonatomic) SGGroupInfo *groupInfo; // @synthesize groupInfo=_groupInfo;
@property(retain, nonatomic) SGDialogs *groupDialogs; // @synthesize groupDialogs=_groupDialogs;
@property(retain, nonatomic) SGModernButton *emotionButton; // @synthesize emotionButton=_emotionButton;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(nonatomic) struct CGSize messageAreaSize; // @synthesize messageAreaSize=_messageAreaSize;
@property(retain, nonatomic) UIMenuItem *huanHangItem; // @synthesize huanHangItem=_huanHangItem;
@property(nonatomic) __weak id <SGModernConversationInputTextPanelDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTimer *inputPanelWillChangeHeightTimer; // @synthesize inputPanelWillChangeHeightTimer=_inputPanelWillChangeHeightTimer;
@property(nonatomic) __weak AGEmojiKeyboardView *emojiKeyboardView; // @synthesize emojiKeyboardView=_emojiKeyboardView;
@property(nonatomic) _Bool setOriginalInputTextFieldHeight; // @synthesize setOriginalInputTextFieldHeight=_setOriginalInputTextFieldHeight;
@property(copy, nonatomic) CDUnknownBlockType loadCloudRedPackage; // @synthesize loadCloudRedPackage=_loadCloudRedPackage;
@property(retain, nonatomic) SGDialogs *shopDialog; // @synthesize shopDialog=_shopDialog;
@property(retain, nonatomic) UILabel *muteLabel; // @synthesize muteLabel=_muteLabel;
@property(nonatomic) __weak UIViewController *weakSuper; // @synthesize weakSuper=_weakSuper;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) double touchDownTime; // @synthesize touchDownTime=_touchDownTime;
@property(nonatomic) _Bool recordPermissionGranted; // @synthesize recordPermissionGranted=_recordPermissionGranted;
@property(nonatomic) _Bool isAssociatePanel; // @synthesize isAssociatePanel=_isAssociatePanel;
@property(nonatomic) long long conversationId; // @synthesize conversationId=_conversationId;
@property(nonatomic) _Bool isAddsociateHeight; // @synthesize isAddsociateHeight=_isAddsociateHeight;
@property(nonatomic) _Bool displayProgress; // @synthesize displayProgress=_displayProgress;
@property(nonatomic) _Bool inputDisabled; // @synthesize inputDisabled=_inputDisabled;
@property(nonatomic) _Bool hasBots; // @synthesize hasBots=_hasBots;
@property(retain, nonatomic) SGModernConversationAssociatedPanel *associatePanel; // @synthesize associatePanel=_associatePanel;
@property(nonatomic) _Bool isBeDelete; // @synthesize isBeDelete=_isBeDelete;
@property(retain, nonatomic) UIView *panelAccessoryView; // @synthesize panelAccessoryView=_panelAccessoryView;
@property(nonatomic) _Bool canShowKeyboardAutomatically; // @synthesize canShowKeyboardAutomatically=_canShowKeyboardAutomatically;
@property(nonatomic) _Bool enableKeyboard; // @synthesize enableKeyboard=_enableKeyboard;
@property(readonly, nonatomic) _Bool changingKeyboardMode; // @synthesize changingKeyboardMode=_changingKeyboardMode;
@property(retain, nonatomic) NSString *contextPlaceholder; // @synthesize contextPlaceholder=_contextPlaceholder;
@property(retain, nonatomic) UIImageView *inputFieldPlaceholder; // @synthesize inputFieldPlaceholder=_inputFieldPlaceholder;
@property(retain, nonatomic) HPGrowingTextView *inputField; // @synthesize inputField=_inputField;
@property(retain, nonatomic) UIView *inputFieldClippingContainer; // @synthesize inputFieldClippingContainer=_inputFieldClippingContainer;
@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
@property(retain, nonatomic) UIButton *keyboardButton; // @synthesize keyboardButton=_keyboardButton;
@property(retain, nonatomic) UIButton *recordButton; // @synthesize recordButton=_recordButton;
@property(retain, nonatomic) UIButton *micButton; // @synthesize micButton=_micButton;
@property(retain, nonatomic) SGAddActionView *addView; // @synthesize addView=_addView;
@property(retain, nonatomic) UIButton *attachButton; // @synthesize attachButton=_attachButton;
@property(retain, nonatomic) UIImageView *fieldBackground; // @synthesize fieldBackground=_fieldBackground;
- (void).cxx_destruct;
- (void)setRecordButtonTitle:(_Bool)arg1;
- (void)cancelRecordButtonTouchEvent;
- (void)setRecordButtonBackground:(_Bool)arg1;
- (void)recordActionEnd;
- (void)recordButtonDragExit;
- (void)recordButtonDragEnter;
- (void)recordButtonTouchUpoutside;
- (void)recordButtonTouchUpinside;
- (void)recordButtonTouchDown;
- (_Bool)recordButtonTouchEventEnded;
- (void)addActionTargets;
- (void)slashModeButtonPressed;
- (void)keyboardModeButtonPressed;
- (void)setModeButtons:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)shouldDisableAutocorrection;
- (struct CGRect)broadcastModeButtonFrame;
- (struct CGRect)stickerButtonFrame;
- (struct CGRect)attachmentButtonFrame;
- (void)shakeControls;
- (void)layoutSubviews;
- (void)_inputPanelWillChangeHeight:(id)arg1;
- (void)growingTextView:(id)arg1 willChangeHeight:(double)arg2 duration:(double)arg3 animationCurve:(int)arg4;
- (void)cancelButtonClick;
- (void)setAssociatePanelWithMessage:(id)arg1 associateHidden:(_Bool)arg2;
- (void)changeToSize:(struct CGSize)arg1 keyboardHeight:(double)arg2 duration:(double)arg3;
- (void)updateInputFieldLayout;
- (void)_adjustForSize:(struct CGSize)arg1 keyboardHeight:(double)arg2 inputFieldHeight:(double)arg3 duration:(double)arg4 animationCurve:(int)arg5;
- (double)heightForInputFieldHeight:(double)arg1;
- (struct CGPoint)inputFieldPlaceholderOffset;
- (struct UIEdgeInsets)inputFieldInternalEdgeInsets;
- (struct UIEdgeInsets)inputFieldInsets;
- (double)extendedPanelHeight;
- (_Bool)shouldDisplayPanels;
- (double)baseHeight;
- (void)adjustForSize:(struct CGSize)arg1 keyboardHeight:(double)arg2 duration:(double)arg3 animationCurve:(int)arg4;
- (int)_maxNumberOfLinesForSize:(struct CGSize)arg1;
- (void)micButtonPressed;
- (void)sendImageArray:(id)arg1;
- (void)onClickCamera:(id)arg1;
- (_Bool)addActionCanRobet;
- (_Bool)addActionCanShop;
- (_Bool)addActionCanDonated;
- (_Bool)addActionCanExtort;
- (_Bool)addActionCanReward;
- (void)addActionClick:(long long)arg1 withObject:(id)arg2 flag:(_Bool)arg3;
- (void)attachButtonPressed:(id)arg1;
- (id)sendText;
- (void)sendButtonPressed;
- (void)sendStickerImage:(id)arg1;
- (void)addEmojiClips;
- (void)fieldBackgroundTapGesture:(id)arg1;
- (_Bool)inputPanelSendShouldBeAlwaysEnabled;
- (void)growingTextViewDidChange:(id)arg1 afterSetText:(_Bool)arg2;
- (void)actionStageResourceDispatched:(id)arg1 resource:(id)arg2 arguments:(id)arg3;
- (id)_inputTextForText:(id)arg1 byAddingString:(id)arg2;
- (void)replaceMention:(id)arg1;
- (void)sgemoticKeyboradDidSelectedIndex:(id)arg1 withSelectedEmoj:(id)arg2;
- (void)insertText:(id)arg1;
- (id)backSpaceButtonImageForEmojiKeyboardView:(id)arg1;
- (id)emojiKeyboardView:(id)arg1 imageForNonSelectedCategory:(long long)arg2;
- (id)emojiKeyboardView:(id)arg1 imageForSelectedCategory:(long long)arg2;
- (id)imageByCategory:(long long)arg1;
- (long long)defaultCategoryForEmojiKeyboardView:(id)arg1;
- (void)emojiKeyBoardViewDidPressBackSpace:(id)arg1;
- (struct _NSRange)lastRange:(id)arg1;
- (void)emojiKeyBoardView:(id)arg1 didUseEmoji:(id)arg2;
- (void)setEmotionButtonSelectedAction;
- (void)emotionButtonPress:(id)arg1;
- (void)keyboardButtonPress;
- (void)growingTextViewTextChange:(id)arg1;
- (_Bool)growingTextViewShouldReturn:(id)arg1;
- (void)growingTextViewDidEndEditing:(id)arg1;
- (void)growingTextViewDidBeginEditing:(id)arg1;
- (void)growingTextView:(id)arg1 didPasteImage:(id)arg2;
- (void)inputViewDidClear;
- (_Bool)growingTextViewShouldBeginEditing:(id)arg1;
- (void)setRecallEditPanelDraft:(id)arg1;
- (void)setPanelDraft:(id)arg1;
- (void)addCutomItem;
- (void)growingTextAddHuanHang;
- (void)addAttributedString:(id)arg1;
- (_Bool)growingTextViewEnabled:(id)arg1 replacementText:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)maybeInputField;
- (void)_updatePlaceholderImage;
- (void)setReplyPanel;
- (void)reloadMenueShowContent;
- (id)initWithFrame:(struct CGRect)arg1 accessoryView:(id)arg2 withGroupFlag:(_Bool)arg3 withConversationUin:(long long)arg4 withDialog:(id)arg5 delegate:(id)arg6;
- (SEL)extracted;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

