//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, NSURL, PHAsset, SGModernConversationInputTextPanel, SGStickerModel, UIImage;

@protocol SGModernConversationInputTextPanelDelegate <NSObject>
- (void)conversationSendSticker:(SGStickerModel *)arg1;
- (void)addStickers:(SGModernConversationInputTextPanel *)arg1;
- (void)conversationMicroButtonClick:(_Bool)arg1;
- (void)conversationInputTextPanelSendAtWIthStr:(NSString *)arg1;
- (void)conversationInputPanelAssociatePanelHidden:(_Bool)arg1;
- (void)conversationInputPanelWillChangeHeight:(SGModernConversationInputTextPanel *)arg1 a:(double)arg2 b:(double)arg3 c:(int)arg4;
- (_Bool)conversationInputPanelRequestedSendMessage:(SGModernConversationInputTextPanel *)arg1 a:(NSString *)arg2;
- (void)growingTextViewDidEndEditing:(SGModernConversationInputTextPanel *)arg1;
- (void)growingTextViewDidBeginEditing:(SGModernConversationInputTextPanel *)arg1;
- (_Bool)growingTextViewShouldBeginEditing:(SGModernConversationInputTextPanel *)arg1;

@optional
- (_Bool)conversationActionSheetCanRobet;
- (_Bool)conversationActionSheetCanShop;
- (_Bool)conversationActionSheetCanDonated;
- (_Bool)conversationActionSheetCanExtort;
- (_Bool)actionSheetCanReward;
- (void)conversationActionJirmRedpacket;
- (void)conversationActionSheetShop;
- (void)conversationActionSheetDonated;
- (void)conversationActionSheetExtort;
- (void)conversationActionSheetReward;
- (void)conversationActionSheetAlipayRedPacketTaped;
- (void)conversationInputPanelText:(SGModernConversationInputTextPanel *)arg1 a:(UIImage *)arg2;
- (void)selectedPHAsset:(PHAsset *)arg1 image:(UIImage *)arg2 type:(unsigned long long)arg3;
- (void)conversationActionSheetGame;
- (void)conversationActionSheetCollect;
- (void)conversationActionSheetTremble;
- (void)conversationActionSheetImageDidTaped;
- (void)conversationActionSheetBillTaped;
- (void)conversationActionSheetRedPacketTaped;
- (void)conversationActionSheetTransfer;
- (void)conversationActionSheetPhone;
- (void)actionSheetLocationTaped;
- (void)conversationActionSheetCardDidTapd;
- (void)conversationActionSheetVideoPath:(NSURL *)arg1 a:(UIImage *)arg2;
- (void)conversationActionSheetDidFinished:(NSArray *)arg1;
- (void)conversationVoiceRecordingTooShort;
- (void)conversationVoiceRecordingDidDragoutside;
- (void)conversationVoiceRecordingDidDraginside;
- (void)conversationVoicRecordingShouldFinish;
- (void)conversationVoiceRecordingShouldCancel;
- (void)conversationVoiceRecordingShouldStart;
- (_Bool)sendStickerImage:(id)arg1;
- (_Bool)addEmojiButtonClips:(SGModernConversationInputTextPanel *)arg1;
- (_Bool)conversationDeleteTextAction;
- (_Bool)inputPanelSendShouldBeAlwaysEnabled:(SGModernConversationInputTextPanel *)arg1;
- (void)inputPanelTextChanged:(SGModernConversationInputTextPanel *)arg1 text:(NSString *)arg2;
@end

