//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SGGoodsListDataVO, UIButton, UIImageView, UILabel, UIView;
@protocol GoodsListCellDelegate;

@interface SGNewGoodsListCell : UITableViewCell
{
    SGGoodsListDataVO *_goodModel;
    id <GoodsListCellDelegate> _cellDelegate;
    UIView *_bkgView;
    UIImageView *_goodsIconView;
    UILabel *_goodsNameLab;
    UILabel *_rmbLab;
    UIButton *_sendButton;
    UIView *_verLineView;
    UILabel *_commissonLab;
    UILabel *_buyNumLab;
    UILabel *_failerLab;
}

@property(retain, nonatomic) UILabel *failerLab; // @synthesize failerLab=_failerLab;
@property(retain, nonatomic) UILabel *buyNumLab; // @synthesize buyNumLab=_buyNumLab;
@property(retain, nonatomic) UILabel *commissonLab; // @synthesize commissonLab=_commissonLab;
@property(retain, nonatomic) UIView *verLineView; // @synthesize verLineView=_verLineView;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UILabel *rmbLab; // @synthesize rmbLab=_rmbLab;
@property(retain, nonatomic) UILabel *goodsNameLab; // @synthesize goodsNameLab=_goodsNameLab;
@property(retain, nonatomic) UIImageView *goodsIconView; // @synthesize goodsIconView=_goodsIconView;
@property(retain, nonatomic) UIView *bkgView; // @synthesize bkgView=_bkgView;
@property(nonatomic) __weak id <GoodsListCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(retain, nonatomic) SGGoodsListDataVO *goodModel; // @synthesize goodModel=_goodModel;
- (void).cxx_destruct;
- (void)clickShare;
- (void)clickEdit;
- (void)clcikDelete;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

