//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSString;

@interface SGNewWxDepositResp : SGHTTPSResponseModel
{
    NSString *_timeStamp;
    NSString *_nonceStr;
    NSString *_prepayId;
    NSString *_paySign;
    NSString *_myPackage;
    NSString *_partnerId;
    long long _depositId;
}

+ (int)constructor;
@property(nonatomic) long long depositId; // @synthesize depositId=_depositId;
@property(copy, nonatomic) NSString *partnerId; // @synthesize partnerId=_partnerId;
@property(copy, nonatomic) NSString *myPackage; // @synthesize myPackage=_myPackage;
@property(copy, nonatomic) NSString *paySign; // @synthesize paySign=_paySign;
@property(copy, nonatomic) NSString *prepayId; // @synthesize prepayId=_prepayId;
@property(copy, nonatomic) NSString *nonceStr; // @synthesize nonceStr=_nonceStr;
@property(copy, nonatomic) NSString *timeStamp; // @synthesize timeStamp=_timeStamp;
- (void).cxx_destruct;

@end

