//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDetailCellModel.h"

@class NSString, SGOrderSetSuccessModel;

@interface SGNewOrderSetSuccessCellModel : SGDialogDetailCellModel
{
    SGOrderSetSuccessModel *_setSuccessModel;
    NSString *_noticeTitleAtt;
    NSString *_balanceAtt;
    NSString *_amoutAtt;
    NSString *_bottomAtt;
    NSString *_settleRoleAtt;
    NSString *_settleRoleName;
    NSString *_settleNumLeftStr;
    NSString *_settleNum;
    NSString *_intructLeftStr;
    NSString *_intructContent;
    struct CGRect _noticeTitleFrame;
    struct CGRect _noticeBalanceTextFrame;
    struct CGRect _noticeAmoutFrame;
    struct CGRect _settleRoleLeftFrame;
    struct CGRect _settleRoleNameFrame;
    struct CGRect _settleNumLeftFrame;
    struct CGRect _settleNumFrame;
    struct CGRect _intructleftFrame;
    struct CGRect _intructContentFrame;
    struct CGRect _lineFrame;
    struct CGRect _arrowFrame;
    struct CGRect _bottomtextFrame;
}

@property(nonatomic) struct CGRect bottomtextFrame; // @synthesize bottomtextFrame=_bottomtextFrame;
@property(nonatomic) struct CGRect arrowFrame; // @synthesize arrowFrame=_arrowFrame;
@property(nonatomic) struct CGRect lineFrame; // @synthesize lineFrame=_lineFrame;
@property(nonatomic) struct CGRect intructContentFrame; // @synthesize intructContentFrame=_intructContentFrame;
@property(nonatomic) struct CGRect intructleftFrame; // @synthesize intructleftFrame=_intructleftFrame;
@property(nonatomic) struct CGRect settleNumFrame; // @synthesize settleNumFrame=_settleNumFrame;
@property(nonatomic) struct CGRect settleNumLeftFrame; // @synthesize settleNumLeftFrame=_settleNumLeftFrame;
@property(nonatomic) struct CGRect settleRoleNameFrame; // @synthesize settleRoleNameFrame=_settleRoleNameFrame;
@property(nonatomic) struct CGRect settleRoleLeftFrame; // @synthesize settleRoleLeftFrame=_settleRoleLeftFrame;
@property(nonatomic) struct CGRect noticeAmoutFrame; // @synthesize noticeAmoutFrame=_noticeAmoutFrame;
@property(nonatomic) struct CGRect noticeBalanceTextFrame; // @synthesize noticeBalanceTextFrame=_noticeBalanceTextFrame;
@property(nonatomic) struct CGRect noticeTitleFrame; // @synthesize noticeTitleFrame=_noticeTitleFrame;
@property(copy, nonatomic) NSString *intructContent; // @synthesize intructContent=_intructContent;
@property(copy, nonatomic) NSString *intructLeftStr; // @synthesize intructLeftStr=_intructLeftStr;
@property(copy, nonatomic) NSString *settleNum; // @synthesize settleNum=_settleNum;
@property(copy, nonatomic) NSString *settleNumLeftStr; // @synthesize settleNumLeftStr=_settleNumLeftStr;
@property(copy, nonatomic) NSString *settleRoleName; // @synthesize settleRoleName=_settleRoleName;
@property(copy, nonatomic) NSString *settleRoleAtt; // @synthesize settleRoleAtt=_settleRoleAtt;
@property(copy, nonatomic) NSString *bottomAtt; // @synthesize bottomAtt=_bottomAtt;
@property(copy, nonatomic) NSString *amoutAtt; // @synthesize amoutAtt=_amoutAtt;
@property(copy, nonatomic) NSString *balanceAtt; // @synthesize balanceAtt=_balanceAtt;
@property(copy, nonatomic) NSString *noticeTitleAtt; // @synthesize noticeTitleAtt=_noticeTitleAtt;
@property(retain, nonatomic) SGOrderSetSuccessModel *setSuccessModel; // @synthesize setSuccessModel=_setSuccessModel;
- (void).cxx_destruct;
- (Class)getCellClass;
- (struct CGSize)getSizeBy:(id)arg1 strFont:(double)arg2 maxSize:(struct CGSize)arg3;
- (void)calculateSubView;
- (id)initWithMessage:(id)arg1 member:(id)arg2;

@end

