//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@interface SGNewAddGoodsViewController : SGViewController
{
    CDUnknownBlockType _addBlock;
    CDUnknownBlockType _deletOfficeBlock;
    CDUnknownBlockType _thirdBlock;
    long long _groupID;
    SGViewController *_navgationLastViewController;
}

@property(nonatomic) __weak SGViewController *navgationLastViewController; // @synthesize navgationLastViewController=_navgationLastViewController;
@property(nonatomic) long long groupID; // @synthesize groupID=_groupID;
@property(copy, nonatomic) CDUnknownBlockType thirdBlock; // @synthesize thirdBlock=_thirdBlock;
@property(copy, nonatomic) CDUnknownBlockType deletOfficeBlock; // @synthesize deletOfficeBlock=_deletOfficeBlock;
@property(copy, nonatomic) CDUnknownBlockType addBlock; // @synthesize addBlock=_addBlock;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)clcikOwn;
- (void)clcikOffice;
- (void)creatChildView;
- (void)viewDidLoad;

@end

