//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SGGroupMangeCellModel, UIImageView, UILabel, UISwitch, UIView;
@protocol SGNewGroupMangerSwitchDelegate;

@interface SGNewGroupMangerCell : UITableViewCell
{
    _Bool _hiddBottomLine;
    SGGroupMangeCellModel *_cellModel;
    id <SGNewGroupMangerSwitchDelegate> _cellDelegate;
    UILabel *_nameTitleLab;
    UILabel *_subInfoTitleLab;
    UISwitch *_cellSwitch;
    UIView *_cellBottomLineView;
    UIImageView *_arrowIconView;
    UIView *_redView;
    UIView *_otherRedView;
}

@property(retain, nonatomic) UIView *otherRedView; // @synthesize otherRedView=_otherRedView;
@property(retain, nonatomic) UIView *redView; // @synthesize redView=_redView;
@property(retain, nonatomic) UIImageView *arrowIconView; // @synthesize arrowIconView=_arrowIconView;
@property(retain, nonatomic) UIView *cellBottomLineView; // @synthesize cellBottomLineView=_cellBottomLineView;
@property(retain, nonatomic) UISwitch *cellSwitch; // @synthesize cellSwitch=_cellSwitch;
@property(retain, nonatomic) UILabel *subInfoTitleLab; // @synthesize subInfoTitleLab=_subInfoTitleLab;
@property(retain, nonatomic) UILabel *nameTitleLab; // @synthesize nameTitleLab=_nameTitleLab;
@property(nonatomic) __weak id <SGNewGroupMangerSwitchDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(nonatomic) _Bool hiddBottomLine; // @synthesize hiddBottomLine=_hiddBottomLine;
@property(retain, nonatomic) SGGroupMangeCellModel *cellModel; // @synthesize cellModel=_cellModel;
- (void).cxx_destruct;
- (void)switchOnChange;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

