//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SGGoodsCategory, UILabel, UIView;

@interface SGOfficeLeftCategoryCell : UITableViewCell
{
    SGGoodsCategory *_model;
    UIView *_bkgView;
    UILabel *_nameLab;
    UIView *_redSignView;
}

@property(retain, nonatomic) UIView *redSignView; // @synthesize redSignView=_redSignView;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) UIView *bkgView; // @synthesize bkgView=_bkgView;
@property(retain, nonatomic) SGGoodsCategory *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

