//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

#import "ASWatcher-Protocol.h"
#import "SGHomePageCustomLayoutDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ASHandle, NSMutableArray, NSString, SGGetXmallPaymentChannelListResp, SGPayWaitingOrderForMobileResp, SGSendPacketPayView, SGSetGameLoadingView, SGShowOrderResp, SGTLAccountBalanceResp, SGValidateWaitPayOrderResp, SGVirtualGoodsAccountListView, UIButton, UICollectionView, UIImageView, UILabel, UITableView, UIView, _TtC8xianliao22SGSystemRecomGoodsView;

@interface SGOrderDetailViewController : SGGoodsBaseViewController <UITableViewDelegate, UITableViewDataSource, ASWatcher, UICollectionViewDataSource, UICollectionViewDelegate, SGHomePageCustomLayoutDelegate>
{
    _Bool _isFromOrderManger;
    _Bool _forbidPanGesture;
    _Bool _isFromPerson;
    int _pageNo;
    long long _groupID;
    NSString *_orderNo;
    UITableView *_tableView;
    SGSetGameLoadingView *_loadingView;
    UILabel *_stateLab;
    UILabel *_receiveNameLab;
    UILabel *_addressLab;
    UIView *_remarkView;
    UILabel *_remarkLab;
    UIImageView *_headIconView;
    UIImageView *_serviceIconView;
    UILabel *_phoneCenterLab;
    UILabel *_nameLab;
    UILabel *_contactLab;
    UILabel *_totalMoneyLab;
    UILabel *_payMoneyLab;
    UILabel *_goldLab;
    UILabel *_commissionLab;
    UILabel *_orderCodeLab;
    UILabel *_payWayLab;
    UILabel *_orderTimeLab;
    UILabel *_payTimeLab;
    UILabel *_overTimeLab;
    SGShowOrderResp *_orderResp;
    SGSendPacketPayView *_payAlertView;
    UIView *_continuePayView;
    SGVirtualGoodsAccountListView *_virtualAccountView;
    UIView *_normalGoodsExpressView;
    UILabel *_normalGoodsExpressTimeLab;
    SGTLAccountBalanceResp *_accountResp;
    UILabel *_messageDescLab;
    UILabel *_realPayLeftLab;
    UIView *_mobileFeeOrFlowView;
    UILabel *_mobilePhoneLab;
    UIView *_groupView;
    UIImageView *_groupImageView;
    UILabel *_groupNameLab;
    UIView *_groupPersonContactView;
    UIImageView *_serveListenIconV;
    UIButton *_addressSignButton;
    UIView *_refundEnterView;
    UIButton *_refundButton;
    SGGetXmallPaymentChannelListResp *_payListResp;
    SGValidateWaitPayOrderResp *_waitPayResp;
    SGPayWaitingOrderForMobileResp *_waitMobileResp;
    ASHandle *_actionHandle;
    UICollectionView *_collectionView;
    NSMutableArray *_recomendArtray;
    _TtC8xianliao22SGSystemRecomGoodsView *_headRecView;
}

@property(retain, nonatomic) _TtC8xianliao22SGSystemRecomGoodsView *headRecView; // @synthesize headRecView=_headRecView;
@property(nonatomic) int pageNo; // @synthesize pageNo=_pageNo;
@property(retain, nonatomic) NSMutableArray *recomendArtray; // @synthesize recomendArtray=_recomendArtray;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
@property(retain, nonatomic) SGPayWaitingOrderForMobileResp *waitMobileResp; // @synthesize waitMobileResp=_waitMobileResp;
@property(retain, nonatomic) SGValidateWaitPayOrderResp *waitPayResp; // @synthesize waitPayResp=_waitPayResp;
@property(retain, nonatomic) SGGetXmallPaymentChannelListResp *payListResp; // @synthesize payListResp=_payListResp;
@property(retain, nonatomic) UIButton *refundButton; // @synthesize refundButton=_refundButton;
@property(retain, nonatomic) UIView *refundEnterView; // @synthesize refundEnterView=_refundEnterView;
@property(retain, nonatomic) UIButton *addressSignButton; // @synthesize addressSignButton=_addressSignButton;
@property(nonatomic) __weak UIImageView *serveListenIconV; // @synthesize serveListenIconV=_serveListenIconV;
@property(retain, nonatomic) UIView *groupPersonContactView; // @synthesize groupPersonContactView=_groupPersonContactView;
@property(retain, nonatomic) UILabel *groupNameLab; // @synthesize groupNameLab=_groupNameLab;
@property(retain, nonatomic) UIImageView *groupImageView; // @synthesize groupImageView=_groupImageView;
@property(retain, nonatomic) UIView *groupView; // @synthesize groupView=_groupView;
@property(retain, nonatomic) UILabel *mobilePhoneLab; // @synthesize mobilePhoneLab=_mobilePhoneLab;
@property(retain, nonatomic) UIView *mobileFeeOrFlowView; // @synthesize mobileFeeOrFlowView=_mobileFeeOrFlowView;
@property(nonatomic) __weak UILabel *realPayLeftLab; // @synthesize realPayLeftLab=_realPayLeftLab;
@property(nonatomic) __weak UILabel *messageDescLab; // @synthesize messageDescLab=_messageDescLab;
@property(retain, nonatomic) SGTLAccountBalanceResp *accountResp; // @synthesize accountResp=_accountResp;
@property(retain, nonatomic) UILabel *normalGoodsExpressTimeLab; // @synthesize normalGoodsExpressTimeLab=_normalGoodsExpressTimeLab;
@property(retain, nonatomic) UIView *normalGoodsExpressView; // @synthesize normalGoodsExpressView=_normalGoodsExpressView;
@property(retain, nonatomic) SGVirtualGoodsAccountListView *virtualAccountView; // @synthesize virtualAccountView=_virtualAccountView;
@property(retain, nonatomic) UIView *continuePayView; // @synthesize continuePayView=_continuePayView;
@property(retain, nonatomic) SGSendPacketPayView *payAlertView; // @synthesize payAlertView=_payAlertView;
@property(retain, nonatomic) SGShowOrderResp *orderResp; // @synthesize orderResp=_orderResp;
@property(retain, nonatomic) UILabel *overTimeLab; // @synthesize overTimeLab=_overTimeLab;
@property(retain, nonatomic) UILabel *payTimeLab; // @synthesize payTimeLab=_payTimeLab;
@property(retain, nonatomic) UILabel *orderTimeLab; // @synthesize orderTimeLab=_orderTimeLab;
@property(retain, nonatomic) UILabel *payWayLab; // @synthesize payWayLab=_payWayLab;
@property(retain, nonatomic) UILabel *orderCodeLab; // @synthesize orderCodeLab=_orderCodeLab;
@property(retain, nonatomic) UILabel *commissionLab; // @synthesize commissionLab=_commissionLab;
@property(retain, nonatomic) UILabel *goldLab; // @synthesize goldLab=_goldLab;
@property(retain, nonatomic) UILabel *payMoneyLab; // @synthesize payMoneyLab=_payMoneyLab;
@property(retain, nonatomic) UILabel *totalMoneyLab; // @synthesize totalMoneyLab=_totalMoneyLab;
@property(retain, nonatomic) UILabel *contactLab; // @synthesize contactLab=_contactLab;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) UILabel *phoneCenterLab; // @synthesize phoneCenterLab=_phoneCenterLab;
@property(retain, nonatomic) UIImageView *serviceIconView; // @synthesize serviceIconView=_serviceIconView;
@property(retain, nonatomic) UIImageView *headIconView; // @synthesize headIconView=_headIconView;
@property(retain, nonatomic) UILabel *remarkLab; // @synthesize remarkLab=_remarkLab;
@property(retain, nonatomic) UIView *remarkView; // @synthesize remarkView=_remarkView;
@property(retain, nonatomic) UILabel *addressLab; // @synthesize addressLab=_addressLab;
@property(retain, nonatomic) UILabel *receiveNameLab; // @synthesize receiveNameLab=_receiveNameLab;
@property(retain, nonatomic) UILabel *stateLab; // @synthesize stateLab=_stateLab;
@property(retain, nonatomic) SGSetGameLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isFromPerson; // @synthesize isFromPerson=_isFromPerson;
@property(nonatomic) _Bool forbidPanGesture; // @synthesize forbidPanGesture=_forbidPanGesture;
@property(nonatomic) _Bool isFromOrderManger; // @synthesize isFromOrderManger=_isFromOrderManger;
@property(copy, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(nonatomic) long long groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)tapGroupBuyInfo;
- (void)setRefundDetailButtonHiddern;
- (void)clickRefund;
- (_Bool)getRefundButtonIsShow;
- (void)requesrtGetNewOrderRefundState;
- (void)dealloc;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)getItemCellHeight:(id)arg1;
- (double)getSectionHeadHeight:(long long)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)pullMoreData;
- (void)requestGetRecomData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)showNormalGoodsExpressInfo;
- (void)clickToShowGoodsDetail;
- (void)clcikGroup;
- (void)inviteFriendForGroupShop;
- (void)cancleOrder;
- (void)checkIsPayPassword:(CDUnknownBlockType)arg1;
- (void)checkIsRealNameAuth:(CDUnknownBlockType)arg1;
- (void)alertRespError:(id)arg1;
- (void)reBuildView;
- (void)contiunePayGoodsSuccess;
- (void)continuePayResponse:(id)arg1;
- (void)payGoodsWithPassword:(id)arg1 withPayWayModel:(id)arg2;
- (void)getMyWaitResp:(CDUnknownBlockType)arg1;
- (void)payWithWeiXin;
- (void)payWithCustomTlBalance;
- (void)showPayChooseView:(id)arg1;
- (void)judgePayWhichWay;
- (void)getDefaultPayWay:(_Bool)arg1 nextBlock:(CDUnknownBlockType)arg2;
- (void)continuePay;
- (void)getMyBalance:(_Bool)arg1 nextBlock:(CDUnknownBlockType)arg2;
- (void)actionStageResourceDispatched:(id)arg1 resource:(id)arg2 arguments:(id)arg3;
- (void)copyOrderNo;
- (void)clcikContact;
- (id)getOrderStateImage;
- (_Bool)judgeOrderSataeShowExpress:(_Bool)arg1;
- (void)clickRightItemToComplaint;
- (void)backAction;
- (void)setData;
- (void)getGroupContactView;
- (void)creatChildView;
- (void)retryRequest;
- (void)getOrderDetail;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

