//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGOrderSetSuccessModel : NSObject
{
    int _settleRoleType;
    int _settleNum;
    long long _settleAmount;
    NSString *_settleRoleName;
    NSString *_orderNoList;
}

@property(copy, nonatomic) NSString *orderNoList; // @synthesize orderNoList=_orderNoList;
@property(nonatomic) int settleNum; // @synthesize settleNum=_settleNum;
@property(copy, nonatomic) NSString *settleRoleName; // @synthesize settleRoleName=_settleRoleName;
@property(nonatomic) int settleRoleType; // @synthesize settleRoleType=_settleRoleType;
@property(nonatomic) long long settleAmount; // @synthesize settleAmount=_settleAmount;
- (void).cxx_destruct;

@end

