//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface SGPayXmallOrderReq : SGHTTPSReqModel
{
    NSString *_transactionId;
    long long _orderAmount;
    NSString *_payPasswd;
    NSString *_validateToken;
}

@property(copy, nonatomic) NSString *validateToken; // @synthesize validateToken=_validateToken;
@property(copy, nonatomic) NSString *payPasswd; // @synthesize payPasswd=_payPasswd;
@property(nonatomic) long long orderAmount; // @synthesize orderAmount=_orderAmount;
@property(copy, nonatomic) NSString *transactionId; // @synthesize transactionId=_transactionId;
- (void).cxx_destruct;
- (int)constructor;

@end

