//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

#import "SGHomePageCustomLayoutDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UICollectionView, UIView, _TtC8xianliao22SGSystemRecomGoodsView;

@interface SGPayGoodSuccessViewController : SGGoodsBaseViewController <UICollectionViewDataSource, UICollectionViewDelegate, SGHomePageCustomLayoutDelegate>
{
    _Bool _isContinuePaySuccess;
    _Bool _isFromBalance;
    int _pageNo;
    long long _groupID;
    NSArray *_goodsIdArray;
    CDUnknownBlockType _exitBlock;
    NSString *_orderNo;
    UIView *_collectionHeadView;
    UICollectionView *_collectionView;
    NSMutableArray *_dataSource;
    _TtC8xianliao22SGSystemRecomGoodsView *_headRecView;
}

@property(retain, nonatomic) _TtC8xianliao22SGSystemRecomGoodsView *headRecView; // @synthesize headRecView=_headRecView;
@property(nonatomic) int pageNo; // @synthesize pageNo=_pageNo;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UIView *collectionHeadView; // @synthesize collectionHeadView=_collectionHeadView;
@property(copy, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(nonatomic) _Bool isFromBalance; // @synthesize isFromBalance=_isFromBalance;
@property(nonatomic) _Bool isContinuePaySuccess; // @synthesize isContinuePaySuccess=_isContinuePaySuccess;
@property(copy, nonatomic) CDUnknownBlockType exitBlock; // @synthesize exitBlock=_exitBlock;
@property(retain, nonatomic) NSArray *goodsIdArray; // @synthesize goodsIdArray=_goodsIdArray;
@property(nonatomic) long long groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)getItemCellHeight:(id)arg1;
- (double)getSectionHeadHeight:(long long)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)pullMoreData;
- (void)requestGetRecomData;
- (void)showOrder;
- (void)backAction;
- (void)setHeadView;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

