//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "GLImagePreviewDelegate-Protocol.h"

@class NSString, SGGroupMember, SGUser, SGVipLevelImageView, UIImageView, UILabel;

@interface SGPhotoInfoCell : UITableViewCell <GLImagePreviewDelegate>
{
    UIImageView *_headImage;
    long long _userType;
    UILabel *_nickNameLab;
    UILabel *_aliasNameLab;
    SGVipLevelImageView *_vipLeveIV;
    UILabel *_groupAliasNameLab;
    UIImageView *_genderImageView;
    UIImageView *_qrCodeImageView;
    SGUser *_user;
    SGGroupMember *_groupMember;
    UILabel *_xianliaoIdLab;
}

@property(retain, nonatomic) UILabel *xianliaoIdLab; // @synthesize xianliaoIdLab=_xianliaoIdLab;
@property(retain, nonatomic) SGGroupMember *groupMember; // @synthesize groupMember=_groupMember;
@property(retain, nonatomic) SGUser *user; // @synthesize user=_user;
@property(retain, nonatomic) UIImageView *qrCodeImageView; // @synthesize qrCodeImageView=_qrCodeImageView;
@property(retain, nonatomic) UIImageView *genderImageView; // @synthesize genderImageView=_genderImageView;
@property(retain, nonatomic) UILabel *groupAliasNameLab; // @synthesize groupAliasNameLab=_groupAliasNameLab;
@property(retain, nonatomic) SGVipLevelImageView *vipLeveIV; // @synthesize vipLeveIV=_vipLeveIV;
@property(retain, nonatomic) UILabel *aliasNameLab; // @synthesize aliasNameLab=_aliasNameLab;
@property(retain, nonatomic) UILabel *nickNameLab; // @synthesize nickNameLab=_nickNameLab;
@property(nonatomic) long long userType; // @synthesize userType=_userType;
@property(retain, nonatomic) UIImageView *headImage; // @synthesize headImage=_headImage;
- (void).cxx_destruct;
- (_Bool)conversationCanDownLoad:(id)arg1 index:(long long)arg2;
- (id)conversationPreviewHiddenSuperView:(id)arg1;
- (void)longPressGetImageViewForIndex:(long long)arg1;
- (_Bool)previewGetImageData:(id)arg1 imageViewForIndex:(long long)arg2 finished:(CDUnknownBlockType)arg3;
- (id)preview:(id)arg1 highQualityImageURLForIndex:(long long)arg2;
- (id)preview:(id)arg1 imageViewForIndex:(long long)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)setHeadImage:(id)arg1 withNickName:(id)arg2 withUin:(long long)arg3;
- (void)setHeadImage:(id)arg1 withNickName:(id)arg2 aliasName:(id)arg3 user:(id)arg4 withXianliaoId:(id)arg5;
- (void)setHeadImage:(id)arg1 withNickName:(id)arg2 aliasName:(id)arg3 user:(id)arg4 isNeedDesensition:(_Bool)arg5;
- (void)setHeadImage:(id)arg1 withNickName:(id)arg2 aliasName:(id)arg3 user:(id)arg4;
- (void)setVipLevel:(long long)arg1 setXianliaoId:(id)arg2;
- (void)setVipLevel:(long long)arg1;
- (void)setHeadImage:(id)arg1 withNickName:(id)arg2 withQrCodeImageName:(id)arg3 withXianliaoId:(id)arg4;
- (void)setHeadImage:(id)arg1 withNickName:(id)arg2 withQrCodeImageName:(id)arg3;
- (void)setHeadImage:(id)arg1 withNickName:(id)arg2;
- (void)setAliasLab:(_Bool)arg1 groupMember:(_Bool)arg2 nickName:(_Bool)arg3 xianliaoId:(_Bool)arg4 memberRect:(struct CGRect)arg5;
- (void)setUser:(id)arg1 groupMember:(id)arg2 isNeedDesensition:(_Bool)arg3;
- (void)setUser:(id)arg1 groupMember:(id)arg2;
- (void)headClick:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

