//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UICollectionView;

@interface SGPlatformAllSecondTitleView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    _Bool _hiddenAllFlag;
    NSArray *_sonCategories;
    CDUnknownBlockType _chooseBlock;
    UICollectionView *_collectionView;
    UIView *_topView;
    UIView *_moreView;
    NSMutableArray *_dataSource;
}

@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UIView *moreView; // @synthesize moreView=_moreView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(copy, nonatomic) CDUnknownBlockType chooseBlock; // @synthesize chooseBlock=_chooseBlock;
@property(retain, nonatomic) NSArray *sonCategories; // @synthesize sonCategories=_sonCategories;
@property(nonatomic) _Bool hiddenAllFlag; // @synthesize hiddenAllFlag=_hiddenAllFlag;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)tapCloseMoreSecondCategory;
- (void)showAll:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

