//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class OrderItemDetailVO, SGResponWaitPayGoodsItemVO, UIImageView, UILabel;

@interface SGPrePareBuyGoodsListCell : UITableViewCell
{
    _Bool _isKillGoods;
    SGResponWaitPayGoodsItemVO *_waitModel;
    OrderItemDetailVO *_itemModel;
    UIImageView *_goodsIconView;
    UILabel *_goodsNameLab;
    UILabel *_goodsSkuLab;
    UILabel *_goodsNumberLab;
    UILabel *_goodsPriceLab;
    UILabel *_officeFlagLab;
    UILabel *_tagsPriceLab;
}

@property(retain, nonatomic) UILabel *tagsPriceLab; // @synthesize tagsPriceLab=_tagsPriceLab;
@property(retain, nonatomic) UILabel *officeFlagLab; // @synthesize officeFlagLab=_officeFlagLab;
@property(retain, nonatomic) UILabel *goodsPriceLab; // @synthesize goodsPriceLab=_goodsPriceLab;
@property(retain, nonatomic) UILabel *goodsNumberLab; // @synthesize goodsNumberLab=_goodsNumberLab;
@property(retain, nonatomic) UILabel *goodsSkuLab; // @synthesize goodsSkuLab=_goodsSkuLab;
@property(retain, nonatomic) UILabel *goodsNameLab; // @synthesize goodsNameLab=_goodsNameLab;
@property(retain, nonatomic) UIImageView *goodsIconView; // @synthesize goodsIconView=_goodsIconView;
@property(nonatomic) _Bool isKillGoods; // @synthesize isKillGoods=_isKillGoods;
@property(retain, nonatomic) OrderItemDetailVO *itemModel; // @synthesize itemModel=_itemModel;
@property(retain, nonatomic) SGResponWaitPayGoodsItemVO *waitModel; // @synthesize waitModel=_waitModel;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

