//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "SGShareViewDelegate-Protocol.h"

@class NSArray, NSString, SGButton, SGDialogs, SGGroupInfo, SGShareView, UIImage, UIImageView, UIView;

@interface SGQRCodeVC : SGViewController <SGShareViewDelegate>
{
    _Bool _isShowSweepCode;
    _Bool _isOver;
    _Bool _isClickMore;
    NSArray *_memberGroupUrlListArr;
    SGGroupInfo *_groupInfo;
    long long _qrcodeExpireTime;
    NSString *_qrcode;
    UIImageView *_qrCodeImageView;
    NSString *_imageURL;
    long long _uin;
    long long _groupUin;
    NSString *_name;
    unsigned long long _type;
    UIView *_QRCodeBGView;
    SGShareView *_shareView;
    UIView *_maskView;
    UIImage *_currentImage;
    SGDialogs *_dialog;
    SGButton *_inviteButton;
}

@property(nonatomic) _Bool isClickMore; // @synthesize isClickMore=_isClickMore;
@property(retain, nonatomic) SGButton *inviteButton; // @synthesize inviteButton=_inviteButton;
@property(retain, nonatomic) SGDialogs *dialog; // @synthesize dialog=_dialog;
@property(retain, nonatomic) UIImage *currentImage; // @synthesize currentImage=_currentImage;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) SGShareView *shareView; // @synthesize shareView=_shareView;
@property(nonatomic) __weak UIView *QRCodeBGView; // @synthesize QRCodeBGView=_QRCodeBGView;
@property(nonatomic) _Bool isOver; // @synthesize isOver=_isOver;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long groupUin; // @synthesize groupUin=_groupUin;
@property(nonatomic) long long uin; // @synthesize uin=_uin;
@property(retain, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) UIImageView *qrCodeImageView; // @synthesize qrCodeImageView=_qrCodeImageView;
@property(retain, nonatomic) NSString *qrcode; // @synthesize qrcode=_qrcode;
@property(nonatomic) long long qrcodeExpireTime; // @synthesize qrcodeExpireTime=_qrcodeExpireTime;
@property(nonatomic) _Bool isShowSweepCode; // @synthesize isShowSweepCode=_isShowSweepCode;
@property(retain, nonatomic) SGGroupInfo *groupInfo; // @synthesize groupInfo=_groupInfo;
@property(retain, nonatomic) NSArray *memberGroupUrlListArr; // @synthesize memberGroupUrlListArr=_memberGroupUrlListArr;
- (void).cxx_destruct;
- (void)copyGroupCommand;
- (void)pullUpShareView;
- (void)inviteAction;
- (void)loadQrcode;
- (_Bool)isLargeScreen;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveImageToPhotos:(id)arg1;
- (void)hide;
- (void)helpButtonClick;
- (void)shareWeiXinClick;
- (void)shareXianliaoClick;
- (void)cancelButtonClick;
- (void)rightItemClick;
- (id)initWithUin:(long long)arg1 withGroupUin:(long long)arg2 withQrcode:(id)arg3 withImageUrl:(id)arg4 withName:(id)arg5 withQRType:(unsigned long long)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

