//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UILongPressGestureRecognizer, UIView;
@protocol SGRemarkPhoneCellDelegate;

@interface SGRemarkPhoneCell : UITableViewCell
{
    id <SGRemarkPhoneCellDelegate> _phoneDelegate;
    UILabel *_phoneLab1;
    UILabel *_phoneLab2;
    UIView *_lineV;
    UILabel *_titleLab;
    UILongPressGestureRecognizer *_longGesture;
}

@property(retain, nonatomic) UILongPressGestureRecognizer *longGesture; // @synthesize longGesture=_longGesture;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIView *lineV; // @synthesize lineV=_lineV;
@property(retain, nonatomic) UILabel *phoneLab2; // @synthesize phoneLab2=_phoneLab2;
@property(retain, nonatomic) UILabel *phoneLab1; // @synthesize phoneLab1=_phoneLab1;
@property(nonatomic) __weak id <SGRemarkPhoneCellDelegate> phoneDelegate; // @synthesize phoneDelegate=_phoneDelegate;
- (void).cxx_destruct;
- (void)changeButtonStatus:(id)arg1;
- (void)buttonClicked:(id)arg1;
- (void)tapLabAction:(id)arg1;
- (void)setRemarkPhone:(id)arg1 phone2:(id)arg2;

@end

