//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSString;

@interface SGRevTransAccountsResp : SGHTTPSResponseModel
{
    unsigned char _transferStatus;
    long long _sendUserId;
    NSString *_sendUserSmallAvatarUrl;
    NSString *_sendUserNickName;
    long long _transferAmount;
    NSString *_desc;
    long long _receiveUserId;
    NSString *_receiveUserNickName;
    long long _transferReceiveTime;
}

+ (int)constructor;
@property(nonatomic) long long transferReceiveTime; // @synthesize transferReceiveTime=_transferReceiveTime;
@property(copy, nonatomic) NSString *receiveUserNickName; // @synthesize receiveUserNickName=_receiveUserNickName;
@property(nonatomic) long long receiveUserId; // @synthesize receiveUserId=_receiveUserId;
@property(nonatomic) unsigned char transferStatus; // @synthesize transferStatus=_transferStatus;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) long long transferAmount; // @synthesize transferAmount=_transferAmount;
@property(copy, nonatomic) NSString *sendUserNickName; // @synthesize sendUserNickName=_sendUserNickName;
@property(copy, nonatomic) NSString *sendUserSmallAvatarUrl; // @synthesize sendUserSmallAvatarUrl=_sendUserSmallAvatarUrl;
@property(nonatomic) long long sendUserId; // @synthesize sendUserId=_sendUserId;
- (void).cxx_destruct;

@end

