//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSMutableDictionary;

@interface SGRequestCMdidModel : NSObject <NSCoding>
{
    long long _sicknessIPCount;
    double _addSicknessIPCountTime;
    NSMutableDictionary *_cmdidTimerDic;
}

+ (id)requestCMdidModelFilePath;
+ (id)getRequestCMdidModel;
@property(retain, nonatomic) NSMutableDictionary *cmdidTimerDic; // @synthesize cmdidTimerDic=_cmdidTimerDic;
@property(nonatomic) double addSicknessIPCountTime; // @synthesize addSicknessIPCountTime=_addSicknessIPCountTime;
@property(nonatomic) long long sicknessIPCount; // @synthesize sicknessIPCount=_sicknessIPCount;
- (void).cxx_destruct;
- (void)archieveRequestCMdidModel;
- (void)clearData;
- (void)addSicknessIPCount;
@property(readonly, nonatomic) _Bool threeCmdidInMinOutTime;
- (void)addOutTimerCMdid:(int)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

