//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface SGReportAppleReceiptReq : SGHTTPSReqModel
{
    NSString *_receipt;
    NSString *_orderId;
}

@property(copy, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(copy, nonatomic) NSString *receipt; // @synthesize receipt=_receipt;
- (void).cxx_destruct;
- (int)constructor;

@end

