//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGRefundBuyerExpressVO : NSObject
{
    NSString *_expressName;
    NSString *_expressIconUrl;
    NSString *_expressNo;
    NSString *_expressExplain;
    NSString *_pictureUrlList;
}

@property(copy, nonatomic) NSString *pictureUrlList; // @synthesize pictureUrlList=_pictureUrlList;
@property(copy, nonatomic) NSString *expressExplain; // @synthesize expressExplain=_expressExplain;
@property(copy, nonatomic) NSString *expressNo; // @synthesize expressNo=_expressNo;
@property(copy, nonatomic) NSString *expressIconUrl; // @synthesize expressIconUrl=_expressIconUrl;
@property(copy, nonatomic) NSString *expressName; // @synthesize expressName=_expressName;
- (void).cxx_destruct;

@end

