//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

@class NSLayoutConstraint, SGNewGetRealNameInfoResp, UILabel, UIView;

@interface SGRealNameedController : SGViewController
{
    _Bool _haveCleanReamCach;
    SGNewGetRealNameInfoResp *_resp;
    CDUnknownBlockType _changeReamBlock;
    UILabel *_titleLabel;
    UIView *_nameLabelView;
    UIView *_credentialsView;
    UIView *_numberView;
    UILabel *_nameTitleLabel;
    UILabel *_nameContentLabel;
    UILabel *_credentialsTitleLabel;
    UILabel *_credentialsContentLabel;
    UILabel *_numberTitleLabel;
    UILabel *_numberContentLabel;
    UIView *_aliRealMan;
    UILabel *_aliReanManTitleLabel;
    UILabel *_aliRealManResultLabel;
    NSLayoutConstraint *_aliRealManIVWidth;
    NSLayoutConstraint *_aliRealManIVGap;
}

@property(nonatomic) _Bool haveCleanReamCach; // @synthesize haveCleanReamCach=_haveCleanReamCach;
@property(nonatomic) __weak NSLayoutConstraint *aliRealManIVGap; // @synthesize aliRealManIVGap=_aliRealManIVGap;
@property(nonatomic) __weak NSLayoutConstraint *aliRealManIVWidth; // @synthesize aliRealManIVWidth=_aliRealManIVWidth;
@property(nonatomic) __weak UILabel *aliRealManResultLabel; // @synthesize aliRealManResultLabel=_aliRealManResultLabel;
@property(nonatomic) __weak UILabel *aliReanManTitleLabel; // @synthesize aliReanManTitleLabel=_aliReanManTitleLabel;
@property(nonatomic) __weak UIView *aliRealMan; // @synthesize aliRealMan=_aliRealMan;
@property(nonatomic) __weak UILabel *numberContentLabel; // @synthesize numberContentLabel=_numberContentLabel;
@property(nonatomic) __weak UILabel *numberTitleLabel; // @synthesize numberTitleLabel=_numberTitleLabel;
@property(nonatomic) __weak UILabel *credentialsContentLabel; // @synthesize credentialsContentLabel=_credentialsContentLabel;
@property(nonatomic) __weak UILabel *credentialsTitleLabel; // @synthesize credentialsTitleLabel=_credentialsTitleLabel;
@property(nonatomic) __weak UILabel *nameContentLabel; // @synthesize nameContentLabel=_nameContentLabel;
@property(nonatomic) __weak UILabel *nameTitleLabel; // @synthesize nameTitleLabel=_nameTitleLabel;
@property(nonatomic) __weak UIView *numberView; // @synthesize numberView=_numberView;
@property(nonatomic) __weak UIView *credentialsView; // @synthesize credentialsView=_credentialsView;
@property(nonatomic) __weak UIView *nameLabelView; // @synthesize nameLabelView=_nameLabelView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType changeReamBlock; // @synthesize changeReamBlock=_changeReamBlock;
@property(retain, nonatomic) SGNewGetRealNameInfoResp *resp; // @synthesize resp=_resp;
- (void).cxx_destruct;
- (void)aliRealManAction;
- (void)reloadRealyMan;
- (void)reloadReamContent;
- (void)cleanReam;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

