//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SGCopyTextView, SGRobetDetailCardDesripModel, UILabel;

@interface SGRobetCardDetailCell : UITableViewCell
{
    SGRobetDetailCardDesripModel *_model;
    double _keyWidth;
    UILabel *_introleftLab;
    SGCopyTextView *_contextView;
}

@property(retain, nonatomic) SGCopyTextView *contextView; // @synthesize contextView=_contextView;
@property(retain, nonatomic) UILabel *introleftLab; // @synthesize introleftLab=_introleftLab;
@property(nonatomic) double keyWidth; // @synthesize keyWidth=_keyWidth;
@property(retain, nonatomic) SGRobetDetailCardDesripModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

