//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

#import "SGCombatListViewDelegate-Protocol.h"

@class NSString, SGCombatListView, UIImageView, UILabel, UIView;

@interface SGRobetShareCombatCell : SGDialogDeatilBaseCell <SGCombatListViewDelegate>
{
    UIView *_topBackView;
    UILabel *_titleLabel;
    UILabel *_lightTitleLabel;
    UIView *_topLineView;
    UIImageView *_gameImageView;
    UILabel *_gameNameLabel;
    SGCombatListView *_combatListView;
}

@property(nonatomic) __weak SGCombatListView *combatListView; // @synthesize combatListView=_combatListView;
@property(nonatomic) __weak UILabel *gameNameLabel; // @synthesize gameNameLabel=_gameNameLabel;
@property(nonatomic) __weak UIImageView *gameImageView; // @synthesize gameImageView=_gameImageView;
@property(nonatomic) __weak UIView *topLineView; // @synthesize topLineView=_topLineView;
@property(nonatomic) __weak UILabel *lightTitleLabel; // @synthesize lightTitleLabel=_lightTitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIView *topBackView; // @synthesize topBackView=_topBackView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)longTapTableView;
- (void)tapTableView;
- (void)tapButtonRequest:(id)arg1;
- (void)setModel:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

