//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSMutableArray, NSString, SGCouponTemplateInfoVO;

@interface SGScanCouponQrCodeResp : SGHTTPSResponseModel
{
    _Bool _joinFlag;
    _Bool _useFlag;
    _Bool _getFlag;
    int _totalMemberNumber;
    long long _invitedFromUid;
    NSString *_invitedFromNickName;
    NSString *_invitedFromSmallAvatarUrl;
    long long _groupId;
    NSString *_groupTitle;
    NSMutableArray *_groupMemberSmallAvatarUrlList;
    long long _sendId;
    long long _templateId;
    SGCouponTemplateInfoVO *_couponTemplateInfoVO;
}

+ (int)constructor;
@property(retain, nonatomic) SGCouponTemplateInfoVO *couponTemplateInfoVO; // @synthesize couponTemplateInfoVO=_couponTemplateInfoVO;
@property(nonatomic) _Bool getFlag; // @synthesize getFlag=_getFlag;
@property(nonatomic) _Bool useFlag; // @synthesize useFlag=_useFlag;
@property(nonatomic) long long templateId; // @synthesize templateId=_templateId;
@property(nonatomic) long long sendId; // @synthesize sendId=_sendId;
@property(retain, nonatomic) NSMutableArray *groupMemberSmallAvatarUrlList; // @synthesize groupMemberSmallAvatarUrlList=_groupMemberSmallAvatarUrlList;
@property(nonatomic) int totalMemberNumber; // @synthesize totalMemberNumber=_totalMemberNumber;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
@property(copy, nonatomic) NSString *invitedFromSmallAvatarUrl; // @synthesize invitedFromSmallAvatarUrl=_invitedFromSmallAvatarUrl;
@property(copy, nonatomic) NSString *invitedFromNickName; // @synthesize invitedFromNickName=_invitedFromNickName;
@property(nonatomic) long long invitedFromUid; // @synthesize invitedFromUid=_invitedFromUid;
@property(nonatomic) _Bool joinFlag; // @synthesize joinFlag=_joinFlag;
- (void).cxx_destruct;

@end

