//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSMutableArray, NSString;

@interface SGScanGoodsQrCodeResp : SGHTTPSResponseModel
{
    _Bool _joinFlag;
    _Bool _groupbuyFlag;
    int _totalMemberNumber;
    int _momentShareTimes;
    long long _invitedFromUid;
    NSString *_invitedFromNickName;
    NSString *_invitedFromSmallAvatarUrl;
    long long _groupId;
    NSString *_groupTitle;
    NSMutableArray *_groupMemberSmallAvatarUrlList;
    long long _goodsId;
    NSString *_goodsName;
    NSString *_firstGoodsPhotoUrl;
    NSString *_h5Url;
    long long _minSalePrice;
    long long _activityId;
    long long _spikeOrigPrice;
    long long _spikePrice;
    long long _relevantTagPrice;
    long long _promoActivityId;
    NSString *_activityPriceName;
    long long _spikeBeginningTime;
    long long _spikeClosingTime;
    NSString *_groupbuyPriceAlias;
    long long _minGroupbuyPrice;
}

+ (int)constructor;
@property(nonatomic) long long minGroupbuyPrice; // @synthesize minGroupbuyPrice=_minGroupbuyPrice;
@property(retain, nonatomic) NSString *groupbuyPriceAlias; // @synthesize groupbuyPriceAlias=_groupbuyPriceAlias;
@property(nonatomic) _Bool groupbuyFlag; // @synthesize groupbuyFlag=_groupbuyFlag;
@property(nonatomic) long long spikeClosingTime; // @synthesize spikeClosingTime=_spikeClosingTime;
@property(nonatomic) long long spikeBeginningTime; // @synthesize spikeBeginningTime=_spikeBeginningTime;
@property(nonatomic) int momentShareTimes; // @synthesize momentShareTimes=_momentShareTimes;
@property(copy, nonatomic) NSString *activityPriceName; // @synthesize activityPriceName=_activityPriceName;
@property(nonatomic) long long promoActivityId; // @synthesize promoActivityId=_promoActivityId;
@property(nonatomic) long long relevantTagPrice; // @synthesize relevantTagPrice=_relevantTagPrice;
@property(nonatomic) long long spikePrice; // @synthesize spikePrice=_spikePrice;
@property(nonatomic) long long spikeOrigPrice; // @synthesize spikeOrigPrice=_spikeOrigPrice;
@property(nonatomic) long long activityId; // @synthesize activityId=_activityId;
@property(nonatomic) long long minSalePrice; // @synthesize minSalePrice=_minSalePrice;
@property(copy, nonatomic) NSString *h5Url; // @synthesize h5Url=_h5Url;
@property(copy, nonatomic) NSString *firstGoodsPhotoUrl; // @synthesize firstGoodsPhotoUrl=_firstGoodsPhotoUrl;
@property(copy, nonatomic) NSString *goodsName; // @synthesize goodsName=_goodsName;
@property(nonatomic) long long goodsId; // @synthesize goodsId=_goodsId;
@property(retain, nonatomic) NSMutableArray *groupMemberSmallAvatarUrlList; // @synthesize groupMemberSmallAvatarUrlList=_groupMemberSmallAvatarUrlList;
@property(nonatomic) int totalMemberNumber; // @synthesize totalMemberNumber=_totalMemberNumber;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
@property(copy, nonatomic) NSString *invitedFromSmallAvatarUrl; // @synthesize invitedFromSmallAvatarUrl=_invitedFromSmallAvatarUrl;
@property(copy, nonatomic) NSString *invitedFromNickName; // @synthesize invitedFromNickName=_invitedFromNickName;
@property(nonatomic) long long invitedFromUid; // @synthesize invitedFromUid=_invitedFromUid;
@property(nonatomic) _Bool joinFlag; // @synthesize joinFlag=_joinFlag;
- (void).cxx_destruct;

@end

