//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "ZPassWordViewDelegate-Protocol.h"

@class NSString, SGFirstBindingBankCardReqModel, SGNewGetRealNameInfoResp, UILabel, UIViewController, ZPassWordView;

@interface SGSetPayPasswordController : SGViewController <ZPassWordViewDelegate>
{
    _Bool _isModifyPassword;
    _Bool _isForgetPayPassword;
    _Bool _isTLReanAuth;
    _Bool _isSearchPhoneNeedCertify;
    _Bool _isFromReanName;
    _Bool _isSet;
    NSString *_validStr;
    CDUnknownBlockType _setSuccessBlock;
    SGFirstBindingBankCardReqModel *_firstBindingBankCardReqModelreq;
    UIViewController *_profileInfoVC;
    UIViewController *_weakLastViewVC;
    SGNewGetRealNameInfoResp *_infoResp;
    UILabel *_topTipsLab;
    ZPassWordView *_passwordView;
    UILabel *_errorLab;
    NSString *_firstPassword;
    NSString *_secondPassword;
    NSString *_thirdPassoword;
}

@property(nonatomic) _Bool isSet; // @synthesize isSet=_isSet;
@property(retain, nonatomic) NSString *thirdPassoword; // @synthesize thirdPassoword=_thirdPassoword;
@property(retain, nonatomic) NSString *secondPassword; // @synthesize secondPassword=_secondPassword;
@property(retain, nonatomic) NSString *firstPassword; // @synthesize firstPassword=_firstPassword;
@property(retain, nonatomic) UILabel *errorLab; // @synthesize errorLab=_errorLab;
@property(retain, nonatomic) ZPassWordView *passwordView; // @synthesize passwordView=_passwordView;
@property(nonatomic) __weak UILabel *topTipsLab; // @synthesize topTipsLab=_topTipsLab;
@property(nonatomic) _Bool isFromReanName; // @synthesize isFromReanName=_isFromReanName;
@property(nonatomic) _Bool isSearchPhoneNeedCertify; // @synthesize isSearchPhoneNeedCertify=_isSearchPhoneNeedCertify;
@property(retain, nonatomic) SGNewGetRealNameInfoResp *infoResp; // @synthesize infoResp=_infoResp;
@property(nonatomic) _Bool isTLReanAuth; // @synthesize isTLReanAuth=_isTLReanAuth;
@property(nonatomic) __weak UIViewController *weakLastViewVC; // @synthesize weakLastViewVC=_weakLastViewVC;
@property(nonatomic) __weak UIViewController *profileInfoVC; // @synthesize profileInfoVC=_profileInfoVC;
@property(retain, nonatomic) SGFirstBindingBankCardReqModel *firstBindingBankCardReqModelreq; // @synthesize firstBindingBankCardReqModelreq=_firstBindingBankCardReqModelreq;
@property(copy, nonatomic) CDUnknownBlockType setSuccessBlock; // @synthesize setSuccessBlock=_setSuccessBlock;
@property(nonatomic) _Bool isForgetPayPassword; // @synthesize isForgetPayPassword=_isForgetPayPassword;
@property(retain, nonatomic) NSString *validStr; // @synthesize validStr=_validStr;
@property(nonatomic) _Bool isModifyPassword; // @synthesize isModifyPassword=_isModifyPassword;
- (void).cxx_destruct;
- (void)showTwicePasswordDifferentAlert;
- (void)back;
- (void)setAction;
- (void)requestPassword:(id)arg1;
- (void)ValidatePayAction;
- (void)backAction;
- (void)passWordTextDidChange:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

