//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SGSellerOrderCountVO : NSObject
{
    int _unDeliveredNumber;
    int _deliveredNumber;
    int _unSettledNumber;
}

@property(nonatomic) int unSettledNumber; // @synthesize unSettledNumber=_unSettledNumber;
@property(nonatomic) int deliveredNumber; // @synthesize deliveredNumber=_deliveredNumber;
@property(nonatomic) int unDeliveredNumber; // @synthesize unDeliveredNumber=_unDeliveredNumber;

@end

