//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, SGGroupInfo, SGSearchNullView, UISearchController, UITableView;
@protocol SGSearchMemberViewDelegate;

@interface SGSearchMemberViewController : SGViewController <UITableViewDelegate, UITableViewDataSource, UISearchResultsUpdating>
{
    NSArray *_allmembers;
    UISearchController *_searchController;
    SGGroupInfo *_groupInfo;
    id <SGSearchMemberViewDelegate> _delegate;
    UITableView *_tableView;
    NSMutableArray *_dataSource;
    SGSearchNullView *_nullView;
}

@property(retain, nonatomic) SGSearchNullView *nullView; // @synthesize nullView=_nullView;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <SGSearchMemberViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SGGroupInfo *groupInfo; // @synthesize groupInfo=_groupInfo;
@property(nonatomic) __weak UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) NSArray *allmembers; // @synthesize allmembers=_allmembers;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

