//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSReqModel.h"

@class NSString;

@interface SGSendUserPacketFromAlipayReq : SGHTTPSReqModel
{
    NSString *_out_order_no;
    NSString *_out_request_no;
    NSString *_wishContent;
    long long _revUserId;
    long long _packetAmount;
    long long _packetId;
}

@property(nonatomic) long long packetId; // @synthesize packetId=_packetId;
@property(nonatomic) long long packetAmount; // @synthesize packetAmount=_packetAmount;
@property(nonatomic) long long revUserId; // @synthesize revUserId=_revUserId;
@property(copy, nonatomic) NSString *wishContent; // @synthesize wishContent=_wishContent;
@property(copy, nonatomic) NSString *out_request_no; // @synthesize out_request_no=_out_request_no;
@property(copy, nonatomic) NSString *out_order_no; // @synthesize out_order_no=_out_order_no;
- (void).cxx_destruct;
- (int)constructor;

@end

