//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, SGDialogs, UIImageView, UILabel, UIView;

@interface SGSearchDialogListCell : UITableViewCell
{
    SGDialogs *_dialog;
    NSString *_searchContent;
    UILabel *_introLab;
    UILabel *_topNickLab;
    UILabel *_onlyShowNickLab;
    UIView *_lineView;
    UIImageView *_avatarView;
}

@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *onlyShowNickLab; // @synthesize onlyShowNickLab=_onlyShowNickLab;
@property(retain, nonatomic) UILabel *topNickLab; // @synthesize topNickLab=_topNickLab;
@property(retain, nonatomic) UILabel *introLab; // @synthesize introLab=_introLab;
@property(copy, nonatomic) NSString *searchContent; // @synthesize searchContent=_searchContent;
@property(retain, nonatomic) SGDialogs *dialog; // @synthesize dialog=_dialog;
- (void).cxx_destruct;
- (void)refershIcon:(id)arg1;
- (void)creatChildView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

