//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class SGSpikeActivityVO, UILabel, UIView;

@interface SGSecondKillHeadCell : UICollectionViewCell
{
    SGSpikeActivityVO *_model;
    UILabel *_timeLab;
    UILabel *_stateLab;
    UIView *_bkgView;
}

@property(retain, nonatomic) UIView *bkgView; // @synthesize bkgView=_bkgView;
@property(retain, nonatomic) UILabel *stateLab; // @synthesize stateLab=_stateLab;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) SGSpikeActivityVO *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

