//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, SGGetBankCardDetailByCardNoResp, SGNewGetRealNameInfoResp, SGPayAlertView, UIButton, UILabel, UITextField;

@interface SGSecondAddBankViewController : SGViewController <UITextFieldDelegate>
{
    SGGetBankCardDetailByCardNoResp *_carInfoResp;
    SGNewGetRealNameInfoResp *_infoResp;
    NSString *_bankNumber;
    UILabel *_carTypeLab;
    UITextField *_phoneTextField;
    UIButton *_protocolButton;
    UIButton *_agreeButton;
    UIButton *_nextButton;
    SGPayAlertView *_payalertView;
}

@property(retain, nonatomic) SGPayAlertView *payalertView; // @synthesize payalertView=_payalertView;
@property(retain, nonatomic) UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) UIButton *agreeButton; // @synthesize agreeButton=_agreeButton;
@property(retain, nonatomic) UIButton *protocolButton; // @synthesize protocolButton=_protocolButton;
@property(retain, nonatomic) UITextField *phoneTextField; // @synthesize phoneTextField=_phoneTextField;
@property(retain, nonatomic) UILabel *carTypeLab; // @synthesize carTypeLab=_carTypeLab;
@property(copy, nonatomic) NSString *bankNumber; // @synthesize bankNumber=_bankNumber;
@property(retain, nonatomic) SGNewGetRealNameInfoResp *infoResp; // @synthesize infoResp=_infoResp;
@property(retain, nonatomic) SGGetBankCardDetailByCardNoResp *carInfoResp; // @synthesize carInfoResp=_carInfoResp;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)getWhiteBkgView;
- (void)goBackViewController;
- (void)requestAddBank:(id)arg1;
- (void)buttonClickNext;
- (void)showProrocol;
- (void)agreddButtonClick;
- (void)setNextButtonEnable;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textDidChange:(id)arg1;
- (void)tapChooseBankName;
- (void)setData;
- (void)showQuestion;
- (void)creatChildView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

