//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGGoodsBaseViewController.h"

#import "ASWatcher-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ASHandle, AddressVO, NSMutableArray, NSString, SGCouponReceiveVO, SGGetOrderActualPayAmountResp, SGGetXmallPaymentChannelListResp, SGNewGetRealNameInfoResp, SGSendPacketPayView, SGSubmitOrderResp, SGTLAccountBalanceResp, UIImageView, UILabel, UITableView, UIView;

@interface SGShopCartPreParyBuyViewController : SGGoodsBaseViewController <UITableViewDataSource, UITableViewDelegate, ASWatcher>
{
    _Bool _isJumpToAddBank;
    _Bool _isNeedExpress;
    _Bool _isUserCoupons;
    _Bool _isReamOrSetPassWord;
    _Bool _isWeiXinPay;
    int _canUserCouponsTotalNum;
    long long _groupID;
    SGGetOrderActualPayAmountResp *_actualPayResp;
    NSMutableArray *_waitPayArray;
    UITableView *_tableView;
    UIView *_tableHeadView;
    UIView *_noAddressView;
    UIView *_addressView;
    UILabel *_addressLab;
    UILabel *_receiveNameLab;
    UIView *_moneySureView;
    UILabel *_couponsMoneyLab;
    UILabel *_redTotalMoneyLab;
    AddressVO *_addressModel;
    SGTLAccountBalanceResp *_accountResp;
    SGSendPacketPayView *_payAlertView;
    SGNewGetRealNameInfoResp *_realNameInfoResp;
    SGSubmitOrderResp *_submitOrderResp;
    SGCouponReceiveVO *_couponsM;
    UILabel *_groupAddressLab;
    UIImageView *_addressBottomLineV;
    SGGetXmallPaymentChannelListResp *_payListResp;
    ASHandle *_actionHandle;
}

@property(nonatomic) _Bool isWeiXinPay; // @synthesize isWeiXinPay=_isWeiXinPay;
@property(nonatomic) _Bool isReamOrSetPassWord; // @synthesize isReamOrSetPassWord=_isReamOrSetPassWord;
@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
@property(retain, nonatomic) SGGetXmallPaymentChannelListResp *payListResp; // @synthesize payListResp=_payListResp;
@property(nonatomic) __weak UIImageView *addressBottomLineV; // @synthesize addressBottomLineV=_addressBottomLineV;
@property(retain, nonatomic) UILabel *groupAddressLab; // @synthesize groupAddressLab=_groupAddressLab;
@property(nonatomic) int canUserCouponsTotalNum; // @synthesize canUserCouponsTotalNum=_canUserCouponsTotalNum;
@property(nonatomic) _Bool isUserCoupons; // @synthesize isUserCoupons=_isUserCoupons;
@property(retain, nonatomic) SGCouponReceiveVO *couponsM; // @synthesize couponsM=_couponsM;
@property(retain, nonatomic) SGSubmitOrderResp *submitOrderResp; // @synthesize submitOrderResp=_submitOrderResp;
@property(nonatomic) _Bool isNeedExpress; // @synthesize isNeedExpress=_isNeedExpress;
@property(nonatomic) _Bool isJumpToAddBank; // @synthesize isJumpToAddBank=_isJumpToAddBank;
@property(retain, nonatomic) SGNewGetRealNameInfoResp *realNameInfoResp; // @synthesize realNameInfoResp=_realNameInfoResp;
@property(retain, nonatomic) SGSendPacketPayView *payAlertView; // @synthesize payAlertView=_payAlertView;
@property(retain, nonatomic) SGTLAccountBalanceResp *accountResp; // @synthesize accountResp=_accountResp;
@property(retain, nonatomic) AddressVO *addressModel; // @synthesize addressModel=_addressModel;
@property(retain, nonatomic) UILabel *redTotalMoneyLab; // @synthesize redTotalMoneyLab=_redTotalMoneyLab;
@property(retain, nonatomic) UILabel *couponsMoneyLab; // @synthesize couponsMoneyLab=_couponsMoneyLab;
@property(retain, nonatomic) UIView *moneySureView; // @synthesize moneySureView=_moneySureView;
@property(retain, nonatomic) UILabel *receiveNameLab; // @synthesize receiveNameLab=_receiveNameLab;
@property(retain, nonatomic) UILabel *addressLab; // @synthesize addressLab=_addressLab;
@property(retain, nonatomic) UIView *addressView; // @synthesize addressView=_addressView;
@property(retain, nonatomic) UIView *noAddressView; // @synthesize noAddressView=_noAddressView;
@property(retain, nonatomic) UIView *tableHeadView; // @synthesize tableHeadView=_tableHeadView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *waitPayArray; // @synthesize waitPayArray=_waitPayArray;
@property(retain, nonatomic) SGGetOrderActualPayAmountResp *actualPayResp; // @synthesize actualPayResp=_actualPayResp;
@property(nonatomic) long long groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)dealloc;
- (void)sgExit;
- (void)checkIsPayPassword:(CDUnknownBlockType)arg1;
- (void)checkIsRealNameAuth:(CDUnknownBlockType)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)payrequestResponse:(id)arg1;
- (void)payGoodsWithPassword:(id)arg1 withPayWayModel:(id)arg2;
- (void)requestApplyOrderNo:(CDUnknownBlockType)arg1;
- (void)getPayListWay;
- (void)payWithWeiXin;
- (void)payWithCustomTlBalance;
- (void)showPayChooseView:(id)arg1;
- (void)judgePayWhichWay;
- (void)beginPay;
- (void)clickPay;
- (void)requestChangeCoupons:(_Bool)arg1 withModel:(id)arg2;
- (void)chhoseCoupons;
- (void)updateAddressShow:(_Bool)arg1;
- (void)enterMyAddress;
- (void)actionStageResourceDispatched:(id)arg1 resource:(id)arg2 arguments:(id)arg3;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)getMyBalance:(_Bool)arg1 nextBlock:(CDUnknownBlockType)arg2;
- (void)backAction;
- (void)setData;
- (void)creatChildView;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

