//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSArray;

@interface SGShowGroupGoldenBeanCharmListResp : SGHTTPSResponseModel
{
    NSArray *_detailList;
    long long _totalCharm;
}

+ (int)constructor;
@property(nonatomic) long long totalCharm; // @synthesize totalCharm=_totalCharm;
@property(retain, nonatomic) NSArray *detailList; // @synthesize detailList=_detailList;
- (void).cxx_destruct;

@end

