//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class AddressVO, NSArray, NSString, SGCouponReceiveVO, SGGroupbuyTeam;

@interface SGShowOrderResp : SGHTTPSResponseModel
{
    _Bool _expressFlag;
    _Bool _activityFlag;
    _Bool _refundLimitFlag;
    int _orderGoodsType;
    int _refundStatus;
    NSString *_orderNo;
    NSString *_groupTitle;
    NSString *_groupIconUrl;
    long long _groupId;
    long long _orderBuyerStatus;
    long long _orderSellerStatus;
    NSString *_orderSellerStatusDesc;
    NSString *_orderBuyerStatusDesc;
    long long _sellerUserId;
    long long _buyerUserId;
    NSString *_buyerNickname;
    NSString *_buyerSmallAvatarUrl;
    NSString *_channelName;
    NSString *_channelTransactionNo;
    long long _submitOrderTime;
    long long _payTime;
    long long _settleTime;
    long long _orderTotalAmount;
    long long _payAmount;
    long long _totalCommission;
    long long _totalGoldenbeanNum;
    NSString *_expressInfo;
    long long _activityId;
    NSArray *_goodsItemDetailList;
    long long _totalDiscountAmount;
    SGCouponReceiveVO *_couponReceiveVO;
    AddressVO *_addressVO;
    long long _sellerExpireTime;
    NSString *_momentExtraInfo;
    long long _systemCurrentTime;
    SGGroupbuyTeam *_groupbuyTeam;
}

+ (id)modelContainerPropertyGenericClass;
+ (int)constructor;
@property(retain, nonatomic) SGGroupbuyTeam *groupbuyTeam; // @synthesize groupbuyTeam=_groupbuyTeam;
@property(nonatomic) long long systemCurrentTime; // @synthesize systemCurrentTime=_systemCurrentTime;
@property(copy, nonatomic) NSString *momentExtraInfo; // @synthesize momentExtraInfo=_momentExtraInfo;
@property(nonatomic) long long sellerExpireTime; // @synthesize sellerExpireTime=_sellerExpireTime;
@property(nonatomic) _Bool refundLimitFlag; // @synthesize refundLimitFlag=_refundLimitFlag;
@property(nonatomic) int refundStatus; // @synthesize refundStatus=_refundStatus;
@property(retain, nonatomic) AddressVO *addressVO; // @synthesize addressVO=_addressVO;
@property(retain, nonatomic) SGCouponReceiveVO *couponReceiveVO; // @synthesize couponReceiveVO=_couponReceiveVO;
@property(nonatomic) long long totalDiscountAmount; // @synthesize totalDiscountAmount=_totalDiscountAmount;
@property(nonatomic) int orderGoodsType; // @synthesize orderGoodsType=_orderGoodsType;
@property(retain, nonatomic) NSArray *goodsItemDetailList; // @synthesize goodsItemDetailList=_goodsItemDetailList;
@property(nonatomic) long long activityId; // @synthesize activityId=_activityId;
@property(nonatomic) _Bool activityFlag; // @synthesize activityFlag=_activityFlag;
@property(nonatomic) _Bool expressFlag; // @synthesize expressFlag=_expressFlag;
@property(copy, nonatomic) NSString *expressInfo; // @synthesize expressInfo=_expressInfo;
@property(nonatomic) long long totalGoldenbeanNum; // @synthesize totalGoldenbeanNum=_totalGoldenbeanNum;
@property(nonatomic) long long totalCommission; // @synthesize totalCommission=_totalCommission;
@property(nonatomic) long long payAmount; // @synthesize payAmount=_payAmount;
@property(nonatomic) long long orderTotalAmount; // @synthesize orderTotalAmount=_orderTotalAmount;
@property(nonatomic) long long settleTime; // @synthesize settleTime=_settleTime;
@property(nonatomic) long long payTime; // @synthesize payTime=_payTime;
@property(nonatomic) long long submitOrderTime; // @synthesize submitOrderTime=_submitOrderTime;
@property(copy, nonatomic) NSString *channelTransactionNo; // @synthesize channelTransactionNo=_channelTransactionNo;
@property(copy, nonatomic) NSString *channelName; // @synthesize channelName=_channelName;
@property(copy, nonatomic) NSString *buyerSmallAvatarUrl; // @synthesize buyerSmallAvatarUrl=_buyerSmallAvatarUrl;
@property(copy, nonatomic) NSString *buyerNickname; // @synthesize buyerNickname=_buyerNickname;
@property(nonatomic) long long buyerUserId; // @synthesize buyerUserId=_buyerUserId;
@property(nonatomic) long long sellerUserId; // @synthesize sellerUserId=_sellerUserId;
@property(copy, nonatomic) NSString *orderBuyerStatusDesc; // @synthesize orderBuyerStatusDesc=_orderBuyerStatusDesc;
@property(copy, nonatomic) NSString *orderSellerStatusDesc; // @synthesize orderSellerStatusDesc=_orderSellerStatusDesc;
@property(nonatomic) long long orderSellerStatus; // @synthesize orderSellerStatus=_orderSellerStatus;
@property(nonatomic) long long orderBuyerStatus; // @synthesize orderBuyerStatus=_orderBuyerStatus;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
@property(copy, nonatomic) NSString *groupIconUrl; // @synthesize groupIconUrl=_groupIconUrl;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(copy, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
- (void).cxx_destruct;
- (unsigned long long)getOrderRefundDetailType;
- (id)getNormalExpressInfo;
- (id)getVirtualExpressInfo;

@end

