//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSIndexPath, UIImageView, UILabel, UIView;

@interface SGStoreSendGiftInfoCell : UITableViewCell
{
    NSIndexPath *_indexP;
    UILabel *_titleLab;
    UILabel *_nameLab;
    UIImageView *_arrowView;
    UILabel *_consumLab;
    UIView *_lineV;
    UILabel *_leaveGoldLab;
}

@property(retain, nonatomic) UILabel *leaveGoldLab; // @synthesize leaveGoldLab=_leaveGoldLab;
@property(retain, nonatomic) UIView *lineV; // @synthesize lineV=_lineV;
@property(retain, nonatomic) UILabel *consumLab; // @synthesize consumLab=_consumLab;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) NSIndexPath *indexP; // @synthesize indexP=_indexP;
- (void).cxx_destruct;
- (void)configData:(id)arg1 leaveGold:(long long)arg2 chooseName:(id)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

