//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class SGStoreGiftListModel, UIImageView, UILabel, UIView;

@interface SGStoreGiftListCell : UICollectionViewCell
{
    SGStoreGiftListModel *_model;
    UILabel *_nameLab;
    UIImageView *_giftImageView;
    UILabel *_charmLab;
    UILabel *_consumLab;
    UIView *_bkgView;
}

@property(retain, nonatomic) UIView *bkgView; // @synthesize bkgView=_bkgView;
@property(retain, nonatomic) UILabel *consumLab; // @synthesize consumLab=_consumLab;
@property(retain, nonatomic) UILabel *charmLab; // @synthesize charmLab=_charmLab;
@property(retain, nonatomic) UIImageView *giftImageView; // @synthesize giftImageView=_giftImageView;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) SGStoreGiftListModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setChildView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

