//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SGUser, UIButton, UIImageView, UILabel;
@protocol SGStrangeViewDelegate;

@interface SGStrangePeopleView : UIView
{
    id <SGStrangeViewDelegate> _delegate;
    UIImageView *_headImageView;
    UILabel *_textLabel;
    UIButton *_addFriendButton;
    UIButton *_screenButton;
    SGUser *_user;
}

@property(retain, nonatomic) SGUser *user; // @synthesize user=_user;
@property(retain, nonatomic) UIButton *screenButton; // @synthesize screenButton=_screenButton;
@property(retain, nonatomic) UIButton *addFriendButton; // @synthesize addFriendButton=_addFriendButton;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(nonatomic) __weak id <SGStrangeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)screenButtonclick;
- (void)addFriendbuttonclick;
- (id)initWithFrame:(struct CGRect)arg1 user:(id)arg2;

@end

