//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSString;

@interface SGSubmitSpikeOrderResp : SGHTTPSResponseModel
{
    NSString *_transactionId;
    NSString *_payToken;
    NSString *_orderNo;
}

+ (int)constructor;
@property(copy, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(copy, nonatomic) NSString *payToken; // @synthesize payToken=_payToken;
@property(copy, nonatomic) NSString *transactionId; // @synthesize transactionId=_transactionId;
- (void).cxx_destruct;

@end

