//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class SGBadgeButton, SGRedDotButton, UITabBarItem, UIView;

@interface SGTabBarButton : UIButton
{
    UITabBarItem *_item;
    SGRedDotButton *_redDotButton;
    SGBadgeButton *_badgeButton;
    UIView *_badgeView;
}

@property(retain, nonatomic) UIView *badgeView; // @synthesize badgeView=_badgeView;
@property(nonatomic) __weak SGBadgeButton *badgeButton; // @synthesize badgeButton=_badgeButton;
@property(nonatomic) __weak SGRedDotButton *redDotButton; // @synthesize redDotButton=_redDotButton;
@property(retain, nonatomic) UITabBarItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)removeBadgeOnItemIndex;
- (void)showBadgeOnItemIndex;
- (void)setupRedDotButton;
- (void)setupBadgeButton;
- (id)initWithFrame:(struct CGRect)arg1;

@end

