//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGTableViewCell.h"

@class UIImageView, UILabel;

@interface SGTipsCell : SGTableViewCell
{
    UILabel *_titleLab;
    UILabel *_tipsLab;
    UIImageView *_tipsIcon;
}

@property(retain, nonatomic) UIImageView *tipsIcon; // @synthesize tipsIcon=_tipsIcon;
@property(retain, nonatomic) UILabel *tipsLab; // @synthesize tipsLab=_tipsLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
- (void).cxx_destruct;
- (void)setTitle:(id)arg1 withTipsIcon:(id)arg2 withTips:(id)arg3;

@end

