//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGBaseSettingController.h"

#import "ASWatcher-Protocol.h"
#import "SGLTBalanceHeadViewDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class ASHandle, NSString, SGBalanceCellModel, SGIsPayPasswdSetResp, SGLTBalanceHeadView, SGTLAccountBalanceResp, SGTLGetBankListResp, UIColor, UIView;

@interface SGTLBalanceController : SGBaseSettingController <SGLTBalanceHeadViewDelegate, UINavigationControllerDelegate, ASWatcher>
{
    SGTLAccountBalanceResp *_accountBalance;
    SGIsPayPasswdSetResp *_isPayPassWord;
    SGTLGetBankListResp *_getBankCardListResp;
    SGLTBalanceHeadView *_changeHeaderView;
    SGBalanceCellModel *_bankCell;
    UIColor *_tableViewOldBackColor;
    ASHandle *_actionHandle;
    UIView *_tableFotView;
}

@property(retain, nonatomic) UIView *tableFotView; // @synthesize tableFotView=_tableFotView;
@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
@property(retain, nonatomic) UIColor *tableViewOldBackColor; // @synthesize tableViewOldBackColor=_tableViewOldBackColor;
@property(retain, nonatomic) SGBalanceCellModel *bankCell; // @synthesize bankCell=_bankCell;
@property(retain, nonatomic) SGLTBalanceHeadView *changeHeaderView; // @synthesize changeHeaderView=_changeHeaderView;
@property(retain, nonatomic) SGTLGetBankListResp *getBankCardListResp; // @synthesize getBankCardListResp=_getBankCardListResp;
@property(retain, nonatomic) SGIsPayPasswdSetResp *isPayPassWord; // @synthesize isPayPassWord=_isPayPassWord;
@property(retain, nonatomic) SGTLAccountBalanceResp *accountBalance; // @synthesize accountBalance=_accountBalance;
- (void).cxx_destruct;
- (id)getSGSectionModel;
- (void)checkIsPayPassword:(CDUnknownBlockType)arg1;
- (void)clickToTopUpPhoneFee;
- (void)jumpToAddBank;
- (void)enterFund;
- (void)SGBalanceAddBankCard;
- (void)scrollViewDidScroll:(id)arg1;
- (void)sgTableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)goToSetPassword;
- (void)gotoSGAddBankCardTableViewControllerWith;
- (void)showText:(id)arg1 delay:(double)arg2;
- (void)enterWithdraw;
- (void)judgeHaveBank:(CDUnknownBlockType)arg1;
- (void)sgchangeViewWithdrawAction;
- (void)judgeHaveGetPassWordSet:(CDUnknownBlockType)arg1;
- (void)sgchangeViewTopUpAction;
- (void)loadAccountBalance;
- (void)balanceLoadData;
- (void)showQuestion;
- (void)actionStageResourceDispatched:(id)arg1 resource:(id)arg2 arguments:(id)arg3;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

