//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGTableViewCellBase.h"

@class SGBankCardVO, UIImageView, UILabel;

@interface SGToUpTableViewCell : SGTableViewCellBase
{
    UIImageView *_iv;
    UILabel *_label;
    SGBankCardVO *_card;
}

@property(retain, nonatomic) SGBankCardVO *card; // @synthesize card=_card;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
@property(nonatomic) __weak UIImageView *iv; // @synthesize iv=_iv;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

