//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, UIButton, UITextField, UITextView;

@interface SGTopUpAndWithDrawHeaderView : UIView <UITextViewDelegate, UITextFieldDelegate>
{
    UITextField *_amountTF;
    UITextView *_balanceTipsTextView;
    unsigned long long _type;
    UIButton *_selectedBtn;
}

@property(retain, nonatomic) UIButton *selectedBtn; // @synthesize selectedBtn=_selectedBtn;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) UITextView *balanceTipsTextView; // @synthesize balanceTipsTextView=_balanceTipsTextView;
@property(retain, nonatomic) UITextField *amountTF; // @synthesize amountTF=_amountTF;
- (void).cxx_destruct;
- (void)buttonAction:(id)arg1;
- (void)textFiledChangeText;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)initView;
- (id)initViewWithType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

