//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGLqtParentViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, SGEnterLqtMainResp, SGPayAlertView, SGTLGetBankListResp, SGTransferLqtChooseModel, UIButton, UIImageView, UILabel, UITextField;

@interface SGTransferFundOutViewController : SGLqtParentViewController <UITextFieldDelegate>
{
    SGEnterLqtMainResp *_resp;
    UITextField *_amoutTextfield;
    UILabel *_leftMoneyLab;
    UILabel *_wayLab;
    UIButton *_allButton;
    UIButton *_sureButton;
    UILabel *_errorLab;
    SGPayAlertView *_payalertView;
    UIImageView *_iconView;
    SGTransferLqtChooseModel *_lqtChooseModel;
    SGTLGetBankListResp *_bankListResp;
}

@property(retain, nonatomic) SGTLGetBankListResp *bankListResp; // @synthesize bankListResp=_bankListResp;
@property(retain, nonatomic) SGTransferLqtChooseModel *lqtChooseModel; // @synthesize lqtChooseModel=_lqtChooseModel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) SGPayAlertView *payalertView; // @synthesize payalertView=_payalertView;
@property(retain, nonatomic) UILabel *errorLab; // @synthesize errorLab=_errorLab;
@property(retain, nonatomic) UIButton *sureButton; // @synthesize sureButton=_sureButton;
@property(retain, nonatomic) UIButton *allButton; // @synthesize allButton=_allButton;
@property(retain, nonatomic) UILabel *wayLab; // @synthesize wayLab=_wayLab;
@property(retain, nonatomic) UILabel *leftMoneyLab; // @synthesize leftMoneyLab=_leftMoneyLab;
@property(retain, nonatomic) UITextField *amoutTextfield; // @synthesize amoutTextfield=_amoutTextfield;
@property(retain, nonatomic) SGEnterLqtMainResp *resp; // @synthesize resp=_resp;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)clcikAll;
- (void)textDidChange;
- (id)getTextFeildAttributedPlaceholder;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)setWithdrawButtonEnable;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)showTransferCardList:(id)arg1;
- (void)chooseTransferWay;
- (void)showRequestErrorMsg:(id)arg1;
- (void)finalyRequest:(long long)arg1 password:(id)arg2;
- (void)clcikTransfer;
- (void)creatChildView;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

