//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SGUpdateGroupChatTitleNotification : NSObject
{
    long long _groupUin;
    NSString *_nwTitle;
    long long _templateId;
    NSArray *_params;
}

@property(retain, nonatomic) NSArray *params; // @synthesize params=_params;
@property(nonatomic) long long templateId; // @synthesize templateId=_templateId;
@property(retain, nonatomic) NSString *nwTitle; // @synthesize nwTitle=_nwTitle;
@property(nonatomic) long long groupUin; // @synthesize groupUin=_groupUin;
- (void).cxx_destruct;
- (void)initwithDict:(id)arg1;

@end

