//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, SGGroupMember, UIButton, UILabel, UIScrollView, UITextField;

@interface SGUserInGroupViewController : SGViewController <UITextFieldDelegate, UIScrollViewDelegate>
{
    _Bool _keyBoardlsVisible;
    int _keyBoardHeight;
    UITextField *_textTF;
    UILabel *_bottomTips;
    UIButton *_rightBtn;
    NSString *_lastContent;
    long long _uin;
    CDUnknownBlockType _completion;
    NSString *_text;
    UITextField *_phoneTF;
    UITextField *_wechatTF;
    UITextField *_alipayTF;
    UITextField *_other1TF;
    UITextField *_other2TF;
    SGGroupMember *_groupMember;
    UIScrollView *_scrollView;
}

@property(nonatomic) _Bool keyBoardlsVisible; // @synthesize keyBoardlsVisible=_keyBoardlsVisible;
@property(nonatomic) int keyBoardHeight; // @synthesize keyBoardHeight=_keyBoardHeight;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) SGGroupMember *groupMember; // @synthesize groupMember=_groupMember;
@property(retain, nonatomic) UITextField *other2TF; // @synthesize other2TF=_other2TF;
@property(retain, nonatomic) UITextField *other1TF; // @synthesize other1TF=_other1TF;
@property(retain, nonatomic) UITextField *alipayTF; // @synthesize alipayTF=_alipayTF;
@property(retain, nonatomic) UITextField *wechatTF; // @synthesize wechatTF=_wechatTF;
@property(retain, nonatomic) UITextField *phoneTF; // @synthesize phoneTF=_phoneTF;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) long long uin; // @synthesize uin=_uin;
@property(retain, nonatomic) NSString *lastContent; // @synthesize lastContent=_lastContent;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UILabel *bottomTips; // @synthesize bottomTips=_bottomTips;
@property(retain, nonatomic) UITextField *textTF; // @synthesize textTF=_textTF;
- (void).cxx_destruct;
- (void)donePressed;
- (void)cancelPressed;
- (void)endEdit;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textChangeAction;
- (void)dealloc;
- (void)loadOther2TF;
- (void)loadOther1TF;
- (void)loadAlipayTF;
- (void)loadWechatTF;
- (void)loadPhoneTF;
- (void)keyboardHide:(id)arg1;
- (void)loadTextTF;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)viewDidLoad;
- (id)initWithText:(id)arg1 withUin:(long long)arg2 withGroupMember:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

