//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGHTTPSResponseModel.h"

@class NSArray, NSString, SGCouponTemplateInfoVO;

@interface SGVerifyCouponInvitationLinkResp : SGHTTPSResponseModel
{
    _Bool _isInvitedByAdmin;
    _Bool _authorFlag;
    _Bool _joinFlag;
    _Bool _useFlag;
    _Bool _getFlag;
    int _totalMemberNumber;
    NSString *_paramString;
    NSString *_invitedFromNickName;
    NSString *_invitedFromSmallAvatarUrl;
    NSString *_groupTitle;
    NSArray *_groupMemberSmallAvatarUrlList;
    SGCouponTemplateInfoVO *_couponTemplateInfoVO;
}

+ (int)constructor;
@property(retain, nonatomic) SGCouponTemplateInfoVO *couponTemplateInfoVO; // @synthesize couponTemplateInfoVO=_couponTemplateInfoVO;
@property(nonatomic) _Bool getFlag; // @synthesize getFlag=_getFlag;
@property(nonatomic) _Bool useFlag; // @synthesize useFlag=_useFlag;
@property(retain, nonatomic) NSArray *groupMemberSmallAvatarUrlList; // @synthesize groupMemberSmallAvatarUrlList=_groupMemberSmallAvatarUrlList;
@property(nonatomic) int totalMemberNumber; // @synthesize totalMemberNumber=_totalMemberNumber;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(copy, nonatomic) NSString *invitedFromSmallAvatarUrl; // @synthesize invitedFromSmallAvatarUrl=_invitedFromSmallAvatarUrl;
@property(copy, nonatomic) NSString *invitedFromNickName; // @synthesize invitedFromNickName=_invitedFromNickName;
@property(copy, nonatomic) NSString *paramString; // @synthesize paramString=_paramString;
@property(nonatomic) _Bool joinFlag; // @synthesize joinFlag=_joinFlag;
@property(nonatomic) _Bool authorFlag; // @synthesize authorFlag=_authorFlag;
@property(nonatomic) _Bool isInvitedByAdmin; // @synthesize isInvitedByAdmin=_isInvitedByAdmin;
- (void).cxx_destruct;

@end

