//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class SGUserVipConfigPerLevel, UILabel;

@interface SGVIPButton : UIButton
{
    long long _vipLevel;
    long long _moneyPerMonth;
    SGUserVipConfigPerLevel *_config;
    UILabel *_vipLevelLabel;
}

@property(retain, nonatomic) UILabel *vipLevelLabel; // @synthesize vipLevelLabel=_vipLevelLabel;
@property(retain, nonatomic) SGUserVipConfigPerLevel *config; // @synthesize config=_config;
@property(nonatomic) long long moneyPerMonth; // @synthesize moneyPerMonth=_moneyPerMonth;
@property(nonatomic) long long vipLevel; // @synthesize vipLevel=_vipLevel;
- (void).cxx_destruct;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;

@end

