//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ASWatcher-Protocol.h"

@class ASHandle, NSString, UIBarButtonItem, UIButton, UINavigationItem, UIView;

@interface SGViewController : UIViewController <ASWatcher>
{
    _Bool _hatTargetNavigationItem;
    double _currentSizeChangeDuration;
    _Bool _isVisable;
    _Bool _didVisable;
    _Bool _dismissNotEndEdit;
    UIButton *_backBtn;
    UIView *_viewControllerStatusBarBackgroundView;
    long long _viewControllerRotatingFromOrientation;
    UINavigationItem *_targetNavigationItem;
    UIViewController *_targetNavigationTitleController;
    UIBarButtonItem *_leftBarButtonItem;
    UIBarButtonItem *_rightBarButtonItem;
    NSString *_titleText;
    UIView *_titleView;
    ASHandle *_actionHandle;
}

@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(retain, nonatomic) UIBarButtonItem *rightBarButtonItem; // @synthesize rightBarButtonItem=_rightBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *leftBarButtonItem; // @synthesize leftBarButtonItem=_leftBarButtonItem;
@property(nonatomic) __weak UIViewController *targetNavigationTitleController; // @synthesize targetNavigationTitleController=_targetNavigationTitleController;
@property(nonatomic) __weak UINavigationItem *targetNavigationItem; // @synthesize targetNavigationItem=_targetNavigationItem;
@property(nonatomic) long long viewControllerRotatingFromOrientation; // @synthesize viewControllerRotatingFromOrientation=_viewControllerRotatingFromOrientation;
@property(retain, nonatomic) UIView *viewControllerStatusBarBackgroundView; // @synthesize viewControllerStatusBarBackgroundView=_viewControllerStatusBarBackgroundView;
@property(nonatomic) _Bool dismissNotEndEdit; // @synthesize dismissNotEndEdit=_dismissNotEndEdit;
@property(nonatomic) _Bool didVisable; // @synthesize didVisable=_didVisable;
@property(nonatomic) _Bool isVisable; // @synthesize isVisable=_isVisable;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)showToastInCenter:(id)arg1;
- (void)showToast:(id)arg1;
- (void)showAlertToast:(id)arg1;
- (void)backAction;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)hideHUD;
- (void)showHUDError:(id)arg1;
- (void)showHUDSuccess:(id)arg1;
- (void)showHUDLoading;
- (id)getCurrentVC;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

