//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSArray, NSString, SGDialogs, UICollectionView;

@interface SGWallpaperListVC : SGViewController <UICollectionViewDelegate, UICollectionViewDataSource, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    SGDialogs *_dialogs;
    SGViewController *_lastConversionVC;
    NSArray *_defaultWallpaperArr;
    UICollectionView *_wallpaperCollectionView;
    NSString *_selectedImageName;
}

@property(retain, nonatomic) NSString *selectedImageName; // @synthesize selectedImageName=_selectedImageName;
@property(retain, nonatomic) UICollectionView *wallpaperCollectionView; // @synthesize wallpaperCollectionView=_wallpaperCollectionView;
@property(retain, nonatomic) NSArray *defaultWallpaperArr; // @synthesize defaultWallpaperArr=_defaultWallpaperArr;
@property(nonatomic) __weak SGViewController *lastConversionVC; // @synthesize lastConversionVC=_lastConversionVC;
@property(retain, nonatomic) SGDialogs *dialogs; // @synthesize dialogs=_dialogs;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)PhotoLibaryAction;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

