//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGDialogDeatilBaseCell.h"

@class _TtC8xianliao24SGWelfareNoticeTableView;

@interface SGWelfareNoticeCell : SGDialogDeatilBaseCell
{
    _TtC8xianliao24SGWelfareNoticeTableView *_tableView;
}

@property(retain, nonatomic) _TtC8xianliao24SGWelfareNoticeTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)dealwithData:(id)arg1;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)awakeFromNib;

@end

