//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, SGBankCardVO, SGChooseAddressView, SGGetAccountBalanceResp, SGPayAlertView, UIButton, UIImageView, UILabel, UITableView;

@interface SGWithDrawOldMoneyViewController : SGViewController <UITableViewDelegate, UITableViewDataSource>
{
    UILabel *_moneyLab;
    UILabel *_bankLab;
    UIImageView *_bankIconView;
    UILabel *_addressLab;
    UITableView *_tableView;
    UIButton *_withDrawButton;
    SGBankCardVO *_bankCard;
    SGChooseAddressView *_addressView;
    SGGetAccountBalanceResp *_moneyResp;
    SGPayAlertView *_payalertView;
}

@property(retain, nonatomic) SGPayAlertView *payalertView; // @synthesize payalertView=_payalertView;
@property(retain, nonatomic) SGGetAccountBalanceResp *moneyResp; // @synthesize moneyResp=_moneyResp;
@property(retain, nonatomic) SGChooseAddressView *addressView; // @synthesize addressView=_addressView;
@property(retain, nonatomic) SGBankCardVO *bankCard; // @synthesize bankCard=_bankCard;
@property(retain, nonatomic) UIButton *withDrawButton; // @synthesize withDrawButton=_withDrawButton;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UILabel *addressLab; // @synthesize addressLab=_addressLab;
@property(retain, nonatomic) UIImageView *bankIconView; // @synthesize bankIconView=_bankIconView;
@property(retain, nonatomic) UILabel *bankLab; // @synthesize bankLab=_bankLab;
@property(retain, nonatomic) UILabel *moneyLab; // @synthesize moneyLab=_moneyLab;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)checkRedpacketPayPassword:(CDUnknownBlockType)arg1;
- (void)updateBankAddress:(id)arg1 city:(id)arg2;
- (void)withDrawByPassword:(id)arg1;
- (void)withDrawButtonClick;
- (void)chooseBankAddress;
- (void)judgeHaveBank:(CDUnknownBlockType)arg1;
- (void)showBankAddressForBankCard;
- (void)chooseBankCardAction;
- (void)setWithdrawButtonEnable;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)creatChildView;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

