//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView;

@interface SGWithDrawCommitCell : UITableViewCell
{
    _Bool _hiddenBottomLine;
    UILabel *_leftTitleLab;
    UILabel *_rightTitleLab;
    UIView *_line;
}

@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UILabel *rightTitleLab; // @synthesize rightTitleLab=_rightTitleLab;
@property(retain, nonatomic) UILabel *leftTitleLab; // @synthesize leftTitleLab=_leftTitleLab;
@property(nonatomic) _Bool hiddenBottomLine; // @synthesize hiddenBottomLine=_hiddenBottomLine;
- (void).cxx_destruct;
- (void)configData:(id)arg1 withRightValue:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

