//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SGViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, SGApplyWithdrawIdResp, SGBankCardVO, SGGetWithdrawPoundageRateResp, SGGetWithdrawableAmountResp, SGPayAlertView, UIButton, UIImageView, UILabel, UITextField, YYLabel;

@interface SGWithDrawAmoutNewstViewController : SGViewController <UITextFieldDelegate>
{
    long long _cash;
    SGGetWithdrawPoundageRateResp *_rateResp;
    UILabel *_bankNameLab;
    UITextField *_amoutTextField;
    UIButton *_withDrawButton;
    YYLabel *_leftMoneyLab;
    UILabel *_errorLab;
    UILabel *_rateLab;
    SGPayAlertView *_payalertView;
    SGBankCardVO *_bankCard;
    SGApplyWithdrawIdResp *_withDrawIdResp;
    SGGetWithdrawableAmountResp *_withAmoutResp;
    UIImageView *_bankIconView;
}

@property(retain, nonatomic) UIImageView *bankIconView; // @synthesize bankIconView=_bankIconView;
@property(retain, nonatomic) SGGetWithdrawableAmountResp *withAmoutResp; // @synthesize withAmoutResp=_withAmoutResp;
@property(retain, nonatomic) SGApplyWithdrawIdResp *withDrawIdResp; // @synthesize withDrawIdResp=_withDrawIdResp;
@property(retain, nonatomic) SGBankCardVO *bankCard; // @synthesize bankCard=_bankCard;
@property(retain, nonatomic) SGPayAlertView *payalertView; // @synthesize payalertView=_payalertView;
@property(retain, nonatomic) UILabel *rateLab; // @synthesize rateLab=_rateLab;
@property(retain, nonatomic) UILabel *errorLab; // @synthesize errorLab=_errorLab;
@property(retain, nonatomic) YYLabel *leftMoneyLab; // @synthesize leftMoneyLab=_leftMoneyLab;
@property(retain, nonatomic) UIButton *withDrawButton; // @synthesize withDrawButton=_withDrawButton;
@property(retain, nonatomic) UITextField *amoutTextField; // @synthesize amoutTextField=_amoutTextField;
@property(retain, nonatomic) UILabel *bankNameLab; // @synthesize bankNameLab=_bankNameLab;
@property(retain, nonatomic) SGGetWithdrawPoundageRateResp *rateResp; // @synthesize rateResp=_rateResp;
@property(nonatomic) long long cash; // @synthesize cash=_cash;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)showRequestErrorMsg:(id)arg1;
- (void)finallyWithDraw:(id)arg1;
- (void)withDrawByPassword:(id)arg1;
- (void)preparePayAlert;
- (void)withDrawButtonClick;
- (void)showQuestion;
- (void)chooseBank;
- (void)textDidChange;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)allWithDraw;
- (void)setWithdrawButtonEnable;
- (void)setLeftMoneyLabAttributedText;
- (void)creatChildView;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

