//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SGWXToll : NSObject
{
    CDUnknownBlockType _wxCodeBlock;
}

+ (id)shareInstance;
@property(copy, nonatomic) CDUnknownBlockType wxCodeBlock; // @synthesize wxCodeBlock=_wxCodeBlock;
- (void).cxx_destruct;
- (void)reportWXTopuo:(long long)arg1 wxErrCode:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)withDrawWXWithWithdrawId:(long long)arg1 withdrawAmount:(long long)arg2 payPasswd:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)wxWithDrawBrforeGetInfo:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)payWeChat:(id)arg1;
- (void)cleanWXAuth;
- (id)getWXrAuthResult;
- (void)requestTopUp:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cancleWXAuth:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)isWXpayAuthSet:(CDUnknownBlockType)arg1;
- (void)blindWx:(id)arg1 payPassword:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getWxOpenID:(id)arg1;
- (void)requestWxAuth;

@end

