//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGXmallPaymentChannelVO : NSObject
{
    _Bool _isSelect;
    NSString *_channelCode;
    NSString *_channelName;
    long long _minAmount;
    long long _maxAmount;
}

@property(nonatomic) _Bool isSelect; // @synthesize isSelect=_isSelect;
@property(nonatomic) long long maxAmount; // @synthesize maxAmount=_maxAmount;
@property(nonatomic) long long minAmount; // @synthesize minAmount=_minAmount;
@property(copy, nonatomic) NSString *channelName; // @synthesize channelName=_channelName;
@property(copy, nonatomic) NSString *channelCode; // @synthesize channelCode=_channelCode;
- (void).cxx_destruct;

@end

