//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SugramCallTool : NSObject
{
}

+ (void)callURLStr:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)callBackWith:(id)arg1 appId:(id)arg2 callBackType:(long long)arg3 completionHandler:(CDUnknownBlockType)arg4;

@end

