//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, SGInitiatePaymentResp, SGJSCallOCHandle, SGSendPacketPayView, SGTLAccountBalanceResp, SGWebViewController, SugramPayObject, UIButton, UILabel;

@interface SugramPayViewController : UIViewController
{
    SugramPayObject *_object;
    SGWebViewController *_webVC;
    SGJSCallOCHandle *_jsCallOCHandle;
    NSString *_paymentDir;
    UILabel *_amountLabel;
    UILabel *_thirdNameLabel;
    UIButton *_agreeBtn;
    SGInitiatePaymentResp *_resp;
    SGSendPacketPayView *_payAlertView;
    SGTLAccountBalanceResp *_accountBalance;
    unsigned long long _type;
}

+ (id)getSugramPayViewController:(unsigned long long)arg1;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) SGTLAccountBalanceResp *accountBalance; // @synthesize accountBalance=_accountBalance;
@property(retain, nonatomic) SGSendPacketPayView *payAlertView; // @synthesize payAlertView=_payAlertView;
@property(retain, nonatomic) SGInitiatePaymentResp *resp; // @synthesize resp=_resp;
@property(nonatomic) __weak UIButton *agreeBtn; // @synthesize agreeBtn=_agreeBtn;
@property(nonatomic) __weak UILabel *thirdNameLabel; // @synthesize thirdNameLabel=_thirdNameLabel;
@property(nonatomic) __weak UILabel *amountLabel; // @synthesize amountLabel=_amountLabel;
@property(copy, nonatomic) NSString *paymentDir; // @synthesize paymentDir=_paymentDir;
@property(retain, nonatomic) SGJSCallOCHandle *jsCallOCHandle; // @synthesize jsCallOCHandle=_jsCallOCHandle;
@property(nonatomic) __weak SGWebViewController *webVC; // @synthesize webVC=_webVC;
@property(retain, nonatomic) SugramPayObject *object; // @synthesize object=_object;
- (void).cxx_destruct;
- (void)getLqtState:(_Bool)arg1 nextBlock:(CDUnknownBlockType)arg2;
- (void)getTLAccountMoney;
- (void)checkRedpacketPayPassword:(CDUnknownBlockType)arg1;
- (void)checkAmoutReam:(CDUnknownBlockType)arg1;
- (void)payBy:(id)arg1 model:(id)arg2;
- (void)agreeAction:(id)arg1;
- (void)dismiss;
- (void)callBack:(long long)arg1 loginbaseObject:(id)arg2;
- (void)retry;
- (void)cancel;
- (void)setAmount:(double)arg1;
- (id)getItemWith:(id)arg1 action:(SEL)arg2;
- (void)setUIAfterLoadData;
- (void)loadData;
- (void)viewDidLoad;

@end

