//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JYangWalletViewController.h"

#import "UIAlertViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, NSTimer, UIButton, UIImageView, UITextField, UIView;
@protocol WalletVriPwdDelegate;

@interface WalletVerifyPasswordViewController : JYangWalletViewController <UITextFieldDelegate, UIAlertViewDelegate>
{
    UIView *BG_View;
    UITextField *pwdF;
    UIImageView *pwdBGView;
    UIButton *forgetBtn;
    NSString *pwdString;
    int totalTime;
    NSTimer *codeTimer;
    _Bool _isVriCode;
    _Bool _isVriPwd;
    _Bool _isQuickRedeem;
    _Bool _isServiceCharge;
    _Bool _isUnBind;
    CDUnknownBlockType _verifyMsgBlock;
    CDUnknownBlockType _failBlock;
    id <WalletVriPwdDelegate> _delegate;
    NSString *_vriCodeJDId;
    NSString *_vriCodeParameter;
    NSString *_vriPwdParameter;
    NSString *_bankCardNo;
}

@property(retain, nonatomic) NSString *bankCardNo; // @synthesize bankCardNo=_bankCardNo;
@property(nonatomic) _Bool isUnBind; // @synthesize isUnBind=_isUnBind;
@property(nonatomic) _Bool isServiceCharge; // @synthesize isServiceCharge=_isServiceCharge;
@property(nonatomic) _Bool isQuickRedeem; // @synthesize isQuickRedeem=_isQuickRedeem;
@property(retain, nonatomic) NSString *vriPwdParameter; // @synthesize vriPwdParameter=_vriPwdParameter;
@property(nonatomic) _Bool isVriPwd; // @synthesize isVriPwd=_isVriPwd;
@property(retain, nonatomic) NSString *vriCodeParameter; // @synthesize vriCodeParameter=_vriCodeParameter;
@property(retain, nonatomic) NSString *vriCodeJDId; // @synthesize vriCodeJDId=_vriCodeJDId;
@property(nonatomic) _Bool isVriCode; // @synthesize isVriCode=_isVriCode;
@property(nonatomic) __weak id <WalletVriPwdDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType verifyMsgBlock; // @synthesize verifyMsgBlock=_verifyMsgBlock;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)showSelf:(id)arg1;
- (void)doActionDestroyDone;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)doActionClickExit;
- (void)doActionClickGetCode;
- (void)doActionClickForgetPwd;
- (void)doNotificationGetCodeRepeat;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)doChangePassWordPointWithString:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)postGetVerifyUnBindPwdRequest;
- (void)postGetVerifyCodeRequest;
- (void)postGetVerifyPasswordRequest;
- (void)doActionTimeChange;
- (void)doMakeBGView;
- (void)doBecomeFirstRsp;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

