//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JYangWalletViewController.h"

@class NSString, UIThemeButton, WalletItemView;

@interface WalletModifyUserInfoViewController : JYangWalletViewController
{
    WalletItemView *nameView;
    WalletItemView *IDView;
    UIThemeButton *editBtn;
    _Bool _isAuthFind;
    _Bool _isSetUserInfo;
    _Bool _isEditUserInfo;
    CDUnknownBlockType _editUserInfoBlock;
    CDUnknownBlockType _vriFindEditBlock;
    NSString *_userName;
    NSString *_userID;
    NSString *_vc_title;
}

@property(copy, nonatomic) NSString *vc_title; // @synthesize vc_title=_vc_title;
@property(retain, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) _Bool isEditUserInfo; // @synthesize isEditUserInfo=_isEditUserInfo;
@property(nonatomic) _Bool isSetUserInfo; // @synthesize isSetUserInfo=_isSetUserInfo;
@property(nonatomic) _Bool isAuthFind; // @synthesize isAuthFind=_isAuthFind;
@property(copy, nonatomic) CDUnknownBlockType vriFindEditBlock; // @synthesize vriFindEditBlock=_vriFindEditBlock;
@property(copy, nonatomic) CDUnknownBlockType editUserInfoBlock; // @synthesize editUserInfoBlock=_editUserInfoBlock;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)doActionSubmitUserInfo;
- (void)doActionVerifyUserInfo;
- (void)doActionSaveUserInfo;
- (_Bool)doformatInputData;
- (void)postGetFindPasswordVerifyUserInfoRequest;
- (void)postGetSaveUserInfo;
- (void)doActionClickTap;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

