//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JYangWalletViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, NSTimer, WalletItemView;

@interface WalletAddBankCardViewController : JYangWalletViewController <UITextFieldDelegate>
{
    WalletItemView *nameView;
    WalletItemView *IDView;
    WalletItemView *bankCardNoView;
    WalletItemView *phoneView;
    WalletItemView *codeView;
    NSString *mobileToken;
    _Bool firstBinding;
    NSTimer *codeTimer;
    int totalTime;
    _Bool _isCheckReal;
    NSString *_bankName;
    NSString *_bankCardNo;
    NSString *_bankNo;
    NSString *_userName;
    NSString *_userIDCard;
    NSString *_noteStr;
}

@property(copy, nonatomic) NSString *noteStr; // @synthesize noteStr=_noteStr;
@property(retain, nonatomic) NSString *userIDCard; // @synthesize userIDCard=_userIDCard;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) _Bool isCheckReal; // @synthesize isCheckReal=_isCheckReal;
@property(retain, nonatomic) NSString *bankNo; // @synthesize bankNo=_bankNo;
@property(retain, nonatomic) NSString *bankCardNo; // @synthesize bankCardNo=_bankCardNo;
@property(retain, nonatomic) NSString *bankName; // @synthesize bankName=_bankName;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)doActionClickTreaty:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)doChangeTimerValues;
- (void)postGetBindindCardVerifyCodeRequest;
- (void)postGetBindindCardCodeRequest;
- (void)doActionClickSubmit;
- (void)doActionClickGetCode;
- (void)doActionClickTap;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

