//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WalletPacketInfoObj : NSObject
{
    _Bool _isSend;
    _Bool _isPin;
    _Bool _isGetDone;
    _Bool _isOverDue;
    _Bool _isBest;
    NSString *_packetID;
    NSString *_timeStr;
    NSString *_amountStr;
    NSString *_totalStr;
    NSString *_getStr;
    long long _isReturnMoney;
}

@property(nonatomic) long long isReturnMoney; // @synthesize isReturnMoney=_isReturnMoney;
@property(nonatomic) _Bool isBest; // @synthesize isBest=_isBest;
@property(retain, nonatomic) NSString *getStr; // @synthesize getStr=_getStr;
@property(retain, nonatomic) NSString *totalStr; // @synthesize totalStr=_totalStr;
@property(nonatomic) _Bool isOverDue; // @synthesize isOverDue=_isOverDue;
@property(nonatomic) _Bool isGetDone; // @synthesize isGetDone=_isGetDone;
@property(retain, nonatomic) NSString *amountStr; // @synthesize amountStr=_amountStr;
@property(retain, nonatomic) NSString *timeStr; // @synthesize timeStr=_timeStr;
@property(nonatomic) _Bool isPin; // @synthesize isPin=_isPin;
@property(nonatomic) _Bool isSend; // @synthesize isSend=_isSend;
@property(retain, nonatomic) NSString *packetID; // @synthesize packetID=_packetID;
- (void).cxx_destruct;

@end

