//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UIButton, UIImageView, UILabel, UIView;

@interface WalletBankCardCell : UITableViewCell
{
    NSString *_BG_Color;
    UIView *_BG_View;
    UIImageView *_iconImgView;
    UILabel *_bankCardNameLab;
    UILabel *_bankCardNoLab;
    UIButton *_unBindBtn;
}

@property(retain, nonatomic) UIButton *unBindBtn; // @synthesize unBindBtn=_unBindBtn;
@property(retain, nonatomic) UILabel *bankCardNoLab; // @synthesize bankCardNoLab=_bankCardNoLab;
@property(retain, nonatomic) UILabel *bankCardNameLab; // @synthesize bankCardNameLab=_bankCardNameLab;
@property(retain, nonatomic) UIImageView *iconImgView; // @synthesize iconImgView=_iconImgView;
@property(retain, nonatomic) UIView *BG_View; // @synthesize BG_View=_BG_View;
@property(retain, nonatomic) NSString *BG_Color; // @synthesize BG_Color=_BG_Color;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)doFormatBankCardNameLab;
- (void)dobuildingWalletBankCardCell;
- (void)awakeFromNib;

@end

