//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIBarButtonItem;

@interface WKBaseWebView : UIViewController <UIGestureRecognizerDelegate>
{
    _Bool _animatedFlag;
    UIBarButtonItem *_backItem;
    UIBarButtonItem *_closeItem;
    long long _previousIndex;
}

@property(nonatomic) _Bool animatedFlag; // @synthesize animatedFlag=_animatedFlag;
@property(nonatomic) long long previousIndex; // @synthesize previousIndex=_previousIndex;
@property(retain, nonatomic) UIBarButtonItem *closeItem; // @synthesize closeItem=_closeItem;
@property(retain, nonatomic) UIBarButtonItem *backItem; // @synthesize backItem=_backItem;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)clickClose;
- (long long)preferredStatusBarStyle;
- (void)popToBackForwardListItem:(id)arg1 WebView:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

